-- ============================================
-- Platform: SNOWFLAKE
-- Schema/Source: COMPLIANCE_ARCHIVE
-- Generated: 2026-03-18T12:18:16.819669
-- Datasets: 2
-- ============================================

-- Dataset: GDS42832
CREATE SCHEMA IF NOT EXISTS COMPLIANCE_ARCHIVE;

-- This client dataset supports consumer finance operations. Key applications include relationship mana
CREATE TABLE IF NOT EXISTS COMPLIANCE_ARCHIVE.CLIENT_FILE_ARCHIVE (
    ID NUMBER(18,0) NOT NULL,
    CLIENT_ARCHIVE_ID VARCHAR(36) NOT NULL,
    MASREPH_CLIENT_ID VARCHAR(255) NOT NULL,
    EXTERNAL_CRM_CLIENT_ID VARCHAR(255),
    CLIENT_IBAN_PRIMARY VARCHAR(34),
    CLIENT_FULL_NAME VARCHAR(255) NOT NULL,
    CLIENT_TYPE_CODE VARCHAR(255) NOT NULL,
    RESIDENCY_COUNTRY_CODE VARCHAR(255) NOT NULL,
    DATE_OF_BIRTH DATE,
    CLIENT_ONBOARDING_DATE DATE NOT NULL,
    CLIENT_OFFBOARDING_DATE DATE,
    IS_CLIENT_ACTIVE BOOLEAN NOT NULL,
    CLIENT_RISK_RATING NUMBER(18,0),
    CLIENT_PROFITABILITY_SEGMENT VARCHAR(255),
    LAST_CONTACT_TIMESTAMP TIMESTAMP_NTZ,
    PREFERRED_CONTACT_CHANNEL VARCHAR(320),
    EMAIL_ADDRESS VARCHAR(320),
    MOBILE_PHONE_NUMBER VARCHAR(255),
    AGGREGATE_CURRENT_BALANCE_EUR NUMBER(18,2) NOT NULL,
    TWELVE_MONTH_REVENUE_EUR NUMBER(18,2),
    TWELVE_MONTH_INTEREST_EXPENSE_EUR NUMBER(18,2),
    RELATIONSHIP_MANAGER_ID VARCHAR(255),
    GDPR_CONSENT_FLAG BOOLEAN NOT NULL,
    GDPR_CONSENT_LAST_UPDATED TIMESTAMP_NTZ,
    CLIENT_LIFECYCLE_STATUS_CODE VARCHAR(255) NOT NULL,
    LAST_TRANSACTION_TIMESTAMP TIMESTAMP_NTZ,
    CLIENT_PRODUCT_RELATIONSHIPS VARIANT,
    _LOADED_AT TIMESTAMP_NTZ,
    _SOURCE_SYSTEM VARCHAR(255)
    ,CONSTRAINT PK_CLIENT_FILE_ARCHIVE PRIMARY KEY (ID)
);


-- Dataset: GDS59994
CREATE SCHEMA IF NOT EXISTS COMPLIANCE_ARCHIVE;

-- This client dataset supports mobility solutions operations. Key applications include relationship ma
CREATE TABLE IF NOT EXISTS COMPLIANCE_ARCHIVE.CLIENT_FILE_ARCHIVE (
    ID NUMBER(18,0) NOT NULL,
    CLIENT_ID VARCHAR(36) NOT NULL,
    MASREPH_ENTITY_ID VARCHAR(255) NOT NULL,
    CLIENT_TYPE VARCHAR(255) NOT NULL,
    LEGAL_NAME VARCHAR(255) NOT NULL,
    PREFERRED_NAME VARCHAR(255),
    COUNTRY_OF_RESIDENCE VARCHAR(255) NOT NULL,
    PRIMARY_CONTACT_EMAIL VARCHAR(320),
    PRIMARY_CONTACT_PHONE VARCHAR(255),
    DATE_OF_BIRTH DATE,
    CLIENT_ONBOARDING_DATE DATE NOT NULL,
    CLIENT_OFFBOARDING_DATE DATE,
    KYC_COMPLETION_STATUS VARCHAR(255) NOT NULL,
    AML_RISK_RATING VARCHAR(255) NOT NULL,
    GDPR_CONSENT_FLAG BOOLEAN NOT NULL,
    GDPR_CONSENT_TIMESTAMP TIMESTAMP_NTZ,
    MOBILITY_SEGMENT VARCHAR(255),
    PRIMARY_PRODUCT_RELATIONSHIP VARCHAR(255) NOT NULL,
    TOTAL_OUTSTANDING_AUTO_LOAN_BALANCE NUMBER(15,2) NOT NULL,
    TOTAL_DEPOSIT_BALANCE NUMBER(15,2) NOT NULL,
    YTD_INTEREST_INCOME NUMBER(15,2) NOT NULL,
    YTD_FEE_INCOME NUMBER(15,2) NOT NULL,
    LAST_TRANSACTION_TIMESTAMP TIMESTAMP_NTZ,
    LAST_AUTO_LOAN_PAYMENT_DATE DATE,
    DELINQUENCY_STATUS VARCHAR(255) NOT NULL,
    DAYS_PAST_DUE NUMBER(18,0) NOT NULL,
    RELATIONSHIP_MANAGER_ID VARCHAR(255),
    RELATIONSHIP_MANAGER_REGION VARCHAR(255),
    CLIENT_PROFITABILITY_SCORE NUMBER(5,2) NOT NULL,
    CLIENT_LIFETIME_VALUE_EUR NUMBER(18,2) NOT NULL,
    PREFERRED_COMMUNICATION_CHANNEL VARCHAR(320),
    CRM_SOURCE_SYSTEM VARCHAR(255) NOT NULL,
    RECORD_EFFECTIVE_DATE DATE NOT NULL,
    RECORD_EXPIRY_DATE DATE,
    DATA_RECORD_STATUS VARCHAR(255) NOT NULL,
    DATA_LINEAGE_REFERENCE VARCHAR(255),
    PII_MASKING_LEVEL VARCHAR(255) NOT NULL,
    _LOADED_AT TIMESTAMP_NTZ,
    _SOURCE_SYSTEM VARCHAR(255)
    ,CONSTRAINT PK_CLIENT_FILE_ARCHIVE PRIMARY KEY (ID)
);


