-- ============================================
-- Platform: SNOWFLAKE
-- Schema/Source: CRC_SYSTEMS
-- Generated: 2026-03-18T12:18:16.812084
-- Datasets: 2
-- ============================================

-- Dataset: GDS21645
CREATE SCHEMA IF NOT EXISTS CRC_SYSTEMS;

-- This product dataset supports leasing operations. Key applications include product performance analy
CREATE TABLE IF NOT EXISTS CRC_SYSTEMS.FINANCE_PORTFOLIO_CONTRACTS (
    ID NUMBER(18,0) NOT NULL,
    CONTRACT_ID VARCHAR(255) NOT NULL,
    PORTFOLIO_ID VARCHAR(255) NOT NULL,
    CUSTOMER_INTERNAL_ID VARCHAR(36) NOT NULL,
    CONTRACT_NUMBER VARCHAR(255) NOT NULL,
    PRODUCT_CODE VARCHAR(255) NOT NULL,
    PRODUCT_NAME VARCHAR(255) NOT NULL,
    ASSET_CATEGORY VARCHAR(255) NOT NULL,
    CONTRACT_START_DATE DATE NOT NULL,
    CONTRACT_END_DATE DATE NOT NULL,
    CONTRACT_SIGNATURE_TIMESTAMP TIMESTAMP_NTZ NOT NULL,
    CONTRACT_STATUS VARCHAR(255) NOT NULL,
    ORIGINAL_PRINCIPAL_AMOUNT NUMBER(15,2) NOT NULL,
    CURRENT_OUTSTANDING_PRINCIPAL NUMBER(15,2) NOT NULL,
    CONTRACT_CURRENCY VARCHAR(255) NOT NULL,
    INTEREST_RATE_TYPE VARCHAR(255) NOT NULL,
    NOMINAL_INTEREST_RATE NUMBER(5,3) NOT NULL,
    EFFECTIVE_ANNUAL_RATE NUMBER(6,3),
    LEASE_TERM_MONTHS NUMBER(18,0) NOT NULL,
    REMAINING_TERM_MONTHS NUMBER(18,0) NOT NULL,
    PAYMENT_FREQUENCY VARCHAR(255) NOT NULL,
    SCHEDULED_PAYMENT_AMOUNT NUMBER(15,2) NOT NULL,
    BALLOON_PAYMENT_AMOUNT NUMBER(15,2),
    RESIDUAL_VALUE_GUARANTEED NUMBER(15,2),
    COLLATERAL_TYPE VARCHAR(255),
    COLLATERAL_VALUATION_AMOUNT NUMBER(15,2),
    RISK_RATING_INTERNAL VARCHAR(255),
    PROBABILITY_OF_DEFAULT_12M NUMBER(6,4),
    LOSS_GIVEN_DEFAULT NUMBER(5,4),
    EXPECTED_LOSS_AMOUNT NUMBER(18,4),
    CONTRACT_YIELD_TO_MATURITY NUMBER(6,3),
    CUMULATIVE_INTEREST_INCOME NUMBER(18,2),
    CUMULATIVE_FEE_INCOME NUMBER(18,2),
    DAYS_PAST_DUE NUMBER(18,0) NOT NULL,
    NON_PERFORMING_FLAG BOOLEAN NOT NULL,
    WRITEOFF_DATE DATE,
    EARLY_TERMINATION_FLAG BOOLEAN NOT NULL,
    EARLY_TERMINATION_DATE DATE,
    SECTOR_CLASSIFICATION VARCHAR(255),
    COUNTRY_OF_RISK VARCHAR(255) NOT NULL,
    BOOKING_BRANCH_ID VARCHAR(255) NOT NULL,
    ORIGINATION_CHANNEL VARCHAR(255) NOT NULL,
    LINKED_INVESTMENT_PRODUCT_ID VARCHAR(255),
    CROSS_SELL_SCORE NUMBER(5,4),
    CONTRACT_CREATION_SYSTEM VARCHAR(255) NOT NULL,
    LAST_STATUS_UPDATE_TIMESTAMP TIMESTAMP_NTZ NOT NULL,
    GDPR_PSEUDONYMIZED_FLAG BOOLEAN NOT NULL,
    EXPECTED_RESIDUAL_REALIZATION_DATE DATE,
    SCENARIO_RISK_BUCKET VARCHAR(255),
    CONTRACT_NOTES VARCHAR(255),
    _LOADED_AT TIMESTAMP_NTZ,
    _SOURCE_SYSTEM VARCHAR(255)
    ,CONSTRAINT PK_FINANCE_PORTFOLIO_CO PRIMARY KEY (ID)
);


-- Dataset: GDS84625
CREATE SCHEMA IF NOT EXISTS CRC_SYSTEMS;

-- This product dataset supports consumer finance operations. Key applications include product performa
CREATE TABLE IF NOT EXISTS CRC_SYSTEMS.FINANCE_PORTFOLIO_CONTRACTS (
    ID NUMBER(18,0) NOT NULL,
    CONTRACT_ID VARCHAR(36) NOT NULL,
    PORTFOLIO_ID VARCHAR(255) NOT NULL,
    CUSTOMER_INTERNAL_ID VARCHAR(255) NOT NULL,
    IBAN_MASKED VARCHAR(34),
    CONTRACT_TYPE VARCHAR(255) NOT NULL,
    PRODUCT_CODE VARCHAR(255) NOT NULL,
    PRODUCT_NAME VARCHAR(255) NOT NULL,
    CURRENCY_CODE VARCHAR(255) NOT NULL,
    CONTRACT_START_DATE DATE NOT NULL,
    CONTRACT_END_DATE DATE,
    CONTRACT_STATUS VARCHAR(255) NOT NULL,
    BOOKING_BRANCH_CODE VARCHAR(255),
    RISK_PROFILE_CODE VARCHAR(255),
    RISK_PROFILE_LAST_ASSESSED_DATE DATE,
    INVESTMENT_STRATEGY VARCHAR(255),
    INVESTMENT_RISK_FLAGS VARIANT,
    INITIAL_DEPOSIT_AMOUNT NUMBER(15,2) NOT NULL,
    CURRENT_BALANCE_AMOUNT NUMBER(18,2) NOT NULL,
    ACCRUED_INTEREST_AMOUNT NUMBER(18,2) NOT NULL,
    INTEREST_RATE_ANNUAL NUMBER(7,4) NOT NULL,
    INTEREST_CALCULATION_METHOD VARCHAR(255) NOT NULL,
    LAST_INTEREST_ACCRUAL_DATE DATE,
    NEXT_REPRICING_DATE DATE,
    CONTRACT_MATURITY_DATE DATE,
    AUTO_RENEWAL_FLAG BOOLEAN NOT NULL,
    EARLY_WITHDRAWAL_PENALTY_RATE NUMBER(5,2),
    PORTFOLIO_SEGMENT VARCHAR(255),
    CUSTOMER_RESIDENCY_COUNTRY VARCHAR(255),
    CHANNEL_OF_ORIGIN VARCHAR(255),
    CROSS_SELL_ELIGIBILITY_SCORE NUMBER(5,2),
    PRODUCT_PERFORMANCE_RATING NUMBER(3,2),
    EXPECTED_ANNUAL_RETURN_RATE NUMBER(7,4),
    VALUE_AT_RISK_99 NUMBER(18,4),
    STRESS_LOSS_SCENARIO_AMOUNT NUMBER(18,2),
    BENCHMARK_INDICES VARIANT,
    LAST_TRANSACTION_TIMESTAMP TIMESTAMP_NTZ,
    RECORD_CREATED_TIMESTAMP TIMESTAMP_NTZ NOT NULL,
    RECORD_LAST_UPDATED_TIMESTAMP TIMESTAMP_NTZ NOT NULL,
    _LOADED_AT TIMESTAMP_NTZ,
    _SOURCE_SYSTEM VARCHAR(255)
    ,CONSTRAINT PK_FINANCE_PORTFOLIO_CO PRIMARY KEY (ID)
);


