-- ============================================
-- Platform: SNOWFLAKE
-- Schema/Source: CREDIT_RISK_INSIGHTS
-- Generated: 2026-03-18T12:18:16.819669
-- Datasets: 3
-- ============================================

-- Dataset: GDS43693
CREATE SCHEMA IF NOT EXISTS CREDIT_RISK_INSIGHTS;

-- This risk management dataset supports consumer finance operations. Key applications include data ana
CREATE TABLE IF NOT EXISTS CREDIT_RISK_INSIGHTS.CREDIT_RISK_INSIGHTS_DATASET (
    ID NUMBER(18,0) NOT NULL,
    LOAN_ACCOUNT_ID VARCHAR(255) NOT NULL,
    CUSTOMER_ID VARCHAR(255) NOT NULL,
    APPLICATION_ID VARCHAR(255) NOT NULL,
    PRODUCT_TYPE VARCHAR(255) NOT NULL,
    INTEREST_RATE_ANNUAL NUMBER(5,3) NOT NULL,
    LOAN_AMOUNT_ORIGINAL NUMBER(15,2) NOT NULL,
    LOAN_TERM_MONTHS NUMBER(18,0) NOT NULL,
    LOAN_DISBURSEMENT_DATE DATE NOT NULL,
    LOAN_MATURITY_DATE DATE,
    CURRENT_OUTSTANDING_BALANCE NUMBER(15,2) NOT NULL,
    DAYS_PAST_DUE NUMBER(18,0) NOT NULL,
    DELINQUENCY_STATUS VARCHAR(255) NOT NULL,
    CREDIT_RISK_GRADE VARCHAR(255) NOT NULL,
    PROBABILITY_OF_DEFAULT_12M NUMBER(6,5) NOT NULL,
    LOSS_GIVEN_DEFAULT_ESTIMATE NUMBER(5,4) NOT NULL,
    EXPOSURE_AT_DEFAULT_ESTIMATE NUMBER(15,2) NOT NULL,
    BEHAVIORAL_SCORECARD_SCORE NUMBER(18,0),
    APPLICATION_SCORECARD_SCORE NUMBER(18,0) NOT NULL,
    DEBT_TO_INCOME_RATIO NUMBER(5,3),
    INCOME_VERIFIED_FLAG BOOLEAN NOT NULL,
    ANNUAL_GROSS_INCOME NUMBER(15,2),
    EMPLOYMENT_STATUS VARCHAR(255),
    COUNTRY_OF_RESIDENCE VARCHAR(255) NOT NULL,
    CUSTOMER_SEGMENT VARCHAR(255),
    CONSENT_MARKETING_FLAG BOOLEAN NOT NULL,
    CONSENT_DATA_PROCESSING_FLAG BOOLEAN NOT NULL,
    DATE_OF_BIRTH DATE NOT NULL,
    ACCOUNT_OPEN_DATE DATE NOT NULL,
    LAST_PAYMENT_DATE DATE,
    LAST_PAYMENT_AMOUNT NUMBER(15,2),
    NEXT_PAYMENT_DUE_DATE DATE,
    NEXT_PAYMENT_AMOUNT_DUE NUMBER(15,2),
    NONPERFORMING_LOAN_FLAG BOOLEAN NOT NULL,
    WRITE_OFF_FLAG BOOLEAN NOT NULL,
    WRITE_OFF_DATE DATE,
    RESTRUCTURING_FLAG BOOLEAN NOT NULL,
    COLLATERAL_TYPE VARCHAR(255),
    COLLATERAL_VALUE NUMBER(15,2),
    DEFAULT_DATE DATE,
    RECOVERY_AMOUNT_TO_DATE NUMBER(15,2),
    PD_MODEL_VERSION VARCHAR(255) NOT NULL,
    RISK_REVIEW_TIMESTAMP TIMESTAMP_NTZ,
    DATA_SOURCE_SYSTEM VARCHAR(255) NOT NULL,
    RECORD_CREATION_TIMESTAMP TIMESTAMP_NTZ NOT NULL,
    _LOADED_AT TIMESTAMP_NTZ,
    _SOURCE_SYSTEM VARCHAR(255)
    ,CONSTRAINT PK_CREDIT_RISK_INSIGHTS PRIMARY KEY (ID)
);


-- Dataset: GDS49450
CREATE SCHEMA IF NOT EXISTS CREDIT_RISK_INSIGHTS;

-- This risk management dataset supports commercial finance operations. Key applications include data a
CREATE TABLE IF NOT EXISTS CREDIT_RISK_INSIGHTS.CREDIT_RISK_INSIGHTS_DATASET (
    ID NUMBER(18,0) NOT NULL,
    MASREPH_CUSTOMER_ID VARCHAR(255) NOT NULL,
    COUNTERPARTY_LEGAL_NAME VARCHAR(255) NOT NULL,
    COUNTERPARTY_COUNTRY_OF_DOMICILE VARCHAR(255) NOT NULL,
    COUNTERPARTY_INDUSTRY_CODE_NACE VARCHAR(255) NOT NULL,
    GROUP_EXPOSURE_ID VARCHAR(255),
    FACILITY_ID VARCHAR(255) NOT NULL,
    LOAN_ACCOUNT_NUMBER VARCHAR(255) NOT NULL,
    IBAN_PRIMARY_DISBURSEMENT VARCHAR(34),
    PRODUCT_TYPE_CODE VARCHAR(255) NOT NULL,
    CURRENCY_CODE VARCHAR(255) NOT NULL,
    ORIGINAL_FACILITY_LIMIT_AMOUNT NUMBER(18,2) NOT NULL,
    CURRENT_OUTSTANDING_AMOUNT NUMBER(18,2) NOT NULL,
    UNDRAWN_COMMITTED_AMOUNT NUMBER(18,2),
    INTEREST_RATE_TYPE VARCHAR(255) NOT NULL,
    REFERENCE_RATE_INDEX VARCHAR(255),
    INTEREST_MARGIN_BPS NUMBER(18,0),
    EFFECTIVE_INTEREST_RATE NUMBER(7,4),
    ORIGINATION_DATE DATE NOT NULL,
    MATURITY_DATE DATE NOT NULL,
    NEXT_PAYMENT_DUE_DATE DATE,
    DAYS_PAST_DUE NUMBER(18,0) NOT NULL,
    CREDIT_RISK_GRADE_INTERNAL VARCHAR(255) NOT NULL,
    PROBABILITY_OF_DEFAULT_12M NUMBER(10,6) NOT NULL,
    LOSS_GIVEN_DEFAULT_ESTIMATE NUMBER(5,4) NOT NULL,
    EXPOSURE_AT_DEFAULT_EAD NUMBER(18,2) NOT NULL,
    EXPECTED_CREDIT_LOSS_STAGE VARCHAR(255) NOT NULL,
    LIFETIME_EXPECTED_CREDIT_LOSS NUMBER(18,2),
    COLLATERAL_COVERAGE_RATIO NUMBER(7,4),
    PRIMARY_COLLATERAL_TYPE VARCHAR(255),
    COLLATERAL_VALUATION_DATE DATE,
    LATEST_FINANCIAL_STATEMENT_DATE DATE,
    LATEST_EBITDA_AMOUNT NUMBER(18,2),
    TOTAL_DEBT_TO_EBITDA_RATIO NUMBER(9,4),
    INTEREST_COVERAGE_RATIO NUMBER(9,4),
    COUNTERPARTY_EXTERNAL_RATING VARCHAR(255),
    DEFAULT_STATUS_FLAG BOOLEAN NOT NULL,
    DATE_OF_DEFAULT DATE,
    NON_PERFORMING_EXPOSURE_FLAG BOOLEAN NOT NULL,
    RESTRUCTURING_STATUS VARCHAR(255) NOT NULL,
    MASREPH_SEGMENT_CODE VARCHAR(255) NOT NULL,
    RELATIONSHIP_MANAGER_ID VARCHAR(255),
    CUSTOMER_MARKETING_CONSENT_FLAG BOOLEAN NOT NULL,
    GDPR_PSEUDONYMIZED_CUSTOMER_KEY VARCHAR(36),
    CUSTOMER_REGISTERED_ADDRESS_COUNTRY VARCHAR(255),
    ULTIMATE_BENEFICIAL_OWNER_FLAG BOOLEAN NOT NULL,
    SANCTIONS_SCREENING_STATUS VARCHAR(255) NOT NULL,
    LAST_CREDIT_REVIEW_DATE DATE,
    NEXT_CREDIT_REVIEW_DUE_DATE DATE,
    DATA_RECORD_CREATED_TIMESTAMP TIMESTAMP_NTZ NOT NULL,
    DATA_RECORD_LAST_UPDATED_TIMESTAMP TIMESTAMP_NTZ NOT NULL,
    RISK_MITIGATION_INSTRUMENTS VARIANT,
    COVENANT_BREACH_STATUS VARCHAR(255) NOT NULL,
    FACILITY_RISK_SUMMARY VARIANT,
    _LOADED_AT TIMESTAMP_NTZ,
    _SOURCE_SYSTEM VARCHAR(255)
    ,CONSTRAINT PK_CREDIT_RISK_INSIGHTS PRIMARY KEY (ID)
);


-- Dataset: GDS74246
CREATE SCHEMA IF NOT EXISTS CREDIT_RISK_INSIGHTS;

-- This risk management dataset supports mobility solutions operations. Key applications include data a
CREATE TABLE IF NOT EXISTS CREDIT_RISK_INSIGHTS.CREDIT_RISK_INSIGHTS_DATASET (
    ID NUMBER(18,0) NOT NULL,
    DATASET_RECORD_ID VARCHAR(36) NOT NULL,
    CUSTOMER_INTERNAL_ID VARCHAR(255) NOT NULL,
    APPLICATION_ID VARCHAR(255) NOT NULL,
    VEHICLE_ID VARCHAR(255),
    CONTRACT_NUMBER VARCHAR(255),
    NATIONAL_IDENTIFIER_HASH VARCHAR(255),
    CUSTOMER_SEGMENT VARCHAR(255),
    COUNTRY_OF_RESIDENCE VARCHAR(255) NOT NULL,
    APPLICATION_SUBMISSION_TIMESTAMP TIMESTAMP_NTZ NOT NULL,
    CREDIT_DECISION_TIMESTAMP TIMESTAMP_NTZ,
    CREDIT_DECISION_STATUS VARCHAR(255) NOT NULL,
    CREDIT_DECISION_REASON_CODE VARCHAR(255),
    REQUESTED_LOAN_AMOUNT NUMBER(15,2) NOT NULL,
    APPROVED_LOAN_AMOUNT NUMBER(15,2),
    LOAN_CURRENCY_CODE VARCHAR(255) NOT NULL,
    LOAN_TERM_MONTHS NUMBER(18,0) NOT NULL,
    INTEREST_RATE_ANNUAL NUMBER(5,3) NOT NULL,
    RISK_GRADE VARCHAR(255) NOT NULL,
    PROBABILITY_OF_DEFAULT_12M NUMBER(5,4) NOT NULL,
    LOSS_GIVEN_DEFAULT_PERCENTAGE NUMBER(5,2) NOT NULL,
    EXPOSURE_AT_DEFAULT NUMBER(15,2) NOT NULL,
    DEBT_TO_INCOME_RATIO NUMBER(5,2),
    MONTHLY_NET_INCOME NUMBER(15,2),
    MONTHLY_HOUSING_COST NUMBER(15,2),
    EMPLOYMENT_STATUS VARCHAR(255),
    EMPLOYMENT_START_DATE DATE,
    INDUSTRY_SECTOR_CODE VARCHAR(255),
    AGE_AT_APPLICATION NUMBER(18,0),
    MARITAL_STATUS VARCHAR(255),
    NUMBER_OF_DEPENDENTS NUMBER(18,0),
    HAS_MARKETING_CONSENT BOOLEAN NOT NULL,
    CONSENT_CAPTURE_TIMESTAMP TIMESTAMP_NTZ,
    DATA_SOURCE_SYSTEM VARCHAR(255) NOT NULL,
    INSURANCE_POLICY_ID VARCHAR(255),
    INSURANCE_PREMIUM_AMOUNT NUMBER(15,2),
    INSURANCE_COVERAGE_LEVEL VARCHAR(255),
    VEHICLE_MARKET_VALUE NUMBER(15,2),
    VEHICLE_REGISTRATION_DATE DATE,
    MOBILITY_PRODUCT_TYPE VARCHAR(255) NOT NULL,
    ARREARS_STATUS VARCHAR(255) NOT NULL,
    DAYS_PAST_DUE NUMBER(18,0) NOT NULL,
    CURRENT_OUTSTANDING_BALANCE NUMBER(15,2) NOT NULL,
    RESTRUCTURING_FLAG BOOLEAN NOT NULL,
    DEFAULT_EVENT_DATE DATE,
    WRITE_OFF_AMOUNT NUMBER(15,2),
    RECORD_LAST_UPDATED_TIMESTAMP TIMESTAMP_NTZ NOT NULL,
    _LOADED_AT TIMESTAMP_NTZ,
    _SOURCE_SYSTEM VARCHAR(255)
    ,CONSTRAINT PK_CREDIT_RISK_INSIGHTS PRIMARY KEY (ID)
);


