-- ============================================
-- Platform: SNOWFLAKE
-- Schema/Source: CREDIT_RISK_CONTROLS
-- Generated: 2026-03-18T12:18:16.818667
-- Datasets: 1
-- ============================================

-- Dataset: GDS42292
CREATE SCHEMA IF NOT EXISTS CREDIT_RISK_CONTROLS;

-- This product dataset supports mobility solutions operations. Key applications include product perfor
CREATE TABLE IF NOT EXISTS CREDIT_RISK_CONTROLS.CREDIT_PAYMENT_AGREEMENTS_DATASET (
    ID NUMBER(18,0) NOT NULL,
    AGREEMENT_ID VARCHAR(36) NOT NULL,
    AGREEMENT_EXTERNAL_REF VARCHAR(255),
    CUSTOMER_ID VARCHAR(255) NOT NULL,
    VEHICLE_CONTRACT_ID VARCHAR(255) NOT NULL,
    LOAN_PRODUCT_CODE VARCHAR(255) NOT NULL,
    LOAN_PRODUCT_NAME VARCHAR(255) NOT NULL,
    AGREEMENT_STATUS VARCHAR(255) NOT NULL,
    AGREEMENT_START_DATE DATE NOT NULL,
    AGREEMENT_END_DATE DATE,
    ORIGINATION_CHANNEL VARCHAR(255) NOT NULL,
    COUNTRY_CODE VARCHAR(255) NOT NULL,
    CURRENCY_CODE VARCHAR(255) NOT NULL,
    ORIGINAL_PRINCIPAL_AMOUNT NUMBER(15,2) NOT NULL,
    CURRENT_OUTSTANDING_PRINCIPAL NUMBER(15,2) NOT NULL,
    INTEREST_RATE_ANNUAL NUMBER(5,3) NOT NULL,
    INTEREST_RATE_TYPE VARCHAR(255) NOT NULL,
    LOAN_TERM_MONTHS NUMBER(18,0) NOT NULL,
    REMAINING_TERM_MONTHS NUMBER(18,0),
    PAYMENT_FREQUENCY VARCHAR(255) NOT NULL,
    SCHEDULED_PAYMENT_AMOUNT NUMBER(13,2) NOT NULL,
    NEXT_DUE_DATE DATE,
    LAST_PAYMENT_DATE DATE,
    LAST_PAYMENT_AMOUNT NUMBER(13,2),
    TOTAL_PAID_PRINCIPAL_TO_DATE NUMBER(15,2) NOT NULL,
    TOTAL_PAID_INTEREST_TO_DATE NUMBER(15,2) NOT NULL,
    TOTAL_PAID_FEES_TO_DATE NUMBER(15,2) NOT NULL,
    DAYS_PAST_DUE NUMBER(18,0) NOT NULL,
    DELINQUENCY_STATUS VARCHAR(255) NOT NULL,
    NON_PAYMENT_REASON_CODE VARCHAR(255),
    RESTRUCTURED_FLAG BOOLEAN NOT NULL,
    RESTRUCTURING_EFFECTIVE_DATE DATE,
    BALLOON_PAYMENT_AMOUNT NUMBER(13,2),
    BALLOON_PAYMENT_DUE_DATE DATE,
    EARLY_SETTLEMENT_FLAG BOOLEAN NOT NULL,
    EARLY_SETTLEMENT_DATE DATE,
    COLLATERAL_VEHICLE_VIN VARCHAR(255),
    VEHICLE_CATEGORY VARCHAR(255),
    MOBILITY_USAGE_TYPE VARCHAR(255),
    MARKETING_SEGMENT_CODE VARCHAR(255),
    CROSS_SELL_OFFER_FLAG BOOLEAN NOT NULL,
    PAYMENT_METHOD_PREFERRED VARCHAR(255),
    MANDATE_REFERENCE VARCHAR(255),
    ARREARS_AMOUNT_TOTAL NUMBER(15,2) NOT NULL,
    ARREARS_PRINCIPAL_AMOUNT NUMBER(15,2) NOT NULL,
    ARREARS_INTEREST_AMOUNT NUMBER(15,2) NOT NULL,
    ARREARS_FEES_AMOUNT NUMBER(15,2) NOT NULL,
    AGREEMENT_CREATION_TIMESTAMP TIMESTAMP_NTZ NOT NULL,
    RECORD_LAST_UPDATED_TIMESTAMP TIMESTAMP_NTZ NOT NULL,
    DATA_SOURCE_SYSTEM VARCHAR(255) NOT NULL,
    GDPR_PERSONAL_DATA_FLAG BOOLEAN NOT NULL,
    PAYMENT_HISTORY_SUMMARY VARIANT,
    AGREEMENT_TAGS VARIANT,
    _LOADED_AT TIMESTAMP_NTZ,
    _SOURCE_SYSTEM VARCHAR(255)
    ,CONSTRAINT PK_CREDIT_PAYMENT_AGREE PRIMARY KEY (ID)
);


