-- ============================================
-- Platform: SNOWFLAKE
-- Schema/Source: ESRB_RATINGS
-- Generated: 2026-03-18T12:18:16.815092
-- Datasets: 2
-- ============================================

-- Dataset: GDS31723
CREATE SCHEMA IF NOT EXISTS ESRB_RATINGS;

-- This finance dataset supports consumer finance operations. Key applications include data analysis, r
CREATE TABLE IF NOT EXISTS ESRB_RATINGS.QUOTAFLEX_FINANCE_DATASET (
    ID NUMBER(18,0) NOT NULL,
    DATASET_RECORD_ID VARCHAR(36) NOT NULL,
    MASREPH_CUSTOMER_ID VARCHAR(255) NOT NULL,
    ACCOUNT_IBAN VARCHAR(34) NOT NULL,
    ACCOUNT_CURRENCY_CODE VARCHAR(255) NOT NULL,
    CUSTOMER_COUNTRY_CODE VARCHAR(255) NOT NULL,
    CUSTOMER_CONSENT_MARKETING BOOLEAN NOT NULL,
    CUSTOMER_CONSENT_DATA_PROCESSING BOOLEAN NOT NULL,
    PRODUCT_TYPE VARCHAR(255) NOT NULL,
    PRODUCT_SUB_TYPE VARCHAR(255),
    ACCOUNT_OPEN_DATE DATE NOT NULL,
    ACCOUNT_CLOSE_DATE DATE,
    REPORTING_DATE DATE NOT NULL,
    TRANSACTION_ID VARCHAR(36),
    TRANSACTION_TIMESTAMP TIMESTAMP_NTZ,
    TRANSACTION_AMOUNT NUMBER(15,2),
    TRANSACTION_CURRENCY_CODE VARCHAR(255),
    TRANSACTION_TYPE VARCHAR(255),
    TRANSACTION_CHANNEL VARCHAR(255),
    BALANCE_END_OF_DAY NUMBER(17,2),
    CREDIT_LIMIT_AMOUNT NUMBER(15,2),
    INTEREST_RATE_ANNUAL_PCT NUMBER(7,4),
    DELINQUENCY_STATUS VARCHAR(255),
    DAYS_PAST_DUE NUMBER(18,0),
    WRITE_OFF_FLAG BOOLEAN,
    WRITE_OFF_DATE DATE,
    BUDGET_SEGMENT VARCHAR(255),
    PROFITABILITY_SEGMENT VARCHAR(255),
    RISK_SCORE NUMBER(18,0),
    RISK_BAND VARCHAR(255),
    MARKETING_CAMPAIGN_ID VARCHAR(255),
    FORECASTED_REVENUE_12M NUMBER(17,2),
    ACTUAL_REVENUE_YTD NUMBER(17,2),
    COST_OF_FUNDS_RATE NUMBER(7,4),
    NET_INTEREST_MARGIN_PCT NUMBER(5,2),
    CUSTOMER_AGE_YEARS NUMBER(18,0),
    CUSTOMER_EMPLOYMENT_STATUS VARCHAR(255),
    GDP_REGION_CODE VARCHAR(255),
    DATA_SOURCE_SYSTEM VARCHAR(255) NOT NULL,
    IS_RECORD_ACTIVE BOOLEAN NOT NULL,
    RECORD_CREATED_TIMESTAMP TIMESTAMP_NTZ NOT NULL,
    RECORD_LAST_UPDATED_TIMESTAMP TIMESTAMP_NTZ NOT NULL,
    STREAMING_INGEST_BATCH_ID VARCHAR(255),
    CONSENT_CAPTURE_TIMESTAMP TIMESTAMP_NTZ,
    CUSTOMER_CONTACT_CHANNEL_PREFERENCES VARIANT,
    KYC_STATUS VARCHAR(255),
    PII_HASH_OBJECT VARIANT,
    _LOADED_AT TIMESTAMP_NTZ,
    _SOURCE_SYSTEM VARCHAR(255)
    ,CONSTRAINT PK_QUOTAFLEX_FINANCE_DA PRIMARY KEY (ID)
);


-- Dataset: GDS51958
CREATE SCHEMA IF NOT EXISTS ESRB_RATINGS;

-- This finance dataset supports leasing operations. Key applications include data analysis, reporting,
CREATE TABLE IF NOT EXISTS ESRB_RATINGS.QUOTAFLEX_FINANCE_TERMS (
    ID NUMBER(18,0) NOT NULL,
    TERM_ID VARCHAR(36) NOT NULL,
    TERM_CODE VARCHAR(255) NOT NULL,
    TERM_NAME VARCHAR(255) NOT NULL,
    TERM_CATEGORY VARCHAR(255) NOT NULL,
    TERM_DEFINITION VARCHAR(255) NOT NULL,
    CALCULATION_FORMULA VARCHAR(255),
    CALCULATION_EXAMPLE VARCHAR(255),
    STANDARD_LEASE_TENOR_MONTHS NUMBER(18,0),
    DEFAULT_INTEREST_RATE_PCT NUMBER(7,4),
    MINIMUM_FINANCED_AMOUNT_EUR NUMBER(15,2),
    MAXIMUM_FINANCED_AMOUNT_EUR NUMBER(15,2),
    RESIDUAL_VALUE_PCT NUMBER(5,2),
    EARLY_TERMINATION_FEE_PCT NUMBER(5,2),
    GRACE_PERIOD_DAYS NUMBER(18,0),
    COMPOUNDING_FREQUENCY VARCHAR(255),
    IS_IFRS9_RELEVANT BOOLEAN NOT NULL,
    EFFECTIVE_START_DATE DATE NOT NULL,
    EFFECTIVE_END_DATE DATE,
    LAST_REVIEW_TIMESTAMP TIMESTAMP_NTZ,
    CREATED_BY_USER_ID VARCHAR(255) NOT NULL,
    LAST_MODIFIED_BY_USER_ID VARCHAR(255),
    REGULATORY_REFERENCE VARCHAR(255),
    LANGUAGE_CODE VARCHAR(255) NOT NULL,
    COUNTRY_APPLICABILITY_LIST VARIANT,
    MARKETING_CONSENT_REQUIRED BOOLEAN NOT NULL,
    CUSTOMER_DATA_USAGE_SCOPE VARCHAR(255),
    MASREPH_INTERNAL_RISK_WEIGHT NUMBER(5,2),
    TERM_METADATA VARIANT,
    _LOADED_AT TIMESTAMP_NTZ,
    _SOURCE_SYSTEM VARCHAR(255)
    ,CONSTRAINT PK_QUOTAFLEX_FINANCE_TE PRIMARY KEY (ID)
);


