-- ============================================
-- Platform: SNOWFLAKE
-- Schema/Source: EUROCOMPLY
-- Generated: 2026-03-18T12:18:16.812084
-- Datasets: 4
-- ============================================

-- Dataset: GDS18189
CREATE SCHEMA IF NOT EXISTS EUROCOMPLY;

-- This product dataset supports leasing operations. Key applications include product performance analy
CREATE TABLE IF NOT EXISTS EUROCOMPLY.EUROCOMPLY_FINANCE_FILTER (
    ID NUMBER(18,0) NOT NULL,
    PRODUCT_ID VARCHAR(255) NOT NULL,
    PRODUCT_NAME VARCHAR(255) NOT NULL,
    PRODUCT_CATEGORY VARCHAR(255) NOT NULL,
    PRODUCT_SUB_CATEGORY VARCHAR(255),
    LEASE_CONTRACT_ID VARCHAR(255) NOT NULL,
    MASREPH_CUSTOMER_ID VARCHAR(255) NOT NULL,
    CUSTOMER_SEGMENT VARCHAR(255),
    LESSEE_LEGAL_NAME VARCHAR(255) NOT NULL,
    LESSEE_VAT_NUMBER VARCHAR(255),
    LESSEE_COUNTRY_CODE VARCHAR(255) NOT NULL,
    LESSEE_EU_MEMBER_STATE VARCHAR(255),
    LESSEE_INDUSTRY_NACE_CODE VARCHAR(255),
    LESSEE_CONTACT_DETAILS VARIANT,
    ASSET_TYPE VARCHAR(255) NOT NULL,
    ASSET_DESCRIPTION VARCHAR(255),
    ASSET_MARKET_VALUE_EUR NUMBER(15,2),
    LEASE_START_DATE DATE NOT NULL,
    LEASE_END_DATE DATE,
    LEASE_TERM_MONTHS NUMBER(18,0) NOT NULL,
    LEASE_CURRENCY_CODE VARCHAR(255) NOT NULL,
    LEASE_PRINCIPAL_AMOUNT NUMBER(18,2) NOT NULL,
    LEASE_INTEREST_RATE NUMBER(5,3) NOT NULL,
    LEASE_PAYMENT_FREQUENCY VARCHAR(255) NOT NULL,
    LEASE_STATUS VARCHAR(255) NOT NULL,
    NON_PERFORMING_EXPOSURE_FLAG BOOLEAN NOT NULL,
    DAYS_PAST_DUE NUMBER(18,0),
    IFRS9_STAGE VARCHAR(255),
    EXPECTED_CREDIT_LOSS_EUR NUMBER(18,2),
    GDPR_DATA_PROCESSING_LEGAL_BASIS VARCHAR(255),
    CONSENT_MARKETING_FLAG BOOLEAN,
    CONSENT_CROSS_SELLING_FLAG BOOLEAN,
    AML_RISK_RATING VARCHAR(255),
    KYC_REVIEW_DATE DATE,
    SANCTIONS_SCREENING_STATUS VARCHAR(255),
    REGULATORY_REPORTING_FLAGS VARIANT,
    ESG_RISK_SCORE NUMBER(5,2),
    EU_TAXONOMY_ALIGNMENT_FLAG BOOLEAN,
    PRODUCT_MARGIN_ANNUAL_PCT NUMBER(6,3),
    PRODUCT_ROI_ANNUAL_PCT NUMBER(6,3),
    PORTFOLIO_SEGMENT_CODE VARCHAR(255),
    PORTFOLIO_CONCENTRATION_LIMIT_PCT NUMBER(5,2),
    UTILIZATION_RATE_PCT NUMBER(5,2),
    REVENUE_YTD_EUR NUMBER(18,2),
    REVENUE_FORECAST_NEXT_12M_EUR NUMBER(18,2),
    CHURN_RISK_SCORE NUMBER(5,3),
    LAST_PRICING_REVIEW_TIMESTAMP TIMESTAMP_NTZ,
    RECORD_CREATION_TIMESTAMP TIMESTAMP_NTZ NOT NULL,
    RECORD_LAST_UPDATE_TIMESTAMP TIMESTAMP_NTZ NOT NULL,
    DATA_SOURCE_SYSTEM VARCHAR(255) NOT NULL,
    STREAMING_INGESTION_PARTITION_KEY VARCHAR(255) NOT NULL,
    _LOADED_AT TIMESTAMP_NTZ,
    _SOURCE_SYSTEM VARCHAR(255)
    ,CONSTRAINT PK_EUROCOMPLY_FINANCE_F PRIMARY KEY (ID)
);


-- Dataset: GDS36524
CREATE SCHEMA IF NOT EXISTS EUROCOMPLY;

-- This product dataset supports consumer finance operations. Key applications include product performa
CREATE TABLE IF NOT EXISTS EUROCOMPLY.EUROWIRE_COMPLIANCE_DATA (
    ID NUMBER(18,0) NOT NULL,
    DATASET_ID VARCHAR(36) NOT NULL,
    RECORD_ID VARCHAR(255) NOT NULL,
    MASREPH_CUSTOMER_ID VARCHAR(255) NOT NULL,
    EXTERNAL_CUSTOMER_ID VARCHAR(255),
    PRODUCT_ID VARCHAR(255) NOT NULL,
    PAYMENT_INSTRUMENT_ID VARCHAR(255),
    IBAN VARCHAR(34) NOT NULL,
    BIC VARCHAR(255),
    SEPA_MANDATE_ID VARCHAR(255),
    TRANSACTION_ID VARCHAR(255) NOT NULL,
    TRANSACTION_TIMESTAMP TIMESTAMP_NTZ NOT NULL,
    BOOKING_DATE DATE NOT NULL,
    VALUE_DATE DATE,
    PAYMENT_AMOUNT_EUR NUMBER(15,2) NOT NULL,
    PAYMENT_CURRENCY VARCHAR(255) NOT NULL,
    EXCHANGE_RATE_APPLIED NUMBER(10,6),
    FEE_AMOUNT_EUR NUMBER(15,2),
    FEE_TYPE VARCHAR(255),
    REVENUE_RECOGNITION_FLAG BOOLEAN NOT NULL,
    COMPLIANCE_CHECK_STATUS VARCHAR(255) NOT NULL,
    COMPLIANCE_BREACH_FLAG BOOLEAN NOT NULL,
    BREACH_TYPE_CODE VARCHAR(255),
    BREACH_SEVERITY_LEVEL VARCHAR(255),
    REMEDIATION_ACTION_CODES VARIANT,
    REMEDIATION_COMPLETION_TIMESTAMP TIMESTAMP_NTZ,
    GDPR_CONSENT_FLAG BOOLEAN NOT NULL,
    GDPR_CONSENT_CAPTURE_TIMESTAMP TIMESTAMP_NTZ,
    CUSTOMER_RESIDENCY_COUNTRY VARCHAR(255) NOT NULL,
    CUSTOMER_SEGMENT_CODE VARCHAR(255),
    PRODUCT_TYPE_CODE VARCHAR(255) NOT NULL,
    PRODUCT_RISK_RATING NUMBER(18,0) NOT NULL,
    AML_RISK_SCORE NUMBER(5,2),
    KYC_REVIEW_DUE_DATE DATE,
    SANCTIONS_SCREENING_STATUS VARIANT,
    SANCTIONS_HIT_INDICATOR BOOLEAN NOT NULL,
    PEP_FLAG BOOLEAN NOT NULL,
    CROSS_SELL_ELIGIBILITY_SCORE NUMBER(5,2),
    PORTFOLIO_SEGMENT_CODE VARCHAR(255),
    PORTFOLIO_ROI_ROLLING_12M NUMBER(6,2),
    CHURN_RISK_SCORE NUMBER(5,2),
    MARKETING_OPT_IN_EMAIL_FLAG BOOLEAN NOT NULL,
    PAYMENT_CHANNEL_CODE VARCHAR(255) NOT NULL,
    PROCESSING_STATUS_CODE VARCHAR(255) NOT NULL,
    REAL_TIME_STREAM_INGESTION_TIMESTAMP TIMESTAMP_NTZ NOT NULL,
    DATA_SOURCE_SYSTEM_CODE VARCHAR(255) NOT NULL,
    RECORD_EFFECTIVE_DATE DATE NOT NULL,
    RECORD_EXPIRY_DATE DATE,
    DATA_QUALITY_SCORE NUMBER(4,2),
    _LOADED_AT TIMESTAMP_NTZ,
    _SOURCE_SYSTEM VARCHAR(255)
    ,CONSTRAINT PK_EUROWIRE_COMPLIANCE_ PRIMARY KEY (ID)
);


-- Dataset: GDS54217
CREATE SCHEMA IF NOT EXISTS EUROCOMPLY;

-- This product dataset supports mobility solutions operations. Key applications include product perfor
CREATE TABLE IF NOT EXISTS EUROCOMPLY.EUROCOMPLY_FINANCE_FILTER (
    ID NUMBER(18,0) NOT NULL,
    DATASET_PRODUCT_ID VARCHAR(255) NOT NULL,
    MASREPH_CONTRACT_ID VARCHAR(255) NOT NULL,
    CUSTOMER_SEGMENT_CODE VARCHAR(255) NOT NULL,
    VEHICLE_USAGE_TYPE VARCHAR(255) NOT NULL,
    EU_MEMBER_STATE_CODE VARCHAR(255) NOT NULL,
    PAYMENT_SCHEDULE_ID VARCHAR(36) NOT NULL,
    PAYMENT_DUE_DATE DATE NOT NULL,
    PAYMENT_AMOUNT_EUR NUMBER(15,2) NOT NULL,
    PRINCIPAL_COMPONENT_EUR NUMBER(15,2) NOT NULL,
    INTEREST_COMPONENT_EUR NUMBER(15,2) NOT NULL,
    LATE_FEE_AMOUNT_EUR NUMBER(15,2),
    OUTSTANDING_PRINCIPAL_EUR NUMBER(17,2) NOT NULL,
    SCHEDULE_STATUS_CODE VARCHAR(255) NOT NULL,
    SCHEDULE_CREATION_TIMESTAMP TIMESTAMP_NTZ NOT NULL,
    SCHEDULE_LAST_UPDATED_TIMESTAMP TIMESTAMP_NTZ NOT NULL,
    ORIGINATION_DATE DATE NOT NULL,
    CONTRACT_MATURITY_DATE DATE NOT NULL,
    INTEREST_RATE_ANNUAL_PCT NUMBER(5,3) NOT NULL,
    REPAYMENT_FREQUENCY_CODE VARCHAR(255) NOT NULL,
    AUTO_DEBIT_MANDATE_FLAG BOOLEAN NOT NULL,
    SEPA_MANDATE_REFERENCE VARCHAR(255),
    MARKETING_CONSENT_FLAG BOOLEAN NOT NULL,
    GDPR_PROCESSING_LEGAL_BASIS VARCHAR(255) NOT NULL,
    PRODUCT_PERFORMANCE_SCORE NUMBER(5,2),
    PORTFOLIO_RISK_BAND VARCHAR(255) NOT NULL,
    DEFAULT_PROBABILITY_PCT NUMBER(6,3),
    MOBILITY_SOLUTION_TYPE VARCHAR(255) NOT NULL,
    CROSS_SELL_ELIGIBILITY_FLAG BOOLEAN NOT NULL,
    EU_TAXONOMY_ALIGNMENT_FLAG BOOLEAN,
    COUNTRY_GDP_WEIGHTING_FACTOR NUMBER(5,4),
    ANONYMIZED_CUSTOMER_ID VARCHAR(255) NOT NULL,
    DATA_LINEAGE_SOURCE_SYSTEM VARCHAR(255) NOT NULL,
    RECORD_COMPLIANCE_CHECK_STATUS VARCHAR(255) NOT NULL,
    _LOADED_AT TIMESTAMP_NTZ,
    _SOURCE_SYSTEM VARCHAR(255)
    ,CONSTRAINT PK_EUROCOMPLY_FINANCE_F PRIMARY KEY (ID)
);


-- Dataset: GDS54826
CREATE SCHEMA IF NOT EXISTS EUROCOMPLY;

-- This product dataset supports commercial finance operations. Key applications include product perfor
CREATE TABLE IF NOT EXISTS EUROCOMPLY.EUROWIRE_COMPLIANCE_DATASET (
    ID NUMBER(18,0) NOT NULL,
    TRANSACTION_ID VARCHAR(255) NOT NULL,
    MASREPH_PRODUCT_ID VARCHAR(255) NOT NULL,
    MASREPH_CUSTOMER_ID VARCHAR(255) NOT NULL,
    ORIGINATING_ACCOUNT_IBAN VARCHAR(34) NOT NULL,
    BENEFICIARY_ACCOUNT_IBAN VARCHAR(34) NOT NULL,
    ORIGINATING_BANK_BIC VARCHAR(255) NOT NULL,
    BENEFICIARY_BANK_BIC VARCHAR(255),
    TRANSACTION_TIMESTAMP TIMESTAMP_NTZ NOT NULL,
    TRANSACTION_VALUE_DATE DATE NOT NULL,
    TRANSACTION_CURRENCY_CODE VARCHAR(255) NOT NULL,
    TRANSACTION_AMOUNT NUMBER(18,2) NOT NULL,
    TRANSACTION_AMOUNT_EUR NUMBER(18,2) NOT NULL,
    EXCHANGE_RATE_APPLIED NUMBER(12,6),
    TRANSACTION_TYPE_CODE VARCHAR(255) NOT NULL,
    TRANSACTION_CHANNEL VARCHAR(11) NOT NULL,
    PAYMENT_REFERENCE VARCHAR(255),
    REMITTANCE_INFORMATION VARCHAR(255),
    REGULATORY_REPORTING_CODE VARCHAR(255),
    COMPLIANCE_SCREENING_STATUS VARCHAR(255) NOT NULL,
    COMPLIANCE_SCREENING_REASON VARCHAR(255),
    SANCTIONS_LIST_HIT_FLAG BOOLEAN NOT NULL,
    PEP_FLAG BOOLEAN NOT NULL,
    HIGH_RISK_COUNTRY_FLAG BOOLEAN NOT NULL,
    ORIGINATING_COUNTRY_CODE VARCHAR(255) NOT NULL,
    BENEFICIARY_COUNTRY_CODE VARCHAR(255) NOT NULL,
    ECONOMIC_SECTOR_CODE VARCHAR(255),
    PRODUCT_CATEGORY VARCHAR(255) NOT NULL,
    FEE_AMOUNT NUMBER(18,2) NOT NULL,
    FEE_CURRENCY_CODE VARCHAR(255) NOT NULL,
    REVENUE_RECOGNITION_BUCKET VARCHAR(255),
    RELATIONSHIP_MANAGER_ID VARCHAR(255),
    RISK_RATING_SCORE NUMBER(5,2),
    RISK_RATING_BAND VARCHAR(255),
    PORTFOLIO_SEGMENT_CODE VARCHAR(255) NOT NULL,
    PORTFOLIO_SEGMENT_DESCRIPTION VARCHAR(255),
    CROSS_SELL_INDICATOR BOOLEAN NOT NULL,
    TRANSACTION_STATUS VARCHAR(255) NOT NULL,
    REVERSAL_INDICATOR BOOLEAN NOT NULL,
    ORIGINAL_TRANSACTION_ID VARCHAR(255),
    BATCH_ID VARCHAR(255),
    BOOKING_BRANCH_ID VARCHAR(255) NOT NULL,
    BOOKING_LEDGER_CODE VARCHAR(255) NOT NULL,
    REPORTING_PERIOD_MONTH VARCHAR(255) NOT NULL,
    REPORTING_PERIOD_YEAR NUMBER(18,0) NOT NULL,
    DATA_SOURCE_SYSTEM VARCHAR(255) NOT NULL,
    INGESTION_TIMESTAMP TIMESTAMP_NTZ NOT NULL,
    LAST_UPDATED_TIMESTAMP TIMESTAMP_NTZ NOT NULL,
    GDPR_PERSONAL_DATA_FLAG BOOLEAN NOT NULL,
    RECORD_HASH_ID VARCHAR(255) NOT NULL,
    _LOADED_AT TIMESTAMP_NTZ,
    _SOURCE_SYSTEM VARCHAR(255)
    ,CONSTRAINT PK_EUROWIRE_COMPLIANCE_ PRIMARY KEY (ID)
);


