-- ============================================
-- Platform: SNOWFLAKE
-- Schema/Source: JUMIO_RISK_SIGNALS
-- Generated: 2026-03-18T12:18:16.817667
-- Datasets: 1
-- ============================================

-- Dataset: GDS36563
CREATE SCHEMA IF NOT EXISTS JUMIO_RISK_SIGNALS;

-- This risk management dataset supports mobility solutions operations. Key applications include data a
CREATE TABLE IF NOT EXISTS JUMIO_RISK_SIGNALS.CREDIT_RISK_INSIGHTS_DATASET (
    ID NUMBER(18,0) NOT NULL,
    CREDIT_RISK_RECORD_ID VARCHAR(36) NOT NULL,
    MASREPH_CUSTOMER_ID VARCHAR(255) NOT NULL,
    EXTERNAL_CUSTOMER_REFERENCE VARCHAR(255),
    VEHICLE_LOAN_ACCOUNT_ID VARCHAR(255),
    APPLICATION_ID VARCHAR(255) NOT NULL,
    CUSTOMER_SEGMENT_CODE VARCHAR(255) NOT NULL,
    CUSTOMER_RESIDENCE_COUNTRY VARCHAR(255) NOT NULL,
    CUSTOMER_BIRTH_DATE DATE,
    APPLICATION_SUBMISSION_TIMESTAMP TIMESTAMP_NTZ NOT NULL,
    CREDIT_DECISION_TIMESTAMP TIMESTAMP_NTZ,
    CREDIT_DECISION_STATUS VARCHAR(255) NOT NULL,
    CREDIT_DECISION_REASON_CODE VARCHAR(255),
    REQUESTED_LOAN_AMOUNT NUMBER(15,2) NOT NULL,
    APPROVED_LOAN_AMOUNT NUMBER(15,2),
    LOAN_CURRENCY_CODE VARCHAR(255) NOT NULL,
    LOAN_TERM_MONTHS NUMBER(18,0),
    INTEREST_RATE_ANNUAL NUMBER(5,3),
    DEBT_TO_INCOME_RATIO NUMBER(5,2),
    CREDIT_SCORE_PROVIDER_NAME VARCHAR(255),
    CREDIT_SCORE_VALUE NUMBER(18,0),
    CREDIT_SCORE_BAND VARCHAR(255),
    PROBABILITY_OF_DEFAULT_12M NUMBER(6,4),
    LOSS_GIVEN_DEFAULT_PERCENTAGE NUMBER(5,2),
    EXPOSURE_AT_DEFAULT NUMBER(17,2),
    COLLATERAL_VEHICLE_ESTIMATED_VALUE NUMBER(15,2),
    VEHICLE_USAGE_TYPE VARCHAR(255) NOT NULL,
    MOBILITY_SOLUTION_TYPE VARCHAR(255) NOT NULL,
    PAYMENT_FREQUENCY_CODE VARCHAR(255),
    FIRST_INSTALLMENT_DUE_DATE DATE,
    CURRENT_DAYS_PAST_DUE NUMBER(18,0),
    NON_PERFORMING_FLAG BOOLEAN NOT NULL,
    RESTRUCTURING_FLAG BOOLEAN NOT NULL,
    WRITE_OFF_FLAG BOOLEAN NOT NULL,
    LAST_PAYMENT_DATE DATE,
    LAST_PAYMENT_AMOUNT NUMBER(15,2),
    OUTSTANDING_PRINCIPAL_AMOUNT NUMBER(17,2),
    CUSTOMER_EMPLOYMENT_STATUS VARCHAR(255),
    CUSTOMER_MONTHLY_NET_INCOME NUMBER(15,2),
    CUSTOMER_TOTAL_MONTHLY_OBLIGATIONS NUMBER(15,2),
    GEOLOCATION_RISK_BUCKET VARCHAR(255),
    DATA_SOURCE_SYSTEM VARCHAR(255) NOT NULL,
    RECORD_EFFECTIVE_TIMESTAMP TIMESTAMP_NTZ NOT NULL,
    RECORD_LAST_UPDATED_TIMESTAMP TIMESTAMP_NTZ NOT NULL,
    GDPR_CONSENT_FLAG BOOLEAN NOT NULL,
    _LOADED_AT TIMESTAMP_NTZ,
    _SOURCE_SYSTEM VARCHAR(255)
    ,CONSTRAINT PK_CREDIT_RISK_INSIGHTS PRIMARY KEY (ID)
);


