-- ============================================
-- Platform: SNOWFLAKE
-- Schema/Source: RACCENT
-- Generated: 2026-03-18T12:18:16.808466
-- Datasets: 3
-- ============================================

-- Dataset: GDS11663
CREATE SCHEMA IF NOT EXISTS RACCENT;

-- This risk management dataset supports consumer finance operations. Key applications include data ana
CREATE TABLE IF NOT EXISTS RACCENT.FORBEARANCE_FINANCE_DATA_SET (
    ID NUMBER(18,0) NOT NULL,
    FORBEARANCE_RECORD_ID VARCHAR(36) NOT NULL,
    LOAN_ACCOUNT_ID VARCHAR(255) NOT NULL,
    CUSTOMER_INTERNAL_ID VARCHAR(255) NOT NULL,
    COUNTRY_CODE VARCHAR(255) NOT NULL,
    PRODUCT_TYPE VARCHAR(255) NOT NULL,
    FORBEARANCE_PROGRAM_CODE VARCHAR(255) NOT NULL,
    FORBEARANCE_PROGRAM_DESCRIPTION VARCHAR(255),
    FORBEARANCE_START_DATE DATE NOT NULL,
    FORBEARANCE_END_DATE DATE,
    FORBEARANCE_REQUEST_DATE DATE,
    ORIGINAL_MATURITY_DATE DATE NOT NULL,
    LOAN_ORIGINATION_DATE DATE NOT NULL,
    CURRENT_PAYMENT_DUE_DATE DATE,
    ORIGINAL_PRINCIPAL_AMOUNT NUMBER(15,2) NOT NULL,
    OUTSTANDING_PRINCIPAL_AMOUNT NUMBER(15,2) NOT NULL,
    INTEREST_RATE NUMBER(5,3) NOT NULL,
    INTEREST_RATE_TYPE VARCHAR(255) NOT NULL,
    CONTRACTUAL_MONTHLY_INSTALLMENT_AMOUNT NUMBER(15,2) NOT NULL,
    REDUCED_INSTALLMENT_AMOUNT NUMBER(15,2),
    FORBEARANCE_TYPE VARCHAR(255) NOT NULL,
    FORBEARANCE_STATUS VARCHAR(255) NOT NULL,
    DAYS_PAST_DUE_AT_FORBEARANCE_START NUMBER(18,0) NOT NULL,
    RISK_SEGMENT VARCHAR(255),
    CREDIT_SCORE_AT_FORBEARANCE_START NUMBER(18,0),
    EBA_FORBEARANCE_FLAG BOOLEAN NOT NULL,
    NON_PERFORMING_EXPOSURE_FLAG BOOLEAN NOT NULL,
    WRITE_OFF_FLAG BOOLEAN NOT NULL,
    IMPAIRMENT_STAGE_IFRS9 VARCHAR(255) NOT NULL,
    REASON_FOR_FORBEARANCE VARCHAR(255),
    INCOME_VERIFICATION_STATUS VARCHAR(255),
    CUSTOMER_EMPLOYMENT_STATUS VARCHAR(255),
    LAST_STATUS_UPDATE_TIMESTAMP TIMESTAMP_NTZ NOT NULL,
    DATA_SOURCE_SYSTEM VARCHAR(255) NOT NULL,
    REPORTING_ENTITY_LEI VARCHAR(255) NOT NULL,
    CURRENCY_CODE VARCHAR(255) NOT NULL,
    GDPR_CONSENT_FLAG BOOLEAN NOT NULL,
    RECORD_CREATION_TIMESTAMP TIMESTAMP_NTZ NOT NULL,
    _LOADED_AT TIMESTAMP_NTZ,
    _SOURCE_SYSTEM VARCHAR(255)
    ,CONSTRAINT PK_FORBEARANCE_FINANCE_ PRIMARY KEY (ID)
);


-- Dataset: GDS64698
CREATE SCHEMA IF NOT EXISTS RACCENT;

-- This client dataset supports consumer finance operations. Key applications include relationship mana
CREATE TABLE IF NOT EXISTS RACCENT.FINANCE_CONTACT_INFORMATION_DATASET (
    ID NUMBER(18,0) NOT NULL,
    CLIENT_CONTACT_ID VARCHAR(36) NOT NULL,
    PARTY_UNIQUE_REFERENCE VARCHAR(255) NOT NULL,
    PERSONAL_LOAN_ACCOUNT_ID VARCHAR(255),
    CONTACT_ROLE_TYPE VARCHAR(255) NOT NULL,
    CONTACT_ENTITY_TYPE VARCHAR(255) NOT NULL,
    PRIMARY_EMAIL_ADDRESS VARCHAR(320) NOT NULL,
    SECONDARY_EMAIL_ADDRESS VARCHAR(320),
    ADDITIONAL_EMAIL_ADDRESSES VARCHAR(320),
    EMAIL_CONSENT_FLAG BOOLEAN NOT NULL,
    MOBILE_PHONE_NUMBER VARCHAR(255) NOT NULL,
    HOME_PHONE_NUMBER VARCHAR(255),
    WORK_PHONE_NUMBER VARCHAR(255),
    SMS_MARKETING_CONSENT_FLAG BOOLEAN NOT NULL,
    PHONE_CONTACT_PREFERENCE VARCHAR(255) NOT NULL,
    MAILING_ADDRESS_LINE_1 VARCHAR(255) NOT NULL,
    MAILING_ADDRESS_LINE_2 VARCHAR(255),
    MAILING_ADDRESS_CITY VARCHAR(255) NOT NULL,
    MAILING_ADDRESS_POSTAL_CODE VARCHAR(255) NOT NULL,
    MAILING_ADDRESS_COUNTRY_CODE VARCHAR(255) NOT NULL,
    MAILING_ADDRESS_GEOLOCATION VARIANT,
    MAILING_ADDRESS_VALIDATED_FLAG BOOLEAN NOT NULL,
    PREFERRED_CONTACT_CHANNEL VARCHAR(320) NOT NULL,
    PREFERRED_CONTACT_TIME_WINDOW VARCHAR(255),
    CONTACT_LANGUAGE_CODE VARCHAR(255) NOT NULL,
    CLIENT_TIME_ZONE VARCHAR(255),
    DO_NOT_CONTACT_FLAG BOOLEAN NOT NULL,
    LAST_OUTBOUND_CONTACT_TIMESTAMP TIMESTAMP_NTZ,
    LAST_INBOUND_CONTACT_TIMESTAMP TIMESTAMP_NTZ,
    NEXT_SCHEDULED_CONTACT_DATE DATE,
    CONTACT_SOURCE_SYSTEM_CODE VARCHAR(255) NOT NULL,
    CRM_LEAD_IDENTIFIER VARCHAR(255),
    RELATIONSHIP_MANAGER_EMPLOYEE_ID VARCHAR(255),
    CLIENT_PROFITABILITY_SEGMENT_CODE VARCHAR(255),
    ANNUAL_GROSS_INCOME_AMOUNT NUMBER(15,2),
    CONTACT_VALUE_SCORE NUMBER(5,2),
    DATA_PRIVACY_CONSENT_VERSION VARCHAR(255),
    GDPR_CONSENT_CAPTURED_TIMESTAMP TIMESTAMP_NTZ,
    CONTACT_RECORD_ACTIVE_FLAG BOOLEAN NOT NULL,
    _LOADED_AT TIMESTAMP_NTZ,
    _SOURCE_SYSTEM VARCHAR(255)
    ,CONSTRAINT PK_FINANCE_CONTACT_INFO PRIMARY KEY (ID)
);


-- Dataset: GDS85323
CREATE SCHEMA IF NOT EXISTS RACCENT;

-- This partner dataset supports consumer finance operations. Key applications include data analysis, r
CREATE TABLE IF NOT EXISTS RACCENT.PARTNER_FINANCE_DISTRIBUTION_DATA (
    ID NUMBER(18,0) NOT NULL,
    RECORD_ID VARCHAR(36) NOT NULL,
    PARTNER_ID VARCHAR(255) NOT NULL,
    PARTNER_LEGAL_NAME VARCHAR(255) NOT NULL,
    PARTNER_COUNTRY_CODE VARCHAR(255) NOT NULL,
    DISTRIBUTION_CHANNEL_CODE VARCHAR(255) NOT NULL,
    DISTRIBUTION_CHANNEL_DESCRIPTION VARCHAR(255),
    PARTNER_BRANCH_ID VARCHAR(255),
    PARTNER_SEGMENT_CODE VARCHAR(255),
    PRODUCT_CODE VARCHAR(255) NOT NULL,
    PRODUCT_NAME VARCHAR(255) NOT NULL,
    LOAN_APPLICATION_ID VARCHAR(255) NOT NULL,
    LOAN_CONTRACT_ID VARCHAR(255),
    CUSTOMER_INTERNAL_ID VARCHAR(255) NOT NULL,
    CUSTOMER_RESIDENCE_COUNTRY VARCHAR(255),
    LOAN_PURPOSE_CODE VARCHAR(255),
    LOAN_PURPOSE_DESCRIPTION VARCHAR(255),
    APPLICATION_SUBMISSION_TIMESTAMP TIMESTAMP_NTZ NOT NULL,
    APPLICATION_DECISION_TIMESTAMP TIMESTAMP_NTZ,
    APPLICATION_STATUS_CODE VARCHAR(255) NOT NULL,
    DECISION_OUTCOME_CODE VARCHAR(255),
    DECLINE_REASON_CODE VARCHAR(255),
    REQUESTED_LOAN_AMOUNT NUMBER(15,2) NOT NULL,
    APPROVED_LOAN_AMOUNT NUMBER(15,2),
    LOAN_CURRENCY_CODE VARCHAR(255) NOT NULL,
    NOMINAL_INTEREST_RATE NUMBER(5,3),
    APR_EFFECTIVE_RATE NUMBER(6,3),
    LOAN_TERM_MONTHS NUMBER(18,0) NOT NULL,
    INSTALLMENT_AMOUNT NUMBER(15,2),
    FIRST_DISBURSEMENT_DATE DATE,
    CONTRACT_MATURITY_DATE DATE,
    LOAN_STATUS_CODE VARCHAR(255),
    CURRENT_DAYS_PAST_DUE NUMBER(18,0),
    OUTSTANDING_PRINCIPAL_BALANCE NUMBER(15,2),
    PARTNER_COMMISSION_RATE NUMBER(5,3),
    PARTNER_COMMISSION_AMOUNT NUMBER(15,2),
    UPFRONT_FEE_AMOUNT NUMBER(15,2),
    LATE_FEE_POLICY_CODE VARCHAR(255),
    CUSTOMER_INCOME_BRACKET_CODE VARCHAR(255),
    CREDIT_RISK_GRADE VARCHAR(255),
    PREAPPROVAL_FLAG BOOLEAN NOT NULL,
    CO_BORROWER_PRESENT_FLAG BOOLEAN,
    CROSS_SELL_ORIGIN_FLAG BOOLEAN,
    PARTNER_REPORTING_DATE DATE NOT NULL,
    DATA_CAPTURE_TIMESTAMP TIMESTAMP_NTZ NOT NULL,
    SOURCE_SYSTEM_CODE VARCHAR(255) NOT NULL,
    PARTNER_CONTRACT_ID VARCHAR(255),
    REGULATORY_REPORTING_REGION VARCHAR(255),
    MARKETING_CAMPAIGN_ID VARCHAR(255),
    DISTRIBUTION_REFERENCE_ID VARCHAR(255),
    PARTNER_HIERARCHY VARIANT,
    ASSOCIATED_PRODUCT_CODES VARIANT,
    _LOADED_AT TIMESTAMP_NTZ,
    _SOURCE_SYSTEM VARCHAR(255)
    ,CONSTRAINT PK_PARTNER_FINANCE_DIST PRIMARY KEY (ID)
);


