-- ============================================
-- Platform: SNOWFLAKE
-- Schema/Source: RISKCONNECT
-- Generated: 2026-03-18T12:18:16.817667
-- Datasets: 2
-- ============================================

-- Dataset: GDS39436
CREATE SCHEMA IF NOT EXISTS RISKCONNECT;

-- This risk management dataset supports commercial finance operations. Key applications include data a
CREATE TABLE IF NOT EXISTS RISKCONNECT.RISKCONNECT_FINANCE_DATASET (
    ID NUMBER(18,0) NOT NULL,
    RISKCONNECT_RECORD_ID VARCHAR(36) NOT NULL,
    MASREPH_CUSTOMER_ID VARCHAR(255) NOT NULL,
    LEGAL_ENTITY_NAME VARCHAR(255) NOT NULL,
    CUSTOMER_SEGMENT VARCHAR(255) NOT NULL,
    COUNTERPARTY_COUNTRY_CODE VARCHAR(255) NOT NULL,
    LEI_CODE VARCHAR(255),
    FACILITY_ID VARCHAR(255) NOT NULL,
    FACILITY_TYPE VARCHAR(255) NOT NULL,
    CURRENCY_CODE VARCHAR(255) NOT NULL,
    FACILITY_LIMIT_AMOUNT NUMBER(18,2) NOT NULL,
    OUTSTANDING_EXPOSURE_AMOUNT NUMBER(18,2) NOT NULL,
    EXPOSURE_AMOUNT_EUR NUMBER(20,4) NOT NULL,
    INTEREST_RATE_TYPE VARCHAR(255) NOT NULL,
    REFERENCE_RATE_INDEX VARCHAR(255),
    CONTRACT_INTEREST_RATE NUMBER(7,4) NOT NULL,
    ORIGINATION_DATE DATE NOT NULL,
    MATURITY_DATE DATE,
    DAYS_PAST_DUE NUMBER(18,0) NOT NULL,
    DEFAULT_STATUS_FLAG BOOLEAN NOT NULL,
    DEFAULT_DATE DATE,
    INTERNAL_RATING_GRADE VARCHAR(255) NOT NULL,
    INTERNAL_RATING_MODEL_ID VARCHAR(255),
    PROBABILITY_OF_DEFAULT_12M NUMBER(7,5) NOT NULL,
    LOSS_GIVEN_DEFAULT NUMBER(6,4) NOT NULL,
    EXPOSURE_AT_DEFAULT_EUR NUMBER(20,2) NOT NULL,
    IFRS9_STAGE VARCHAR(255) NOT NULL,
    EXPECTED_CREDIT_LOSS_EUR NUMBER(20,2) NOT NULL,
    COLLATERAL_COVERAGE_RATIO NUMBER(7,4),
    PRIMARY_COLLATERAL_TYPE VARCHAR(255),
    SECTOR_NACE_CODE VARCHAR(255) NOT NULL,
    SME_FLAG BOOLEAN NOT NULL,
    COUNTERPARTY_GROUP_ID VARCHAR(255),
    SANCTIONS_SCREENING_STATUS VARCHAR(255) NOT NULL,
    LAST_RISK_REVIEW_DATE DATE,
    NEXT_RISK_REVIEW_DUE_DATE DATE,
    WATCHLIST_FLAG BOOLEAN NOT NULL,
    COVENANT_BREACH_FLAG BOOLEAN NOT NULL,
    COVENANT_BREACH_DATE DATE,
    REAL_TIME_FEED_TIMESTAMP TIMESTAMP_NTZ NOT NULL,
    GDPR_PERSONAL_DATA_FLAG BOOLEAN NOT NULL,
    RISK_DATA_QUALITY_SCORE NUMBER(4,2),
    RISK_FLAGS VARIANT,
    _LOADED_AT TIMESTAMP_NTZ,
    _SOURCE_SYSTEM VARCHAR(255)
    ,CONSTRAINT PK_RISKCONNECT_FINANCE_ PRIMARY KEY (ID)
);


-- Dataset: GDS78871
CREATE SCHEMA IF NOT EXISTS RISKCONNECT;

-- This risk management dataset supports leasing operations. Key applications include data analysis, re
CREATE TABLE IF NOT EXISTS RISKCONNECT.RISKCONNECT_FINANCE_DATASET (
    ID NUMBER(18,0) NOT NULL,
    DATASET_RECORD_ID VARCHAR(36) NOT NULL,
    LEASE_CONTRACT_ID VARCHAR(255) NOT NULL,
    LESSEE_CUSTOMER_ID VARCHAR(255) NOT NULL,
    ASSET_ID VARCHAR(255) NOT NULL,
    ASSET_TYPE VARCHAR(255) NOT NULL,
    ASSET_DESCRIPTION VARCHAR(255),
    COUNTRY_CODE VARCHAR(255) NOT NULL,
    BOOKING_ENTITY_CODE VARCHAR(255) NOT NULL,
    CONTRACT_START_DATE DATE NOT NULL,
    CONTRACT_END_DATE DATE,
    FIRST_RENTAL_DUE_DATE DATE,
    CONTRACT_STATUS VARCHAR(255) NOT NULL,
    CONTRACT_TERM_MONTHS NUMBER(18,0) NOT NULL,
    PAYMENT_FREQUENCY_CODE VARCHAR(255) NOT NULL,
    CURRENCY_CODE VARCHAR(255) NOT NULL,
    ORIGINAL_PRINCIPAL_AMOUNT NUMBER(18,2) NOT NULL,
    OUTSTANDING_PRINCIPAL_AMOUNT NUMBER(18,2) NOT NULL,
    EFFECTIVE_INTEREST_RATE NUMBER(5,3),
    INTEREST_RATE_TYPE VARCHAR(255) NOT NULL,
    RISK_RATING_INTERNAL VARCHAR(255),
    RISK_RATING_EXTERNAL VARCHAR(255),
    DAYS_PAST_DUE NUMBER(18,0) NOT NULL,
    NON_PERFORMING_EXPOSURE_FLAG BOOLEAN NOT NULL,
    DEFAULT_STATUS VARCHAR(255) NOT NULL,
    DEFAULT_DATE DATE,
    FORBEARANCE_FLAG BOOLEAN NOT NULL,
    COLLATERAL_VALUE_CURRENT NUMBER(18,2),
    COLLATERAL_VALUATION_DATE DATE,
    LGD_ESTIMATE_PERCENT NUMBER(5,2) NOT NULL,
    PD_12M_ESTIMATE_PERCENT NUMBER(6,4) NOT NULL,
    EAD_CURRENT_AMOUNT NUMBER(18,2) NOT NULL,
    IMPAIRMENT_STAGE_IFRS9 VARCHAR(255) NOT NULL,
    IMPAIRMENT_PROVISION_AMOUNT NUMBER(18,2) NOT NULL,
    WRITE_OFF_AMOUNT NUMBER(18,2) NOT NULL,
    RESTRUCTURING_FLAG BOOLEAN NOT NULL,
    COLLECTION_STRATEGY_CODE VARCHAR(255),
    INDUSTRY_SECTOR_CODE VARCHAR(255),
    ORIGINATION_CHANNEL VARCHAR(255),
    CREDIT_DECISION_TIMESTAMP TIMESTAMP_NTZ NOT NULL,
    CREDIT_DECISION_OUTCOME VARCHAR(255) NOT NULL,
    GDPR_CONSENT_FLAG BOOLEAN NOT NULL,
    LAST_PAYMENT_DATE DATE,
    LAST_PAYMENT_AMOUNT NUMBER(18,2),
    NEXT_PAYMENT_DUE_DATE DATE,
    DATA_SOURCE_SYSTEM VARCHAR(255) NOT NULL,
    RECORD_LAST_UPDATED_TIMESTAMP TIMESTAMP_NTZ NOT NULL,
    STREAMING_EVENT_ID VARCHAR(36) NOT NULL,
    _LOADED_AT TIMESTAMP_NTZ,
    _SOURCE_SYSTEM VARCHAR(255)
    ,CONSTRAINT PK_RISKCONNECT_FINANCE_ PRIMARY KEY (ID)
);


