-- ============================================
-- Platform: SNOWFLAKE
-- Schema/Source: SANCTION_SCANNER
-- Generated: 2026-03-18T12:18:16.816653
-- Datasets: 7
-- ============================================

-- Dataset: GDS34651
CREATE SCHEMA IF NOT EXISTS SANCTION_SCANNER;

-- This partner dataset supports mobility solutions operations. Key applications include data analysis,
CREATE TABLE IF NOT EXISTS SANCTION_SCANNER.RISKFLOW_FINANCE_DATASET (
    ID NUMBER(18,0) NOT NULL,
    DATASET_ID VARCHAR(36) NOT NULL,
    PARTNER_SOURCE_SYSTEM VARCHAR(255) NOT NULL,
    CUSTOMER_ID VARCHAR(255) NOT NULL,
    VEHICLE_ID VARCHAR(255),
    CONTRACT_ID VARCHAR(255) NOT NULL,
    LOAN_ACCOUNT_NUMBER VARCHAR(255) NOT NULL,
    APPLICATION_ID VARCHAR(255),
    RISK_ASSESSMENT_ID VARCHAR(255),
    COUNTRY_CODE VARCHAR(255) NOT NULL,
    CURRENCY_CODE VARCHAR(255) NOT NULL,
    CUSTOMER_SEGMENT VARCHAR(255),
    PRODUCT_TYPE VARCHAR(255) NOT NULL,
    INTEREST_RATE_ANNUAL NUMBER(5,3) NOT NULL,
    PRINCIPAL_AMOUNT NUMBER(15,2) NOT NULL,
    OUTSTANDING_BALANCE NUMBER(15,2) NOT NULL,
    LOAN_TERM_MONTHS NUMBER(18,0) NOT NULL,
    ORIGINATION_DATE DATE NOT NULL,
    MATURITY_DATE DATE,
    FIRST_PAYMENT_DATE DATE,
    LAST_PAYMENT_DATE DATE,
    DAYS_PAST_DUE NUMBER(18,0) NOT NULL,
    DEFAULT_FLAG BOOLEAN NOT NULL,
    WRITE_OFF_AMOUNT NUMBER(15,2),
    COLLATERAL_TYPE VARCHAR(255),
    COLLATERAL_VALUE NUMBER(15,2),
    LTV_RATIO NUMBER(6,3),
    DTI_RATIO NUMBER(5,2),
    RISK_SCORE_INTERNAL NUMBER(18,0),
    PROBABILITY_OF_DEFAULT_12M NUMBER(6,4),
    LOSS_GIVEN_DEFAULT_PCT NUMBER(5,2),
    EXPOSURE_AT_DEFAULT NUMBER(17,2),
    BOOKING_BRANCH_CODE VARCHAR(255),
    GDP_COMPLIANCE_FLAG BOOLEAN NOT NULL,
    DATA_SOURCE_TIMESTAMP TIMESTAMP_NTZ NOT NULL,
    RECORD_CREATED_TIMESTAMP TIMESTAMP_NTZ NOT NULL,
    RECORD_LAST_UPDATED_TIMESTAMP TIMESTAMP_NTZ NOT NULL,
    PAYMENT_FREQUENCY VARCHAR(255) NOT NULL,
    PAYMENT_AMOUNT_SCHEDULED NUMBER(12,2) NOT NULL,
    PAYMENT_AMOUNT_LAST NUMBER(12,2),
    DELINQUENCY_STATUS VARCHAR(255) NOT NULL,
    RESTRUCTURING_FLAG BOOLEAN NOT NULL,
    MOBILITY_USE_CASE VARCHAR(255),
    STREAMING_EVENT_ID VARCHAR(255),
    DATA_QUALITY_SCORE NUMBER(4,2) NOT NULL,
    CONSENT_MARKETING_FLAG BOOLEAN,
    AML_KYC_RISK_RATING VARCHAR(255),
    _LOADED_AT TIMESTAMP_NTZ,
    _SOURCE_SYSTEM VARCHAR(255)
    ,CONSTRAINT PK_RISKFLOW_FINANCE_DAT PRIMARY KEY (ID)
);


-- Dataset: GDS48675
CREATE SCHEMA IF NOT EXISTS SANCTION_SCANNER;

-- This client dataset supports commercial finance operations. Key applications include relationship ma
CREATE TABLE IF NOT EXISTS SANCTION_SCANNER.FINANCE_RISK_INSIGHTS (
    ID NUMBER(18,0) NOT NULL,
    CLIENT_ID VARCHAR(36) NOT NULL,
    GROUP_CLIENT_REFERENCE VARCHAR(255),
    PARTY_LEI VARCHAR(255),
    CLIENT_LEGAL_NAME VARCHAR(255) NOT NULL,
    CLIENT_TRADING_NAME VARCHAR(255),
    CLIENT_TYPE VARCHAR(255) NOT NULL,
    INDUSTRY_CODE_NACE VARCHAR(255) NOT NULL,
    COUNTRY_OF_DOMICILE VARCHAR(255) NOT NULL,
    PRIMARY_OPERATING_COUNTRY VARCHAR(255),
    RELATIONSHIP_MANAGER_ID VARCHAR(255) NOT NULL,
    RELATIONSHIP_START_DATE DATE NOT NULL,
    RELATIONSHIP_STATUS VARCHAR(255) NOT NULL,
    CLIENT_SEGMENT VARCHAR(255) NOT NULL,
    STRATEGIC_IMPORTANCE_FLAG BOOLEAN NOT NULL,
    ANNUAL_REVENUE_EUR NUMBER(18,2),
    EBITDA_MARGIN_PCT NUMBER(5,2),
    TOTAL_ASSETS_EUR NUMBER(18,2),
    RISK_RATING_INTERNAL VARCHAR(255) NOT NULL,
    RISK_RATING_EXTERNAL VARCHAR(255),
    PROBABILITY_OF_DEFAULT_12M NUMBER(6,4) NOT NULL,
    LOSS_GIVEN_DEFAULT_PCT NUMBER(5,2) NOT NULL,
    EXPOSURE_AT_DEFAULT_EUR NUMBER(20,2) NOT NULL,
    TOTAL_CREDIT_LIMIT_EUR NUMBER(20,2) NOT NULL,
    UTILIZED_CREDIT_AMOUNT_EUR NUMBER(20,2) NOT NULL,
    PAST_DUE_AMOUNT_EUR NUMBER(18,2) NOT NULL,
    NONPERFORMING_FLAG BOOLEAN NOT NULL,
    WATCHLIST_FLAG BOOLEAN NOT NULL,
    WATCHLIST_REASON VARCHAR(255),
    SANCTIONS_SCREENING_STATUS VARCHAR(255) NOT NULL,
    KYC_REVIEW_STATUS VARCHAR(255) NOT NULL,
    KYC_NEXT_REVIEW_DATE DATE,
    GDPR_DATA_PROCESSING_BASIS VARCHAR(255),
    CONSENT_MARKETING_FLAG BOOLEAN NOT NULL,
    PRIMARY_CONTACT_EMAIL_HASH VARCHAR(255),
    ONBOARDING_CHANNEL VARCHAR(255),
    LAST_CONTACT_TIMESTAMP TIMESTAMP_NTZ,
    LAST_CONTACT_CHANNEL VARCHAR(320),
    PREFERRED_CONTACT_LANGUAGE VARCHAR(255),
    CLIENT_PROFITABILITY_SCORE NUMBER(18,0) NOT NULL,
    NET_INTEREST_INCOME_YTD_EUR NUMBER(18,2) NOT NULL,
    FEE_INCOME_YTD_EUR NUMBER(18,2) NOT NULL,
    COST_TO_SERVE_YTD_EUR NUMBER(18,2) NOT NULL,
    CROSS_SELL_OPPORTUNITY_SCORE NUMBER(18,0) NOT NULL,
    CHURN_RISK_SCORE NUMBER(18,0) NOT NULL,
    RELATIONSHIP_TENURE_MONTHS NUMBER(18,0) NOT NULL,
    PRIMARY_BANK_FLAG BOOLEAN NOT NULL,
    NUMBER_OF_ACTIVE_PRODUCTS NUMBER(18,0) NOT NULL,
    AVERAGE_ACCOUNT_BALANCE_3M_EUR NUMBER(18,2) NOT NULL,
    COLLATERAL_COVERAGE_RATIO_PCT NUMBER(6,2),
    COVENANT_BREACH_FLAG BOOLEAN NOT NULL,
    CREDIT_REVIEW_FREQUENCY_MONTHS NUMBER(18,0) NOT NULL,
    NEXT_CREDIT_REVIEW_DATE DATE,
    _LOADED_AT TIMESTAMP_NTZ,
    _SOURCE_SYSTEM VARCHAR(255)
    ,CONSTRAINT PK_FINANCE_RISK_INSIGHT PRIMARY KEY (ID)
);


-- Dataset: GDS58553
CREATE SCHEMA IF NOT EXISTS SANCTION_SCANNER;

-- This client dataset supports mobility solutions operations. Key applications include relationship ma
CREATE TABLE IF NOT EXISTS SANCTION_SCANNER.FINANCE_RISK_INSIGHTS (
    ID NUMBER(18,0) NOT NULL,
    CLIENT_ID VARCHAR(36) NOT NULL,
    CLIENT_GLOBAL_ID VARCHAR(255) NOT NULL,
    LEASE_CONTRACT_ID VARCHAR(255) NOT NULL,
    RELATIONSHIP_MANAGER_ID VARCHAR(255),
    CLIENT_SEGMENT_CODE VARCHAR(255) NOT NULL,
    CLIENT_RESIDENCY_COUNTRY_CODE VARCHAR(255) NOT NULL,
    CLIENT_PRIMARY_LANGUAGE_CODE VARCHAR(255),
    CLIENT_ONBOARDING_DATE DATE NOT NULL,
    CLIENT_BIRTH_DATE DATE,
    CLIENT_AGE_YEARS NUMBER(18,0),
    CLIENT_RISK_RATING VARCHAR(255) NOT NULL,
    RISK_RATING_LAST_REVIEW_DATE DATE,
    RISK_SCORE_PD NUMBER(5,2) NOT NULL,
    RISK_SCORE_LGD NUMBER(5,2),
    RISK_APPETITE_BUCKET VARCHAR(255),
    AML_KYC_STATUS VARCHAR(255) NOT NULL,
    AML_KYC_LAST_REVIEW_TIMESTAMP TIMESTAMP_NTZ,
    GDPR_CONSENT_MARKETING_FLAG BOOLEAN NOT NULL,
    GDPR_CONSENT_LAST_UPDATED_TIMESTAMP TIMESTAMP_NTZ,
    CLIENT_PROFITABILITY_ROLLING_12M NUMBER(15,2),
    CLIENT_REVENUE_ROLLING_12M NUMBER(15,2),
    CLIENT_COST_ROLLING_12M NUMBER(15,2),
    LEASE_PORTFOLIO_OUTSTANDING_BALANCE NUMBER(18,2) NOT NULL,
    LEASE_AVG_TERM_MONTHS NUMBER(18,0),
    LEASE_AVG_INTEREST_RATE NUMBER(6,4),
    LEASE_PAYMENT_BEHAVIOR_SCORE NUMBER(18,0),
    LEASE_PAYMENT_ARREARS_DAYS_AVG NUMBER(6,2),
    NPS_LATEST_SCORE NUMBER(18,0),
    LAST_CONTACT_CHANNEL VARCHAR(320),
    LAST_CONTACT_TIMESTAMP TIMESTAMP_NTZ,
    PREFERRED_CONTACT_CHANNEL VARCHAR(320),
    MOBILITY_SOLUTION_TYPE VARCHAR(255) NOT NULL,
    VEHICLE_VIN_HASHED VARCHAR(255),
    VEHICLE_FUEL_TYPE VARCHAR(255),
    VEHICLE_USAGE_PATTERN_CODE VARCHAR(255),
    GEO_PRIMARY_OPERATING_REGION VARCHAR(255),
    EARLY_TERMINATION_RISK_SCORE NUMBER(5,2),
    CHURN_PROPENSITY_SCORE NUMBER(5,4),
    CROSS_SELL_UPTAKE_INDEX NUMBER(18,0),
    RELATIONSHIP_TENURE_MONTHS NUMBER(18,0),
    CREDIT_LIMIT_ACTIVE_AMOUNT NUMBER(18,2),
    CREDIT_UTILIZATION_RATIO NUMBER(6,4),
    DELINQUENCY_FLAG BOOLEAN NOT NULL,
    WRITE_OFF_AMOUNT_LIFETIME NUMBER(18,2),
    RISK_ALERT_ACTIVE_FLAG BOOLEAN NOT NULL,
    RISK_ALERT_REASON_CODES VARIANT,
    DATA_SOURCE_SYSTEM_CODE VARCHAR(255) NOT NULL,
    RECORD_LAST_UPDATED_TIMESTAMP TIMESTAMP_NTZ NOT NULL,
    _LOADED_AT TIMESTAMP_NTZ,
    _SOURCE_SYSTEM VARCHAR(255)
    ,CONSTRAINT PK_FINANCE_RISK_INSIGHT PRIMARY KEY (ID)
);


-- Dataset: GDS65231
CREATE SCHEMA IF NOT EXISTS SANCTION_SCANNER;

-- This client dataset supports consumer finance operations. Key applications include relationship mana
CREATE TABLE IF NOT EXISTS SANCTION_SCANNER.FINANCE_RISK_INSIGHTS (
    ID NUMBER(18,0) NOT NULL,
    CLIENT_ID VARCHAR(36) NOT NULL,
    MASREPH_PARTY_ID VARCHAR(255) NOT NULL,
    CUSTOMER_SEGMENT_CODE VARCHAR(255) NOT NULL,
    CUSTOMER_RISK_RATING VARCHAR(255) NOT NULL,
    RISK_RATING_LAST_UPDATED_TS TIMESTAMP_NTZ NOT NULL,
    COUNTRY_OF_RESIDENCE_CODE VARCHAR(255) NOT NULL,
    EU_GDPR_CONSENT_FLAG BOOLEAN NOT NULL,
    PRIMARY_RELATIONSHIP_MANAGER_ID VARCHAR(255),
    CLIENT_ONBOARDING_DATE DATE NOT NULL,
    TOTAL_OUTSTANDING_LOAN_BALANCE NUMBER(15,2) NOT NULL,
    UNSECURED_EXPOSURE_AMOUNT NUMBER(15,2) NOT NULL,
    SECURED_EXPOSURE_AMOUNT NUMBER(15,2) NOT NULL,
    DAYS_PAST_DUE_MAX_LAST_12M NUMBER(18,0) NOT NULL,
    PROBABILITY_OF_DEFAULT_12M NUMBER(5,4) NOT NULL,
    BEHAVIORAL_SCORE NUMBER(18,0) NOT NULL,
    AVG_MONTHLY_ACCOUNT_BALANCE_6M NUMBER(15,2),
    NET_INTEREST_INCOME_YTD NUMBER(15,2),
    FEE_INCOME_YTD NUMBER(15,2),
    RELATIONSHIP_PROFITABILITY_SCORE NUMBER(7,2),
    PREFERRED_CONTACT_CHANNEL VARCHAR(320),
    LAST_OUTBOUND_CONTACT_TS TIMESTAMP_NTZ,
    CHURN_RISK_FLAG BOOLEAN NOT NULL,
    AML_WATCHLIST_SCREENING_STATUS VARCHAR(255) NOT NULL,
    KYC_REVIEW_DUE_DATE DATE,
    DATA_SUBJECT_PSEUDONYM_ID VARCHAR(255) NOT NULL,
    STREAMING_EVENT_INGESTION_TS TIMESTAMP_NTZ NOT NULL,
    _LOADED_AT TIMESTAMP_NTZ,
    _SOURCE_SYSTEM VARCHAR(255)
    ,CONSTRAINT PK_FINANCE_RISK_INSIGHT PRIMARY KEY (ID)
);


-- Dataset: GDS71835
CREATE SCHEMA IF NOT EXISTS SANCTION_SCANNER;

-- This client dataset supports mobility solutions operations. Key applications include relationship ma
CREATE TABLE IF NOT EXISTS SANCTION_SCANNER.FINANCE_RISK_INSIGHTS (
    ID NUMBER(18,0) NOT NULL,
    CLIENT_RISK_INSIGHTS_ID VARCHAR(36) NOT NULL,
    MASREPH_CLIENT_ID VARCHAR(255) NOT NULL,
    EXTERNAL_CRM_CLIENT_ID VARCHAR(255),
    CLIENT_SEGMENT_CODE VARCHAR(255) NOT NULL,
    CLIENT_SEGMENT_DESCRIPTION VARCHAR(255),
    PRIMARY_MOBILITY_PRODUCT_TYPE VARCHAR(255) NOT NULL,
    ACTIVE_AUTO_LOAN_INDICATOR BOOLEAN NOT NULL,
    TOTAL_AUTO_LOAN_BALANCE_EUR NUMBER(15,2) NOT NULL,
    TOTAL_MOBILITY_EXPOSURE_EUR NUMBER(15,2) NOT NULL,
    CLIENT_PROFITABILITY_SCORE NUMBER(5,2) NOT NULL,
    RELATIONSHIP_START_DATE DATE NOT NULL,
    LAST_INTERACTION_TIMESTAMP TIMESTAMP_NTZ,
    PREFERRED_CONTACT_CHANNEL VARCHAR(320),
    GDPR_CONSENT_MARKETING_INDICATOR BOOLEAN NOT NULL,
    GDPR_CONSENT_DATA_SHARE_INDICATOR BOOLEAN NOT NULL,
    CLIENT_COUNTRY_ISO2_CODE VARCHAR(255) NOT NULL,
    CLIENT_RESIDENCE_REGION VARCHAR(255),
    CLIENT_AGE_YEARS NUMBER(18,0),
    CLIENT_EMPLOYMENT_STATUS VARCHAR(255),
    VEHICLE_USAGE_PROFILE VARIANT,
    AVERAGE_MONTHLY_MILEAGE_KM NUMBER(7,2),
    PAYMENT_BEHAVIOR_SCORE NUMBER(5,2) NOT NULL,
    DAYS_PAST_DUE_LAST_12M NUMBER(18,0) NOT NULL,
    MAX_DELINQUENCY_STATUS_LAST_24M VARCHAR(255) NOT NULL,
    EARLY_REPAYMENT_TENDENCY_SCORE NUMBER(5,2),
    CROSS_SELL_UPTAKE_INDICATOR BOOLEAN NOT NULL,
    CHURN_RISK_SCORE NUMBER(5,2) NOT NULL,
    MOBILITY_WALLET_SHARE_PERCENTAGE NUMBER(5,2),
    LAST_SERVICE_BOOKING_DATE DATE,
    MOBILITY_CONTRACT_STATUS VARCHAR(255) NOT NULL,
    RISK_REVIEW_NEXT_DUE_DATE DATE,
    HIGH_RISK_FLAG BOOLEAN NOT NULL,
    RISK_CLASSIFICATION_CODE VARCHAR(255) NOT NULL,
    RELATIONSHIP_MANAGER_ID VARCHAR(255),
    ACTIVE_MOBILITY_CHANNELS VARIANT,
    STREAMING_EVENT_SOURCE_SYSTEM VARCHAR(255) NOT NULL,
    DATA_RECORD_LAST_UPDATED_TIMESTAMP TIMESTAMP_NTZ NOT NULL,
    _LOADED_AT TIMESTAMP_NTZ,
    _SOURCE_SYSTEM VARCHAR(255)
    ,CONSTRAINT PK_FINANCE_RISK_INSIGHT PRIMARY KEY (ID)
);


-- Dataset: GDS89826
CREATE SCHEMA IF NOT EXISTS SANCTION_SCANNER;

-- This client dataset supports leasing operations. Key applications include relationship management, c
CREATE TABLE IF NOT EXISTS SANCTION_SCANNER.FINANCE_RISK_INSIGHTS (
    ID NUMBER(18,0) NOT NULL,
    CLIENT_ID VARCHAR(36) NOT NULL,
    CLIENT_MASREPH_LEASING_ID VARCHAR(255) NOT NULL,
    CLIENT_GLOBAL_LEGACY_ID VARCHAR(255),
    CLIENT_TYPE_CODE VARCHAR(255) NOT NULL,
    CLIENT_RISK_SEGMENT_CODE VARCHAR(255) NOT NULL,
    CLIENT_ONBOARDING_DATE DATE NOT NULL,
    PRIMARY_RELATIONSHIP_MANAGER_ID VARCHAR(255),
    RELATIONSHIP_INTENSITY_SCORE NUMBER(5,2),
    LAST_INTERACTION_TIMESTAMP TIMESTAMP_NTZ,
    INTERACTION_CHANNEL_PREFERENCE VARCHAR(320),
    CLIENT_PROFITABILITY_TIER VARCHAR(255),
    AVERAGE_LEASE_OUTSTANDING_AMOUNT NUMBER(18,2),
    TOTAL_ACTIVE_LEASE_COUNT NUMBER(18,0) NOT NULL,
    LEASE_PORTFOLIO_RISK_RATING VARCHAR(255),
    EXPECTED_ANNUAL_REVENUE NUMBER(18,2),
    EXPECTED_ANNUAL_LOSS NUMBER(18,2),
    PROBABILITY_OF_DEFAULT_12M NUMBER(5,4),
    LOSS_GIVEN_DEFAULT_PERCENTAGE NUMBER(5,2),
    CLIENT_BEHAVIOUR_SCORE NUMBER(6,2),
    EARLY_TERMINATION_INCIDENT_COUNT NUMBER(18,0),
    PAYMENT_MORATORIUM_FLAG BOOLEAN NOT NULL,
    LAST_DELINQUENCY_RESOLVED_DATE DATE,
    DAYS_SINCE_LAST_CONTACT NUMBER(18,0),
    KYC_REVIEW_DUE_DATE DATE,
    GDPR_CONSENT_MARKETING_FLAG BOOLEAN NOT NULL,
    GDPR_CONSENT_LAST_UPDATED TIMESTAMP_NTZ,
    CROSS_SELL_ELIGIBILITY_FLAG BOOLEAN NOT NULL,
    CROSS_SELL_PRODUCT_RECOMMENDATIONS VARIANT,
    PREFERRED_CONTACT_COUNTRY_CODE VARCHAR(255),
    CLIENT_INDUSTRY_NACE_CODE VARCHAR(255),
    MASREPH_REGION_CODE VARCHAR(255) NOT NULL,
    CURRENCY_REPORTING_CODE VARCHAR(255) NOT NULL,
    CRM_SOURCE_SYSTEM_CODE VARCHAR(255) NOT NULL,
    RECORD_CREATION_TIMESTAMP TIMESTAMP_NTZ NOT NULL,
    RECORD_LAST_UPDATED_TIMESTAMP TIMESTAMP_NTZ NOT NULL,
    DATA_QUALITY_ISSUE_FLAG BOOLEAN NOT NULL,
    DATA_QUALITY_ISSUE_CODES VARIANT,
    RISK_INDICATOR_SUMMARY VARIANT,
    _LOADED_AT TIMESTAMP_NTZ,
    _SOURCE_SYSTEM VARCHAR(255)
    ,CONSTRAINT PK_FINANCE_RISK_INSIGHT PRIMARY KEY (ID)
);


-- Dataset: GDS96062
CREATE SCHEMA IF NOT EXISTS SANCTION_SCANNER;

-- This client dataset supports mobility solutions operations. Key applications include relationship ma
CREATE TABLE IF NOT EXISTS SANCTION_SCANNER.FINANCE_RISK_INSIGHTS (
    ID NUMBER(18,0) NOT NULL,
    CLIENT_ID VARCHAR(36) NOT NULL,
    CLIENT_GLOBAL_ID VARCHAR(255),
    RELATIONSHIP_MANAGER_ID VARCHAR(255),
    MOBILITY_CONTRACT_ID VARCHAR(255),
    AUTO_LOAN_ACCOUNT_ID VARCHAR(255),
    CRM_SEGMENT_CODE VARCHAR(255),
    CLIENT_RESIDENCE_COUNTRY VARCHAR(255) NOT NULL,
    CLIENT_AGE_YEARS NUMBER(18,0),
    CLIENT_RISK_RATING VARCHAR(255),
    RISK_RATING_LAST_REVIEW_DATE DATE,
    KYC_COMPLETION_STATUS VARCHAR(255) NOT NULL,
    KYC_LAST_REVIEW_TIMESTAMP TIMESTAMP_NTZ,
    GDPR_CONSENT_FLAG BOOLEAN NOT NULL,
    GDPR_CONSENT_LAST_UPDATED DATE,
    PREFERRED_CONTACT_CHANNEL VARCHAR(320),
    PRIMARY_VEHICLE_USAGE_TYPE VARCHAR(255),
    MOBILITY_PRODUCT_PORTFOLIO VARIANT,
    TOTAL_OUTSTANDING_AUTO_LOAN_BALANCE NUMBER(15,2),
    AVERAGE_MONTHLY_MOBILITY_SPEND NUMBER(12,2),
    CLIENT_PROFITABILITY_SCORE NUMBER(5,2),
    CLIENT_LIFETIME_VALUE_EUR NUMBER(15,2),
    PAYMENT_BEHAVIOR_SCORE NUMBER(5,2),
    LAST_MISSED_PAYMENT_DATE DATE,
    NUMBER_OF_ACTIVE_MOBILITY_CONTRACTS NUMBER(18,0),
    CHURN_RISK_SCORE NUMBER(5,4),
    CROSS_SELL_ELIGIBILITY_FLAG BOOLEAN NOT NULL,
    NEXT_BEST_OFFER_CODE VARCHAR(255),
    RELATIONSHIP_TENURE_MONTHS NUMBER(18,0),
    LAST_INTERACTION_TIMESTAMP TIMESTAMP_NTZ,
    LAST_INTERACTION_CHANNEL VARCHAR(320),
    COMPLAINT_INDICATOR_FLAG BOOLEAN NOT NULL,
    NET_PROMOTER_SCORE NUMBER(18,0),
    CREDIT_BUREAU_SCORE NUMBER(18,0),
    CREDIT_LIMIT_AUTO_LOAN_EUR NUMBER(15,2),
    LOAN_TO_VALUE_RATIO NUMBER(5,2),
    COLLATERAL_VEHICLE_CURRENT_VALUE_EUR NUMBER(15,2),
    DEFAULT_RISK_PROBABILITY_12M NUMBER(6,5),
    ANTI_FRAUD_ALERT_FLAG BOOLEAN NOT NULL,
    DATA_SOURCE_SYSTEM_CODE VARCHAR(255) NOT NULL,
    RECORD_EFFECTIVE_DATE DATE NOT NULL,
    RECORD_LAST_UPDATED_TIMESTAMP TIMESTAMP_NTZ NOT NULL,
    _LOADED_AT TIMESTAMP_NTZ,
    _SOURCE_SYSTEM VARCHAR(255)
    ,CONSTRAINT PK_FINANCE_RISK_INSIGHT PRIMARY KEY (ID)
);


