-- ============================================
-- Platform: SNOWFLAKE
-- Schema/Source: VERIFF
-- Generated: 2026-03-18T12:18:16.820666
-- Datasets: 3
-- ============================================

-- Dataset: GDS45287
CREATE SCHEMA IF NOT EXISTS VERIFF;

-- This risk management dataset supports mobility solutions operations. Key applications include data a
CREATE TABLE IF NOT EXISTS VERIFF.GLOBAL_CLIENT_SCREENING_DATA (
    ID NUMBER(18,0) NOT NULL,
    DATASET_CLIENT_ID VARCHAR(36) NOT NULL,
    GLOBAL_CLIENT_REFERENCE VARCHAR(255) NOT NULL,
    MASREPH_CUSTOMER_NUMBER VARCHAR(255),
    SCREENING_BATCH_ID VARCHAR(255) NOT NULL,
    SOURCE_SYSTEM_CODE VARCHAR(255) NOT NULL,
    CLIENT_TYPE_CODE VARCHAR(255) NOT NULL,
    CLIENT_FULL_NAME VARCHAR(255) NOT NULL,
    PRIMARY_NATIONAL_ID VARCHAR(255),
    NATIONAL_ID_COUNTRY_CODE VARCHAR(255),
    DATE_OF_BIRTH DATE,
    COUNTRY_OF_RESIDENCE_CODE VARCHAR(255) NOT NULL,
    RISK_COUNTRY_RATING VARCHAR(255) NOT NULL,
    PEP_FLAG BOOLEAN NOT NULL,
    SANCTIONS_MATCH_INDICATOR VARCHAR(255) NOT NULL,
    SANCTIONS_LIST_NAMES VARIANT,
    ADVERSE_MEDIA_SCORE NUMBER(5,2),
    ADVERSE_MEDIA_LAST_REVIEW_TS TIMESTAMP_NTZ,
    KYC_RISK_SCORE NUMBER(18,0) NOT NULL,
    KYC_REVIEW_STATUS VARCHAR(255) NOT NULL,
    KYC_NEXT_REVIEW_DATE DATE,
    ONBOARDING_CHANNEL VARCHAR(255) NOT NULL,
    MOBILITY_PRODUCT_TYPE VARCHAR(255),
    VEHICLE_IDENTIFICATION_NUMBER VARCHAR(255),
    LOAN_APPLICATION_ID VARCHAR(255),
    FRAUD_ALERT_FLAG BOOLEAN NOT NULL,
    FRAUD_ALERT_REASON_CODES VARIANT,
    WATCHLIST_MATCH_SCORE NUMBER(5,2),
    MATCH_RESOLUTION_STATUS VARCHAR(255) NOT NULL,
    MATCH_RESOLUTION_TIMESTAMP TIMESTAMP_NTZ,
    DATA_PRIVACY_CONSENT_FLAG BOOLEAN NOT NULL,
    GDPR_PROCESSING_BASIS_CODE VARCHAR(255),
    RECORD_EFFECTIVE_TIMESTAMP TIMESTAMP_NTZ NOT NULL,
    RECORD_LAST_UPDATED_TIMESTAMP TIMESTAMP_NTZ NOT NULL,
    IS_RECORD_ACTIVE BOOLEAN NOT NULL,
    CLIENT_CONTACT_SUMMARY VARCHAR(320),
    REGULATORY_REPORTING_SEGMENT VARCHAR(255),
    RELATIONSHIP_MANAGER_REGION VARCHAR(255),
    _LOADED_AT TIMESTAMP_NTZ,
    _SOURCE_SYSTEM VARCHAR(255)
    ,CONSTRAINT PK_GLOBAL_CLIENT_SCREEN PRIMARY KEY (ID)
);


-- Dataset: GDS62827
CREATE SCHEMA IF NOT EXISTS VERIFF;

-- This risk management dataset supports leasing operations. Key applications include data analysis, re
CREATE TABLE IF NOT EXISTS VERIFF.GLOBAL_CLIENT_SCREENING_DATA (
    ID NUMBER(18,0) NOT NULL,
    CLIENT_SCREENING_ID VARCHAR(36) NOT NULL,
    CLIENT_INTERNAL_ID VARCHAR(255) NOT NULL,
    CLIENT_LEGAL_NAME VARCHAR(255) NOT NULL,
    CLIENT_TRADING_NAME VARCHAR(255),
    CLIENT_TYPE VARCHAR(255) NOT NULL,
    COUNTRY_OF_INCORPORATION VARCHAR(255),
    COUNTRY_OF_RESIDENCE VARCHAR(255),
    PRIMARY_LEASING_MARKET VARCHAR(255),
    DATE_OF_BIRTH_OR_INCORPORATION DATE,
    NATIONAL_ID_NUMBER VARCHAR(255),
    TAX_IDENTIFICATION_NUMBER VARCHAR(255),
    SECTOR_CODE VARCHAR(255),
    PEP_FLAG BOOLEAN NOT NULL,
    PEP_RISK_LEVEL VARCHAR(255) NOT NULL,
    SANCTIONS_MATCH_FLAG BOOLEAN NOT NULL,
    SANCTIONS_MATCH_STATUS VARCHAR(255) NOT NULL,
    WATCHLIST_SOURCES VARIANT,
    ADVERSE_MEDIA_FLAG BOOLEAN NOT NULL,
    ADVERSE_MEDIA_SUMMARY VARCHAR(255),
    OVERALL_RISK_RATING VARCHAR(255) NOT NULL,
    RISK_SCORE_NUMERIC NUMBER(5,2) NOT NULL,
    SCREENING_STATUS VARCHAR(255) NOT NULL,
    INITIAL_SCREENING_DATE DATE NOT NULL,
    LAST_SCREENING_TIMESTAMP TIMESTAMP_NTZ NOT NULL,
    NEXT_REVIEW_DATE DATE,
    REVIEW_FREQUENCY_MONTHS NUMBER(18,0) NOT NULL,
    KYC_COMPLETION_FLAG BOOLEAN NOT NULL,
    KYC_DOCUMENTATION_STATUS VARCHAR(255) NOT NULL,
    ULTIMATE_BENEFICIAL_OWNER_COUNT NUMBER(18,0),
    OWNERSHIP_STRUCTURE_RISK VARCHAR(255),
    LEASING_EXPOSURE_EUR NUMBER(18,2),
    MAX_SINGLE_CONTRACT_AMOUNT_EUR NUMBER(18,2),
    TRANSACTION_VELOCITY_SCORE NUMBER(6,2),
    GEO_RISK_SCORE NUMBER(4,1),
    DATA_PRIVACY_CONSENT_FLAG BOOLEAN NOT NULL,
    GDPR_DATA_PROCESSING_BASIS VARCHAR(255) NOT NULL,
    SCREENING_ENGINE_VERSION VARCHAR(255) NOT NULL,
    MATCH_CONFIDENCE_SCORE NUMBER(5,2),
    MANUAL_REVIEW_REQUIRED_FLAG BOOLEAN NOT NULL,
    MANUAL_REVIEW_OUTCOME VARCHAR(255),
    MLRO_APPROVAL_FLAG BOOLEAN,
    SUSPICIOUS_ACTIVITY_REPORT_FLAG BOOLEAN,
    CLIENT_CONTACT_EMAIL VARCHAR(320),
    PRIMARY_BANK_IBAN VARCHAR(34),
    DATA_QUALITY_SCORE NUMBER(3,1),
    RECORD_LAST_UPDATED_TIMESTAMP TIMESTAMP_NTZ NOT NULL,
    _LOADED_AT TIMESTAMP_NTZ,
    _SOURCE_SYSTEM VARCHAR(255)
    ,CONSTRAINT PK_GLOBAL_CLIENT_SCREEN PRIMARY KEY (ID)
);


-- Dataset: GDS82864
CREATE SCHEMA IF NOT EXISTS VERIFF;

-- This risk management dataset supports leasing operations. Key applications include data analysis, re
CREATE TABLE IF NOT EXISTS VERIFF.GLOBAL_CLIENT_COMPLIANCE_DATA (
    ID NUMBER(18,0) NOT NULL,
    DATASET_RECORD_ID VARCHAR(36) NOT NULL,
    CLIENT_GLOBAL_ID VARCHAR(255) NOT NULL,
    CLIENT_LEGAL_NAME VARCHAR(255) NOT NULL,
    CLIENT_COUNTRY_OF_DOMICILE VARCHAR(255) NOT NULL,
    CLIENT_LEASING_SEGMENT VARCHAR(255),
    REGULATORY_JURISDICTION_CODE VARCHAR(255) NOT NULL,
    UK_REGULATORY_CLASSIFICATION VARCHAR(255),
    COMPLIANCE_ASSESSMENT_DATE DATE NOT NULL,
    COMPLIANCE_STATUS VARCHAR(255) NOT NULL,
    COMPLIANCE_STATUS_REASON VARCHAR(255),
    GDP_COMPLIANT_FLAG BOOLEAN NOT NULL,
    KYC_COMPLETED_FLAG BOOLEAN NOT NULL,
    AML_RISK_RATING VARCHAR(255) NOT NULL,
    AML_RISK_SCORE NUMBER(5,2) NOT NULL,
    SANCTIONS_SCREENING_STATUS VARCHAR(255) NOT NULL,
    SANCTIONS_LAST_SCREENED_TIMESTAMP TIMESTAMP_NTZ NOT NULL,
    POLITICALLY_EXPOSED_PERSON_FLAG BOOLEAN NOT NULL,
    TAX_RESIDENCY_COUNTRY_CODE VARCHAR(255),
    BENEFICIAL_OWNER_DISCLOSURE_FLAG BOOLEAN NOT NULL,
    DATA_PROCESSING_LEGAL_BASIS VARCHAR(255),
    CONSENT_CAPTURE_TIMESTAMP TIMESTAMP_NTZ,
    CONSENT_WITHDRAWN_FLAG BOOLEAN NOT NULL,
    LEASE_CONTRACT_ID VARCHAR(255),
    LEASE_START_DATE DATE,
    LEASE_END_DATE DATE,
    ASSET_CATEGORY VARCHAR(255),
    OUTSTANDING_LEASE_EXPOSURE_AMOUNT NUMBER(18,2),
    CURRENCY_CODE VARCHAR(255),
    PAST_BREACH_INDICATOR BOOLEAN NOT NULL,
    PAST_BREACH_COUNT NUMBER(18,0) NOT NULL,
    LAST_BREACH_RESOLUTION_DATE DATE,
    REGULATORY_REPORTING_REGION VARCHAR(255) NOT NULL,
    MONITORING_FREQUENCY_DAYS NUMBER(18,0) NOT NULL,
    REAL_TIME_MONITORING_ENABLED_FLAG BOOLEAN NOT NULL,
    STREAMING_SOURCE_SYSTEM VARCHAR(255),
    RECORD_EFFECTIVE_START_TIMESTAMP TIMESTAMP_NTZ NOT NULL,
    RECORD_EFFECTIVE_END_TIMESTAMP TIMESTAMP_NTZ,
    RECORD_CURRENT_FLAG BOOLEAN NOT NULL,
    DATA_QUALITY_SCORE NUMBER(5,2) NOT NULL,
    DATA_LINEAGE_REFERENCE VARCHAR(255),
    SETTLEMENT_WARRANTY_ELIGIBILITY_FLAG BOOLEAN NOT NULL,
    SETTLEMENT_WARRANTY_EXCLUSION_REASON VARCHAR(255),
    GDPR_DATA_RETENTION_END_DATE DATE,
    UK_CUSTOMER_FLAG BOOLEAN NOT NULL,
    _LOADED_AT TIMESTAMP_NTZ,
    _SOURCE_SYSTEM VARCHAR(255)
    ,CONSTRAINT PK_GLOBAL_CLIENT_COMPLI PRIMARY KEY (ID)
);


