-- ============================================
-- Platform: FABRIC
-- Schema/Source: DataedoCRDM
-- Generated: 2026-03-18T12:18:16.873157
-- Datasets: 16
-- ============================================

-- Dataset: GDS10949

-- This customer dataset supports innovation & technology operations. Key applications include customer
CREATE TABLE [DataedoCRDM].[TreatyTaxStatusDataset] (
    Id INT NOT NULL,
    TreatyTaxStatusId UNIQUEIDENTIFIER NOT NULL,
    CustomerId VARCHAR(255) NOT NULL,
    LegalEntityIdentifier VARCHAR(255),
    TaxResidencyCountryCode VARCHAR(255) NOT NULL,
    TreatyCountryCode VARCHAR(255) NOT NULL,
    TreatyApplicableFlag BIT NOT NULL,
    TreatyArticleReference VARCHAR(255),
    WithholdingTaxRateTreaty DECIMAL(5,2),
    WithholdingTaxRateDomestic DECIMAL(5,2) NOT NULL,
    TreatyBenefitStartDate DATE,
    TreatyBenefitEndDate DATE,
    LastTreatyReviewDate DATE,
    TreatyEligibilityStatus VARCHAR(255) NOT NULL,
    TreatyEligibilityReason VARCHAR(255),
    PrimaryIndustryCode VARCHAR(255),
    CustomerSegmentCode VARCHAR(255),
    ChurnRiskScore DECIMAL(5,4),
    LifetimeValueScore DECIMAL(10,2),
    PersonalizationSegmentId VARCHAR(255),
    CrossSellEligibilityFlag BIT NOT NULL,
    TaxFormType VARCHAR(255),
    TaxFormReceivedDate DATE,
    TaxFormExpiryDate DATE,
    BeneficialOwnerFlag BIT,
    PrincipalPurposeTestPassedFlag BIT,
    LimitationOfBenefitStatus VARCHAR(255),
    SubstanceRequirementsMetFlag BIT,
    DocumentationCompletenessScore DECIMAL(5,2),
    KycRiskRating VARCHAR(255),
    OnboardingChannel VARCHAR(255),
    OnboardingDate DATE,
    CountryOfIncorporationCode VARCHAR(255),
    LegalEntityType VARCHAR(255),
    GroupAffiliationId VARCHAR(255),
    RevenueBandCode VARCHAR(255),
    EmployeeCount INT,
    DigitalEngagementScore DECIMAL(6,2),
    LastDigitalInteractionTs DATETIME2,
    ConsentToDataProcessingFlag BIT NOT NULL,
    GdprDataErasureRequestedFlag BIT NOT NULL,
    DataLastUpdatedTs DATETIME2 NOT NULL,
    RecordSourceSystem VARCHAR(255) NOT NULL,
    StreamingIngestionTimestamp DATETIME2 NOT NULL,
    TreatyStatusVersion INT NOT NULL,
    PreferredCommunicationChannel VARCHAR(320),
    MarketingOptInFlag BIT NOT NULL,
    AnomalyRiskFlag BIT,
    TaxAuditHistory VARCHAR(MAX),
    LoadedAt DATETIME2,
    SourceSystem VARCHAR(255)
    ,CONSTRAINT PK_TreatyTaxStatusDatas PRIMARY KEY (Id)
);


-- Dataset: GDS30230

-- This partner dataset supports finance office operations. Key applications include data analysis, rep
CREATE TABLE [DataedoCRDM].[LiquidityFinanceContractsDataset] (
    Id INT NOT NULL,
    ContractId UNIQUEIDENTIFIER NOT NULL,
    PartnerLegalEntityId VARCHAR(255) NOT NULL,
    ContractExternalReference VARCHAR(255),
    ContractTypeCode VARCHAR(255) NOT NULL,
    ContractSubtypeCode VARCHAR(255),
    LiquidityProductName VARCHAR(255) NOT NULL,
    CounterpartyName VARCHAR(255) NOT NULL,
    CounterpartyLei VARCHAR(255),
    BookingEntityCode VARCHAR(255) NOT NULL,
    ContractTradeDate DATE NOT NULL,
    ContractEffectiveTimestamp DATETIME2 NOT NULL,
    ContractMaturityDate DATE,
    ContractCloseTimestamp DATETIME2,
    ContractCurrencyCode VARCHAR(255) NOT NULL,
    NotionalAmount DECIMAL(18,2) NOT NULL,
    DrawnAmount DECIMAL(18,2) NOT NULL,
    UndrawnAmount DECIMAL(18,2) NOT NULL,
    InterestRateType VARCHAR(255) NOT NULL,
    InterestRateIndex VARCHAR(255),
    InterestRateSpreadBps DECIMAL(9,4),
    FixedInterestRate DECIMAL(9,6),
    DayCountConvention VARCHAR(255),
    PaymentFrequencyCode VARCHAR(255),
    LiquidityBucketTenor VARCHAR(255) NOT NULL,
    ContractStatusCode VARCHAR(255) NOT NULL,
    RiskCountryCode VARCHAR(255),
    InternalRiskRating VARCHAR(255),
    ProbabilityOfDefault DECIMAL(5,4),
    ExpectedLossAmount DECIMAL(18,2),
    CollateralizationFlag BIT NOT NULL,
    CollateralTypeCode VARCHAR(255),
    ReportingEffectiveDate DATE NOT NULL,
    LastValuationTimestamp DATETIME2,
    MarketValueAmount DECIMAL(18,2),
    DataSourceSystemCode VARCHAR(255) NOT NULL,
    RecordCreatedTimestamp DATETIME2 NOT NULL,
    RecordLastUpdatedTimestamp DATETIME2 NOT NULL,
    IsRecordActive BIT NOT NULL,
    LoadedAt DATETIME2,
    SourceSystem VARCHAR(255)
    ,CONSTRAINT PK_LiquidityFinanceCont PRIMARY KEY (Id)
);


-- Dataset: GDS32391

-- This client dataset supports innovation & technology operations. Key applications include relationsh
CREATE TABLE [DataedoCRDM].[FinanceSectorMappingDataset] (
    Id INT NOT NULL,
    DatasetEntityId UNIQUEIDENTIFIER NOT NULL,
    SourceSystemId VARCHAR(255) NOT NULL,
    LegalEntityIdentifier VARCHAR(255),
    ClientGlobalUltimateParentId VARCHAR(255),
    ClientLegalName VARCHAR(255) NOT NULL,
    ClientTradingName VARCHAR(255),
    CountryOfIncorporationCode VARCHAR(255) NOT NULL,
    PrimaryIndustryCode VARCHAR(255) NOT NULL,
    IndustryClassificationScheme VARCHAR(255) NOT NULL,
    FintechInnovationSegment VARCHAR(255),
    RelationshipManagerUserId VARCHAR(255),
    ClientProfitabilitySegment VARCHAR(255),
    AnnualRevenueUsd DECIMAL(18,2),
    TotalAssetsUsd DECIMAL(20,2),
    ClientTierCode VARCHAR(255),
    ClientRiskRating VARCHAR(255),
    OnboardingDate DATE,
    LastInteractionTimestamp DATETIME2,
    IsStrategicClient BIT NOT NULL,
    GdprDataProcessingFlag BIT NOT NULL,
    ConsentMarketingCommunicationsFlag BIT,
    GlobalCoverageTeam VARCHAR(MAX),
    ActiveProductRelationships VARCHAR(MAX),
    InteractionChannels VARCHAR(320),
    PrimaryContactEmailHash VARCHAR(255),
    DataPrivacyRegion VARCHAR(255) NOT NULL,
    StreamingIngestionTimestamp DATETIME2 NOT NULL,
    RecordSourceEnvironment VARCHAR(255) NOT NULL,
    IsRecordActive BIT NOT NULL,
    LastReviewDate DATE,
    ClientProfitMarginPct DECIMAL(5,2),
    WalletShareEstimatePct DECIMAL(5,2),
    CrossSellOpportunityScore INT,
    DataQualityScore INT,
    LoadedAt DATETIME2,
    SourceSystem VARCHAR(255)
    ,CONSTRAINT PK_FinanceSectorMapping PRIMARY KEY (Id)
);


-- Dataset: GDS32920

-- This partner dataset supports finance office operations. Key applications include data analysis, rep
CREATE TABLE [DataedoCRDM].[FeeFinanceClassificationDataset] (
    Id INT NOT NULL,
    FeeRecordId UNIQUEIDENTIFIER NOT NULL,
    PartnerInstitutionId VARCHAR(255) NOT NULL,
    PartnerInstitutionName VARCHAR(255) NOT NULL,
    FeeScheduleId VARCHAR(255),
    FeeCode VARCHAR(255) NOT NULL,
    FeeName VARCHAR(255) NOT NULL,
    FeeDescription VARCHAR(255),
    FeeType VARCHAR(255) NOT NULL,
    FeeSubtype VARCHAR(255),
    FeeCategory VARCHAR(255),
    FeeCurrencyCode VARCHAR(255) NOT NULL,
    FeeAmountStandard DECIMAL(15,2) NOT NULL,
    FeeAmountMinimum DECIMAL(15,2),
    FeeAmountMaximum DECIMAL(15,2),
    FeeAmountUnit DECIMAL(5,2) NOT NULL,
    FeeCalculationMethod VARCHAR(255),
    FeeFrequencyCode VARCHAR(255) NOT NULL,
    FeeApplicabilityStartDate DATE NOT NULL,
    FeeApplicabilityEndDate DATE,
    IsFeeTaxable BIT NOT NULL,
    TaxRatePercentage DECIMAL(7,4),
    TaxAmountStandard DECIMAL(15,2),
    TotalFeeAmountStandard DECIMAL(15,2),
    FeeWaiverAllowedFlag BIT NOT NULL,
    FeeWaiverReasonCode VARCHAR(255),
    FeeDiscountAllowedFlag BIT NOT NULL,
    FeeDiscountPercentageMax DECIMAL(5,2),
    CustomerSegmentCode VARCHAR(255),
    ProductTypeCode VARCHAR(255) NOT NULL,
    ProductName VARCHAR(255),
    ChannelCode VARCHAR(255),
    FeeApplicableAccountTypes VARCHAR(MAX),
    CountryCode VARCHAR(255) NOT NULL,
    JurisdictionCode VARCHAR(255),
    EffectiveTimestamp DATETIME2 NOT NULL,
    CreatedTimestamp DATETIME2 NOT NULL,
    CreatedByUserId VARCHAR(255),
    LastUpdatedTimestamp DATETIME2,
    LastUpdatedByUserId VARCHAR(255),
    FeeStatusCode VARCHAR(255) NOT NULL,
    FeeRegulatoryReference VARCHAR(255),
    DisclosureRequiredFlag BIT NOT NULL,
    ReportingGroupCode VARCHAR(255),
    InternalCostCenterCode VARCHAR(255),
    DataSourceSystemCode VARCHAR(255) NOT NULL,
    RecordActiveFlag BIT NOT NULL,
    DataQualityIssueFlag BIT NOT NULL,
    DataLineageObject VARCHAR(MAX),
    LoadedAt DATETIME2,
    SourceSystem VARCHAR(255)
    ,CONSTRAINT PK_FeeFinanceClassifica PRIMARY KEY (Id)
);


-- Dataset: GDS48794

-- This client dataset supports innovation & technology operations. Key applications include relationsh
CREATE TABLE [DataedoCRDM].[FinanceRollupOverview] (
    Id INT NOT NULL,
    ClientId VARCHAR(255) NOT NULL,
    ClientLegalName VARCHAR(255) NOT NULL,
    ClientSegmentCode VARCHAR(255) NOT NULL,
    ReportingPeriodStartDate DATE NOT NULL,
    ReportingPeriodEndDate DATE NOT NULL,
    ReportingCurrencyCode VARCHAR(255) NOT NULL,
    TotalRevenueAmount DECIMAL(18,2),
    TotalOperatingExpenseAmount DECIMAL(18,2),
    NetProfitAmount DECIMAL(18,2),
    ProfitMarginPercent DECIMAL(5,2),
    RelationshipManagerId VARCHAR(255),
    RelationshipManagerName VARCHAR(255),
    ClientLifecycleStage VARCHAR(255),
    PrimaryIndustryCode VARCHAR(255),
    ClientRegionCode VARCHAR(255),
    DomicileCountryCode VARCHAR(255),
    IsStrategicClient BIT NOT NULL,
    LastInteractionTimestamp DATETIME2,
    InteractionVolumeCount INT,
    CrossSellOpportunityScore DECIMAL(5,2),
    WalletSharePercent DECIMAL(5,2),
    DataSourceSystemCode VARCHAR(255) NOT NULL,
    RecordEffectiveDate DATE NOT NULL,
    RecordCreatedTimestamp DATETIME2 NOT NULL,
    RecordLastUpdatedTimestamp DATETIME2 NOT NULL,
    IsRecordActive BIT NOT NULL,
    RevenueGrowthRatePercent DECIMAL(6,2),
    ExpenseToRevenueRatioPercent DECIMAL(6,2),
    AverageProductUtilizationScore DECIMAL(5,2),
    CreditExposureAmount DECIMAL(18,2),
    ClientConfidentialityLevel VARCHAR(255) NOT NULL,
    DataLineageReferenceId UNIQUEIDENTIFIER,
    ServiceSatisfactionIndex DECIMAL(5,2),
    DigitalChannelEngagementScore DECIMAL(5,2),
    RelationshipTenureDays INT,
    LoadedAt DATETIME2,
    SourceSystem VARCHAR(255)
    ,CONSTRAINT PK_FinanceRollupOvervie PRIMARY KEY (Id)
);


-- Dataset: GDS49287

-- This partner dataset supports finance office operations. Key applications include data analysis, rep
CREATE TABLE [DataedoCRDM].[RateClassificationDataset] (
    Id INT NOT NULL,
    RateClassificationId UNIQUEIDENTIFIER NOT NULL,
    PartnerOrganizationId VARCHAR(255) NOT NULL,
    PartnerProductCode VARCHAR(255) NOT NULL,
    InternalProductId VARCHAR(255),
    ProductTypeCode VARCHAR(255) NOT NULL,
    ProductSubtypeCode VARCHAR(255),
    RateClassCode VARCHAR(255) NOT NULL,
    RateClassDescription VARCHAR(255),
    InterestRateType VARCHAR(255) NOT NULL,
    BaseInterestRate DECIMAL(7,4) NOT NULL,
    MarginSpreadRate DECIMAL(6,4),
    EffectiveInterestRate DECIMAL(7,4),
    AnnualPercentageRateApr DECIMAL(7,4),
    IndexReferenceCode VARCHAR(255),
    IndexValue DECIMAL(7,4),
    RateEffectiveDate DATE NOT NULL,
    RateExpirationDate DATE,
    RateLastUpdatedTimestamp DATETIME2 NOT NULL,
    RateClassificationStatus VARCHAR(255) NOT NULL,
    CurrencyCode VARCHAR(255) NOT NULL,
    CountryOfBook VARCHAR(255),
    CustomerSegmentCode VARCHAR(255),
    RiskGradeCode VARCHAR(255),
    TenorInMonths INT,
    IntroductoryPeriodMonths INT,
    PenaltyRateFlag BIT NOT NULL,
    PromotionalRateFlag BIT NOT NULL,
    FloorRate DECIMAL(6,4),
    CeilingRate DECIMAL(6,4),
    RateChangeFrequencyCode VARCHAR(255),
    RateChangeCapPerPeriod DECIMAL(5,3),
    LifetimeRateChangeCap DECIMAL(5,3),
    MinEligibleBalanceAmount DECIMAL(15,2),
    MaxEligibleBalanceAmount DECIMAL(15,2),
    DataSourceSystemCode VARCHAR(255) NOT NULL,
    DataIngestionTimestamp DATETIME2 NOT NULL,
    IsHistoricalSnapshot BIT NOT NULL,
    SnapshotAsOfDate DATE,
    ApprovalStatusCode VARCHAR(255) NOT NULL,
    ApprovedByUserId VARCHAR(255),
    ApprovalTimestamp DATETIME2,
    RateCalculationMethodCode VARCHAR(255) NOT NULL,
    CompoundingFrequencyCode VARCHAR(255),
    BusinessLineOwnerCode VARCHAR(255) NOT NULL,
    DataQualityScore DECIMAL(5,2),
    LoadedAt DATETIME2,
    SourceSystem VARCHAR(255)
    ,CONSTRAINT PK_RateClassificationDa PRIMARY KEY (Id)
);


-- Dataset: GDS58935

-- This product dataset supports leasing operations. Key applications include product performance analy
CREATE TABLE [DataedoCRDM].[InterestMappingDataset] (
    Id INT NOT NULL,
    InterestMappingId UNIQUEIDENTIFIER NOT NULL,
    ProductId VARCHAR(255) NOT NULL,
    ProductName VARCHAR(255) NOT NULL,
    MasrephEntityId VARCHAR(255) NOT NULL,
    LeaseContractId VARCHAR(255),
    PortfolioId VARCHAR(255),
    CountryCode VARCHAR(255) NOT NULL,
    RegionCode VARCHAR(255),
    CurrencyCode VARCHAR(255) NOT NULL,
    BookingDate DATE NOT NULL,
    ValueDate DATE NOT NULL,
    MaturityDate DATE,
    RateEffectiveDate DATE NOT NULL,
    RateEndDate DATE,
    InterestRateType VARCHAR(255) NOT NULL,
    InterestRateBasis VARCHAR(255),
    BaseRateIndex VARCHAR(255),
    BaseRateValue DECIMAL(7,4),
    SpreadRate DECIMAL(7,4),
    AllInRate DECIMAL(7,4) NOT NULL,
    TeaserRateFlag BIT NOT NULL,
    PromotionalRateEndDate DATE,
    FixedRateFlag BIT NOT NULL,
    VariableRateResetFrequency VARCHAR(255),
    CompoundingFrequency VARCHAR(255),
    DayCountConvention VARCHAR(255),
    AmortizationType VARCHAR(255),
    LeaseTermMonths INT NOT NULL,
    OriginalPrincipalAmount DECIMAL(15,2) NOT NULL,
    OutstandingPrincipalAmount DECIMAL(15,2) NOT NULL,
    AccruedInterestAmount DECIMAL(15,2) NOT NULL,
    InterestIncomeMtd DECIMAL(15,2) NOT NULL,
    InterestIncomeYtd DECIMAL(15,2) NOT NULL,
    ExpectedYieldPercent DECIMAL(7,4),
    RiskRatingInternal VARCHAR(255),
    DelinquencyStatus VARCHAR(255) NOT NULL,
    NonAccrualFlag BIT NOT NULL,
    PrepaymentPenaltyRate DECIMAL(6,4),
    ProductSegment VARCHAR(255) NOT NULL,
    CustomerSegment VARCHAR(255) NOT NULL,
    PricingStrategyCode VARCHAR(255),
    ApplicableSalesChannels VARCHAR(MAX),
    CompetitiveRateBenchmark VARCHAR(MAX),
    DataSourceSystem VARCHAR(255) NOT NULL,
    RecordEffectiveTimestamp DATETIME2 NOT NULL,
    RecordCreatedTimestamp DATETIME2 NOT NULL,
    RecordLastUpdatedTimestamp DATETIME2 NOT NULL,
    IsActiveRecord BIT NOT NULL,
    DataQualityScore DECIMAL(5,2) NOT NULL,
    LoadedAt DATETIME2,
    SourceSystem VARCHAR(255)
    ,CONSTRAINT PK_InterestMappingDatas PRIMARY KEY (Id)
);


-- Dataset: GDS63424

-- This collateral dataset supports innovation & technology operations. Key applications include asset 
CREATE TABLE [DataedoCRDM].[FinanceRelationshipCategories] (
    Id INT NOT NULL,
    FinanceRelationshipId UNIQUEIDENTIFIER NOT NULL,
    SourceSystemId VARCHAR(255) NOT NULL,
    CustomerPartyId VARCHAR(255) NOT NULL,
    CounterpartyInstitutionId VARCHAR(255) NOT NULL,
    RelationshipTypeCode VARCHAR(255) NOT NULL,
    RelationshipTypeDescription VARCHAR(255),
    CollateralAssetId VARCHAR(255),
    CollateralAssetCategory VARCHAR(255),
    CollateralAssetSubcategory VARCHAR(255),
    JurisdictionCountryCode VARCHAR(255),
    RegulatoryReportingRegion VARCHAR(255),
    OnboardingDate DATE,
    RelationshipStartDate DATE NOT NULL,
    RelationshipEndDate DATE,
    IsActiveRelationship BIT NOT NULL,
    ExposureAmount DECIMAL(18,2),
    ExposureCurrencyCode VARCHAR(255),
    CollateralValuationAmount DECIMAL(18,2),
    CollateralValuationCurrencyCode VARCHAR(255),
    ValuationEffectiveDate DATE,
    LoanToValueRatio DECIMAL(6,3),
    RiskRatingInternal VARCHAR(255),
    RiskRatingExternal VARCHAR(255),
    RiskRatingModelVersion VARCHAR(255),
    DefaultProbabilityPercent DECIMAL(5,3),
    LossGivenDefaultPercent DECIMAL(5,2),
    RecoveryRateEstimatePercent DECIMAL(5,2),
    CollateralHaircutPercent DECIMAL(5,2),
    CollateralPriorityRank INT,
    LegalAgreementType VARCHAR(255),
    LegalAgreementId VARCHAR(255),
    SecuredIndicator BIT NOT NULL,
    SecurityPerfectionStatus VARCHAR(255),
    MonitoringFrequencyCode VARCHAR(255),
    LastMonitoringTimestamp DATETIME2,
    NextReviewDate DATE,
    DataSourceChannel VARCHAR(255),
    RecordCreationTimestamp DATETIME2 NOT NULL,
    RecordLastUpdatedTimestamp DATETIME2 NOT NULL,
    DataQualityScore DECIMAL(5,2),
    LoadedAt DATETIME2,
    SourceSystem VARCHAR(255)
    ,CONSTRAINT PK_FinanceRelationshipC PRIMARY KEY (Id)
);


-- Dataset: GDS66370

-- This partner dataset supports finance office operations. Key applications include data analysis, rep
CREATE TABLE [DataedoCRDM].[FeeFinanceDataset] (
    Id INT NOT NULL,
    FeeRecordId UNIQUEIDENTIFIER NOT NULL,
    InstitutionId VARCHAR(255) NOT NULL,
    InstitutionName VARCHAR(255) NOT NULL,
    FeeTypeCode VARCHAR(255) NOT NULL,
    FeeTypeDescription VARCHAR(255) NOT NULL,
    FeeCategory VARCHAR(255) NOT NULL,
    CorporateCustomerId VARCHAR(255) NOT NULL,
    CorporateLegalName VARCHAR(255),
    AccountId VARCHAR(255) NOT NULL,
    AccountIban VARCHAR(34),
    TransactionId VARCHAR(255),
    FeePostedTimestamp DATETIME2 NOT NULL,
    FeeValueDate DATE NOT NULL,
    FeeCurrencyCode VARCHAR(255) NOT NULL,
    FeeAmount DECIMAL(18,4) NOT NULL,
    FeeTaxAmount DECIMAL(18,4),
    FeeAmountHomeCurrency DECIMAL(18,4),
    HomeCurrencyCode VARCHAR(255) NOT NULL,
    FxRateApplied DECIMAL(18,8),
    FeePricingBasis DECIMAL(5,2),
    FeeRatePercentage DECIMAL(9,6),
    BaseAmountForFee DECIMAL(18,4),
    FeeWaivedIndicator BIT NOT NULL,
    FeeReversalIndicator BIT NOT NULL,
    OriginalFeeRecordId UNIQUEIDENTIFIER,
    FeeStatus VARCHAR(255) NOT NULL,
    BillingCycleId VARCHAR(255),
    StatementDate DATE,
    CountryOfInstitution VARCHAR(255) NOT NULL,
    CountryOfCorporate VARCHAR(255),
    RegulatoryFeeIndicator BIT NOT NULL,
    InternalCostCenterCode VARCHAR(255),
    PartnerContractId VARCHAR(255),
    FeeDescriptionLong VARCHAR(255),
    DisputeIndicator BIT NOT NULL,
    DisputeStatus VARCHAR(255) NOT NULL,
    DisputeOpenDate DATE,
    FeeSettlementMethod VARCHAR(255),
    RecordCreationTimestamp DATETIME2 NOT NULL,
    RecordLastUpdateTimestamp DATETIME2,
    SourceSystemName VARCHAR(255) NOT NULL,
    SourceSystemRecordKey VARCHAR(255),
    DataQualityFlags VARCHAR(MAX),
    LoadedAt DATETIME2,
    SourceSystem VARCHAR(255)
    ,CONSTRAINT PK_FeeFinanceDataset PRIMARY KEY (Id)
);


-- Dataset: GDS69801

-- This it dataset supports innovation & technology operations. Key applications include data analysis,
CREATE TABLE [DataedoCRDM].[FinanceBOCodes] (
    Id INT NOT NULL,
    BoCodeId UNIQUEIDENTIFIER NOT NULL,
    BoCode VARCHAR(255) NOT NULL,
    BoCodeName VARCHAR(255) NOT NULL,
    BoCodeDescription VARCHAR(255),
    BoCodeCategory VARCHAR(255) NOT NULL,
    BoCodeSubcategory VARCHAR(255),
    LineOfBusinessCode VARCHAR(255) NOT NULL,
    LineOfBusinessName VARCHAR(255) NOT NULL,
    OwningOrganisationUnitCode VARCHAR(255) NOT NULL,
    OwningOrganisationUnitName VARCHAR(255) NOT NULL,
    GlobalAppSystemId VARCHAR(255),
    GlReferenceCode VARCHAR(255),
    RegulatoryReportingFlag BIT NOT NULL,
    InternalReportingFlag BIT NOT NULL,
    KpiReportingFlag BIT NOT NULL,
    CostAllocationModelCode VARCHAR(255),
    AverageDailyTxnVolume INT,
    AverageTxnValueAmount DECIMAL(18,2),
    ReportingCurrencyCode VARCHAR(255),
    EffectiveStartDate DATE NOT NULL,
    EffectiveEndDate DATE,
    CreationTimestamp DATETIME2 NOT NULL,
    LastUpdateTimestamp DATETIME2,
    ActiveFlag BIT NOT NULL,
    DeprecatedFlag BIT NOT NULL,
    DeprecationReason VARCHAR(255),
    BoCodeVersion VARCHAR(255) NOT NULL,
    SourceSystemCode VARCHAR(255) NOT NULL,
    SourceSystemRecordId VARCHAR(255),
    DataQualityScore DECIMAL(5,2),
    DataClassificationLevel VARCHAR(255) NOT NULL,
    GdprRelevantFlag BIT NOT NULL,
    SupportedRegionCodes VARCHAR(MAX),
    ServiceLevelAgreementTier VARCHAR(255),
    ProcessingMode VARCHAR(255) NOT NULL,
    StreamingEnabledFlag BIT NOT NULL,
    HistoricalDataRetentionYears INT,
    BoCodeStatus VARCHAR(255) NOT NULL,
    AuthoritativeSourceFlag BIT NOT NULL,
    BusinessOwnerContactEmail VARCHAR(320),
    TechnicalOwnerContactEmail VARCHAR(320),
    LoadedAt DATETIME2,
    SourceSystem VARCHAR(255)
    ,CONSTRAINT PK_FinanceBOCodes PRIMARY KEY (Id)
);


-- Dataset: GDS71216

-- This partner dataset supports finance office operations. Key applications include data analysis, rep
CREATE TABLE [DataedoCRDM].[DepositFlowAnalysis] (
    Id INT NOT NULL,
    DatasetRecordId UNIQUEIDENTIFIER NOT NULL,
    PartnerSourceSystemId VARCHAR(255) NOT NULL,
    DepositFlowRecordId VARCHAR(255) NOT NULL,
    AccountId VARCHAR(255) NOT NULL,
    AccountNumberMasked VARCHAR(255) NOT NULL,
    Iban VARCHAR(34),
    BicSwiftCode VARCHAR(255),
    CustomerSegmentCode VARCHAR(255),
    ProductTypeCode VARCHAR(255) NOT NULL,
    DepositFlowDirection VARCHAR(255) NOT NULL,
    TransactionTypeCode VARCHAR(255) NOT NULL,
    TransactionChannelCode VARCHAR(255),
    BookingDate DATE NOT NULL,
    ValueDate DATE,
    TransactionTimestamp DATETIME2 NOT NULL,
    ReportingCurrencyCode VARCHAR(255) NOT NULL,
    TransactionAmountReportingCcy DECIMAL(18,2) NOT NULL,
    TransactionAmountAccountCcy DECIMAL(18,2) NOT NULL,
    ExchangeRateApplied DECIMAL(12,6),
    RunningAccountBalance DECIMAL(20,2),
    IsIntragroupFlow BIT NOT NULL,
    IsHighValueTransaction BIT NOT NULL,
    LiquidityBucketCode VARCHAR(255),
    RegulatoryReportingFlag BIT,
    EconomicPurposeCode VARCHAR(255),
    CounterpartyBankName VARCHAR(255),
    CounterpartyCountryCode VARCHAR(255),
    CounterpartyRiskRating VARCHAR(255),
    InternalTradeId VARCHAR(255),
    BatchId VARCHAR(255),
    ProcessingStatusCode VARCHAR(255) NOT NULL,
    ProcessingTimestamp DATETIME2 NOT NULL,
    ReversalIndicator BIT NOT NULL,
    OriginalTransactionId VARCHAR(255),
    InterestRateApplied DECIMAL(7,5),
    FeeAmountReportingCcy DECIMAL(18,2),
    CashFlowClassificationCode VARCHAR(255),
    OperationalRiskEventFlag BIT,
    AmlAlertFlag BIT,
    DataQualityScore INT NOT NULL,
    RecordEffectiveDate DATE NOT NULL,
    RecordExpiryDate DATE,
    IngestionTimestamp DATETIME2 NOT NULL,
    SourceRecordHash VARCHAR(255) NOT NULL,
    LineageMetadata VARCHAR(MAX),
    TagsArray VARCHAR(MAX),
    LoadedAt DATETIME2,
    SourceSystem VARCHAR(255)
    ,CONSTRAINT PK_DepositFlowAnalysis PRIMARY KEY (Id)
);


-- Dataset: GDS71530

-- This partner dataset supports finance office operations. Key applications include data analysis, rep
CREATE TABLE [DataedoCRDM].[BlockedAccountReasonsDataset] (
    Id INT NOT NULL,
    BlockedReasonRecordId UNIQUEIDENTIFIER NOT NULL,
    PartnerId VARCHAR(255) NOT NULL,
    PartnerAccountId VARCHAR(255) NOT NULL,
    Iban VARCHAR(34),
    BlockReasonCode VARCHAR(255) NOT NULL,
    BlockReasonDescription VARCHAR(255) NOT NULL,
    BlockSubreasonCode VARCHAR(255),
    BlockCategory VARCHAR(255) NOT NULL,
    FraudSuspicionFlag BIT NOT NULL,
    FraudRiskScore DECIMAL(5,2),
    AmlRiskRating VARCHAR(255),
    BlockInitiationTimestamp DATETIME2 NOT NULL,
    BlockEffectiveDate DATE NOT NULL,
    BlockReleaseTimestamp DATETIME2,
    BlockStatus VARCHAR(255) NOT NULL,
    BlockSourceSystem VARCHAR(255) NOT NULL,
    BlockInitiatorType VARCHAR(255) NOT NULL,
    BlockInitiatorId VARCHAR(255),
    RegulatoryBlockFlag BIT NOT NULL,
    RegulatoryReferenceNumber VARCHAR(255),
    CurrencyCode VARCHAR(255),
    BlockedBalanceAmount DECIMAL(18,2),
    AvailableBalanceAmount DECIMAL(18,2),
    BlockDurationHours DECIMAL(10,2),
    CustomerSegment VARCHAR(255),
    CountryOfAccount VARCHAR(255) NOT NULL,
    CustomerRiskProfile VARCHAR(255),
    PreviousBlocksCount INT,
    LinkedCaseId VARCHAR(255),
    TransactionTriggeredFlag BIT NOT NULL,
    TriggerTransactionCount INT,
    TriggerTransactionTotalAmount DECIMAL(18,2),
    SanctionsListSource VARCHAR(255),
    KycDocumentIssueFlag BIT NOT NULL,
    CustomerNotificationSentFlag BIT NOT NULL,
    CustomerNotificationTimestamp DATETIME2,
    InternalComment VARCHAR(255),
    DataCaptureTimestamp DATETIME2 NOT NULL,
    RecordLastUpdatedTimestamp DATETIME2 NOT NULL,
    DataQualityIssues VARCHAR(MAX),
    ProcessingEnvironment VARCHAR(255) NOT NULL,
    StreamIngestionId VARCHAR(255),
    LoadedAt DATETIME2,
    SourceSystem VARCHAR(255)
    ,CONSTRAINT PK_BlockedAccountReason PRIMARY KEY (Id)
);


-- Dataset: GDS73933

-- This client dataset supports innovation & technology operations. Key applications include relationsh
CREATE TABLE [DataedoCRDM].[FinanceActivityRollup] (
    Id INT NOT NULL,
    DatasetRecordId UNIQUEIDENTIFIER NOT NULL,
    ClientEntityId VARCHAR(255) NOT NULL,
    GlobalClientReference VARCHAR(255),
    SourceSystemCode VARCHAR(255) NOT NULL,
    SourceRecordId VARCHAR(255),
    ReportingPeriodStartDate DATE NOT NULL,
    ReportingPeriodEndDate DATE NOT NULL,
    SnapshotTimestamp DATETIME2 NOT NULL,
    ClientLegalName VARCHAR(255) NOT NULL,
    ClientSegmentCode VARCHAR(255),
    ClientIndustryCode VARCHAR(255),
    ClientDomicileCountryCode VARCHAR(255) NOT NULL,
    RelationshipManagerId VARCHAR(255),
    RelationshipManagerName VARCHAR(255),
    PrimaryBusinessUnitCode VARCHAR(255) NOT NULL,
    ClientLifecycleStage VARCHAR(255) NOT NULL,
    ClientRiskRating VARCHAR(255),
    ClientRiskRatingEffectiveDate DATE,
    IsGdprRestricted BIT NOT NULL,
    TotalRelationshipBalanceCcy VARCHAR(255) NOT NULL,
    TotalRelationshipBalanceAmount DECIMAL(18,2),
    TotalDepositBalanceAmount DECIMAL(18,2),
    TotalLoanBalanceAmount DECIMAL(18,2),
    TotalInvestmentMarketValueAmount DECIMAL(18,2),
    TotalDerivativesNotionalAmount DECIMAL(20,2),
    TotalFeeIncomeAmount DECIMAL(18,2),
    TotalInterestIncomeAmount DECIMAL(18,2),
    TotalInterestExpenseAmount DECIMAL(18,2),
    NetRevenueAmount DECIMAL(18,2),
    AllocatedOperatingCostAmount DECIMAL(18,2),
    ClientProfitabilityAmount DECIMAL(18,2),
    TransactionCountTotal INT,
    TransactionCountCrossBorder INT,
    AverageTransactionValueAmount DECIMAL(18,2),
    LastTransactionTimestamp DATETIME2,
    ActiveAccountCount INT,
    ActivePortfolioCount INT,
    PrimaryContactChannel VARCHAR(320),
    LastContactTimestamp DATETIME2,
    CustomerSatisfactionScore DECIMAL(5,2),
    WalletShareEstimatePercent DECIMAL(5,2),
    CrossSellOpportunityScore DECIMAL(6,3),
    DataPrivacyClassification VARCHAR(255) NOT NULL,
    RecordActiveFlag BIT NOT NULL,
    RecordCreationTimestamp DATETIME2 NOT NULL,
    RecordLastUpdateTimestamp DATETIME2 NOT NULL,
    DataQualityScore DECIMAL(5,2),
    LoadedAt DATETIME2,
    SourceSystem VARCHAR(255)
    ,CONSTRAINT PK_FinanceActivityRollu PRIMARY KEY (Id)
);


-- Dataset: GDS84852

-- This finance dataset supports finance office operations. Key applications include data analysis, rep
CREATE TABLE [DataedoCRDM].[IFRSFinanceElectionDataset] (
    Id INT NOT NULL,
    DatasetRecordId UNIQUEIDENTIFIER NOT NULL,
    SourceSystemCode VARCHAR(255) NOT NULL,
    LegalEntityId VARCHAR(255) NOT NULL,
    LegalEntityName VARCHAR(255) NOT NULL,
    ReportingCurrencyCode VARCHAR(255) NOT NULL,
    FunctionalCurrencyCode VARCHAR(255) NOT NULL,
    IfrsStandardCode VARCHAR(255) NOT NULL,
    IfrsStandardName VARCHAR(255) NOT NULL,
    AccountingPolicyElectionId VARCHAR(255) NOT NULL,
    AccountingPolicyElectionName VARCHAR(255) NOT NULL,
    AccountingPolicyElectionDescription VARCHAR(255),
    ElectionEffectiveDate DATE NOT NULL,
    ElectionEndDate DATE,
    ElectionStatusCode VARCHAR(255) NOT NULL,
    FiscalYear INT NOT NULL,
    FiscalPeriod INT NOT NULL,
    ReportingDate DATE NOT NULL,
    ChartOfAccountsId VARCHAR(255),
    GlAccountNumber VARCHAR(255),
    GlAccountName VARCHAR(255),
    CostCenterCode VARCHAR(255),
    ProductSegmentCode VARCHAR(255),
    BusinessUnitCode VARCHAR(255),
    MeasurementCategoryCode VARCHAR(255),
    MeasurementBasisDescription VARCHAR(255),
    FairValueHierarchyLevel INT,
    RecognitionMethodCode VARCHAR(255),
    RevenueRecognitionPolicyCode VARCHAR(255),
    ImpairmentModelCode VARCHAR(255),
    DiscountRateMethodCode VARCHAR(255),
    PresentationClassificationCode VARCHAR(255),
    ConsolidationMethodCode VARCHAR(255),
    LeaseClassificationCode VARCHAR(255),
    EffectiveInterestRate DECIMAL(7,4),
    CarryingAmountReportingCcy DECIMAL(20,2),
    FairValueReportingCcy DECIMAL(20,2),
    PriorPeriodCarryingAmountReportingCcy DECIMAL(20,2),
    AdjustmentAmountReportingCcy DECIMAL(20,2),
    DisclosureRequiredFlag BIT NOT NULL,
    LastUpdatedTimestamp DATETIME2 NOT NULL,
    CreatedTimestamp DATETIME2 NOT NULL,
    CreatedByUserId VARCHAR(255) NOT NULL,
    LastUpdatedByUserId VARCHAR(255) NOT NULL,
    DataQualityStatusCode VARCHAR(255) NOT NULL,
    LoadedAt DATETIME2,
    SourceSystem VARCHAR(255)
    ,CONSTRAINT PK_IFRSFinanceElectionD PRIMARY KEY (Id)
);


-- Dataset: GDS92316

-- This partner dataset supports innovation & technology operations. Key applications include data anal
CREATE TABLE [DataedoCRDM].[FinanceProductCatalog] (
    Id INT NOT NULL,
    ProductId UNIQUEIDENTIFIER NOT NULL,
    PartnerId VARCHAR(255) NOT NULL,
    ProductCode VARCHAR(255) NOT NULL,
    ProductName VARCHAR(255) NOT NULL,
    ProductType VARCHAR(255) NOT NULL,
    ProductSubType VARCHAR(255),
    ProductDescription VARCHAR(255),
    CurrencyCode VARCHAR(255) NOT NULL,
    MinimumEligibilityScore INT,
    MinimumAnnualRevenue DECIMAL(18,2),
    MinimumAccountTenureMonths INT,
    BaseInterestRate DECIMAL(5,3),
    InterestRateType VARCHAR(255),
    ReferenceRateIndex VARCHAR(255),
    AnnualFeeAmount DECIMAL(15,2),
    SetupFeeAmount DECIMAL(15,2),
    EarlyTerminationFeeAmount DECIMAL(15,2),
    MinimumBalanceAmount DECIMAL(18,2),
    MaximumCreditLimit DECIMAL(18,2),
    TenorMonths INT,
    ProductStatus VARCHAR(255) NOT NULL,
    EffectiveStartDate DATE NOT NULL,
    EffectiveEndDate DATE,
    LastUpdatedTimestamp DATETIME2 NOT NULL,
    CreatedTimestamp DATETIME2 NOT NULL,
    RegionCoverage VARCHAR(MAX),
    TargetIndustrySectors VARCHAR(MAX),
    ChannelAvailability VARCHAR(MAX),
    RequiresPersonalData BIT NOT NULL,
    RequiresMarketingConsent BIT NOT NULL,
    GdprProcessingBasis VARCHAR(255),
    ProductOwnerDepartment VARCHAR(255) NOT NULL,
    RiskRating VARCHAR(255),
    KpiPrimaryMetric VARCHAR(255),
    IsRealTimeEnabled BIT NOT NULL,
    SupportsStreamingData BIT NOT NULL,
    ApiProductSlug VARCHAR(255),
    PartnerVisibilityLevel VARCHAR(255) NOT NULL,
    CustomerSegment VARCHAR(255),
    RegulatoryClassification VARCHAR(255),
    LocalizedMarketingName VARCHAR(255),
    AdditionalConfiguration VARCHAR(MAX),
    LoadedAt DATETIME2,
    SourceSystem VARCHAR(255)
    ,CONSTRAINT PK_FinanceProductCatalo PRIMARY KEY (Id)
);


-- Dataset: GDS92585

-- This partner dataset supports finance office operations. Key applications include data analysis, rep
CREATE TABLE [DataedoCRDM].[LeaseDynamicsDataset] (
    Id INT NOT NULL,
    LeaseContractId VARCHAR(255) NOT NULL,
    PartnerOrganizationId VARCHAR(255) NOT NULL,
    LesseeCorporateId VARCHAR(255) NOT NULL,
    LeasePortfolioId VARCHAR(255) NOT NULL,
    ProductTypeCode VARCHAR(255) NOT NULL,
    AssetCategory VARCHAR(255) NOT NULL,
    AssetDescription VARCHAR(255),
    AssetCountryCode VARCHAR(255) NOT NULL,
    OriginationChannel VARCHAR(255),
    LeaseStartDate DATE NOT NULL,
    LeaseEndDate DATE,
    FirstPaymentDate DATE,
    LeaseMaturityDate DATE,
    OriginationTimestamp DATETIME2 NOT NULL,
    ContractCurrencyCode VARCHAR(255) NOT NULL,
    OriginalPrincipalAmount DECIMAL(18,2) NOT NULL,
    OutstandingPrincipalAmount DECIMAL(18,2) NOT NULL,
    EffectiveInterestRate DECIMAL(7,4) NOT NULL,
    PaymentFrequencyCode VARCHAR(255) NOT NULL,
    ScheduledPaymentAmount DECIMAL(18,2),
    LastPaymentDate DATE,
    DaysPastDue INT NOT NULL,
    NonAccrualFlag BIT NOT NULL,
    ImpairmentStatusCode VARCHAR(255) NOT NULL,
    ImpairmentAmount DECIMAL(18,2) NOT NULL,
    WriteOffAmount DECIMAL(18,2) NOT NULL,
    LeaseStatusCode VARCHAR(255) NOT NULL,
    RestructuringFlag BIT NOT NULL,
    EarlyTerminationFlag BIT NOT NULL,
    ResidualValueGuaranteedAmount DECIMAL(18,2),
    CollateralValuationAmount DECIMAL(18,2),
    InternalRatingGrade VARCHAR(255),
    ExternalRatingAgency VARCHAR(255),
    ExpectedLossRate DECIMAL(9,6) NOT NULL,
    EclStageCode VARCHAR(255) NOT NULL,
    ReportingEntityLegalName VARCHAR(255) NOT NULL,
    DataSourceSystemCode VARCHAR(255) NOT NULL,
    RecordLastUpdatedTimestamp DATETIME2 NOT NULL,
    LoadedAt DATETIME2,
    SourceSystem VARCHAR(255)
    ,CONSTRAINT PK_LeaseDynamicsDataset PRIMARY KEY (Id)
);


