-- ============================================
-- Platform: ORACLE
-- Schema/Source: BOARD_OF_TRADE
-- Generated: 2026-03-18T12:18:16.773739
-- Datasets: 1
-- ============================================

-- Dataset: GDS14806
-- Schema: BOARD_OF_TRADE

-- This client dataset supports commercial finance operations. Key applications include relationship ma
CREATE TABLE BOARD_OF_TRADE.LOCATION_FINANCE_INSIGHTS (
    ID NUMBER(18,0) NOT NULL,
    CLIENT_LOCATION_FINANCE_ID RAW(16) NOT NULL,
    MASREPH_CLIENT_ID VARCHAR2(255) NOT NULL,
    GLOBAL_CLIENT_ID VARCHAR2(255),
    LEGAL_ENTITY_NAME VARCHAR2(255) NOT NULL,
    CLIENT_SEGMENT_CODE VARCHAR2(255) NOT NULL,
    CLIENT_SEGMENT_DESCRIPTION VARCHAR2(255),
    COUNTRY_ISO_CODE VARCHAR2(255) NOT NULL,
    REGION_NAME VARCHAR2(255),
    CITY_NAME VARCHAR2(255),
    POSTAL_CODE VARCHAR2(255),
    LATITUDE NUMBER(9,6),
    LONGITUDE NUMBER(9,6),
    RELATIONSHIP_MANAGER_ID VARCHAR2(255),
    RELATIONSHIP_MANAGER_NAME VARCHAR2(255),
    PRIMARY_BRANCH_ID VARCHAR2(255),
    PRIMARY_BRANCH_NAME VARCHAR2(255),
    RELATIONSHIP_START_DATE DATE NOT NULL,
    RELATIONSHIP_END_DATE DATE,
    IS_ACTIVE_RELATIONSHIP NUMBER(1) NOT NULL,
    CLIENT_ONBOARD_DATE DATE,
    CLIENT_OFFBOARD_REASON VARCHAR2(255),
    ANNUAL_REVENUE_EUR NUMBER(18,2),
    CREDIT_EXPOSURE_EUR NUMBER(18,2) NOT NULL,
    OUTSTANDING_LOAN_BALANCE_EUR NUMBER(18,2) NOT NULL,
    DEPOSIT_BALANCE_EUR NUMBER(18,2) NOT NULL,
    FEE_INCOME_YTD_EUR NUMBER(18,2) NOT NULL,
    INTEREST_INCOME_YTD_EUR NUMBER(18,2) NOT NULL,
    INTEREST_EXPENSE_YTD_EUR NUMBER(18,2) NOT NULL,
    PROFITABILITY_SCORE NUMBER(5,2) NOT NULL,
    RISK_RATING_INTERNAL VARCHAR2(255) NOT NULL,
    PROBABILITY_OF_DEFAULT_PCT NUMBER(6,4) NOT NULL,
    CLIENT_TIMEZONE VARCHAR2(255),
    DATA_SOURCE_SYSTEM VARCHAR2(255) NOT NULL,
    RECORD_EFFECTIVE_TIMESTAMP TIMESTAMP NOT NULL,
    RECORD_EXPIRY_TIMESTAMP TIMESTAMP,
    IS_CURRENT_RECORD NUMBER(1) NOT NULL,
    LAST_INTERACTION_TIMESTAMP TIMESTAMP,
    LAST_INTERACTION_CHANNEL VARCHAR2(255),
    INTERACTION_FREQUENCY_90D NUMBER(18,0) NOT NULL,
    PRODUCTS_HELD_COUNT NUMBER(18,0) NOT NULL,
    PRIMARY_INDUSTRY_CODE_NACE VARCHAR2(255),
    PRIMARY_INDUSTRY_DESCRIPTION VARCHAR2(255),
    GEO_RISK_SCORE NUMBER(5,2),
    CROSS_SELL_OPPORTUNITY_FLAG NUMBER(1) NOT NULL,
    CROSS_SELL_OPPORTUNITY_SCORE NUMBER(5,2),
    SERVICE_ISSUE_FLAG NUMBER(1) NOT NULL,
    SERVICE_ISSUE_COUNT_12M NUMBER(18,0) NOT NULL,
    GDPR_CONSENT_FLAG NUMBER(1) NOT NULL,
    LOCATION_ACCURACY_CODE VARCHAR2(255),
    DATA_QUALITY_SCORE NUMBER(5,2),
    SYS_CR_DT TIMESTAMP,
    SYS_UPD_DT TIMESTAMP
    ,CONSTRAINT PK_LOCATION_FINANCE_INS PRIMARY KEY (ID)
);


