-- ============================================
-- Platform: ORACLE
-- Schema/Source: ECD_ORACLE
-- Generated: 2026-03-18T12:18:16.776094
-- Datasets: 1
-- ============================================

-- Dataset: GDS26230
-- Schema: ECD_ORACLE

-- This client dataset supports innovation & technology operations. Key applications include relationsh
CREATE TABLE ECD_ORACLE.FINANCE360_COMPANY_INSIGHTS (
    ID NUMBER(18,0) NOT NULL,
    COMPANY_INSIGHT_ID RAW(16) NOT NULL,
    CORE_CLIENT_ID VARCHAR2(255) NOT NULL,
    EXTERNAL_COMPANY_REFERENCE VARCHAR2(255),
    LEGAL_ENTITY_IDENTIFIER VARCHAR2(255),
    COMPANY_LEGAL_NAME VARCHAR2(255) NOT NULL,
    COMPANY_TRADING_NAME VARCHAR2(255),
    INDUSTRY_SECTOR_CODE VARCHAR2(255) NOT NULL,
    INDUSTRY_SECTOR_DESCRIPTION VARCHAR2(255) NOT NULL,
    GLOBAL_ULTIMATE_PARENT_ID VARCHAR2(255),
    COUNTRY_OF_INCORPORATION VARCHAR2(255) NOT NULL,
    PRIMARY_OPERATING_COUNTRY VARCHAR2(255),
    COMPANY_STATUS VARCHAR2(255) NOT NULL,
    ONBOARDING_DATE DATE,
    LAST_RELATIONSHIP_REVIEW_DATE DATE,
    NEXT_REVIEW_DUE_DATE DATE,
    PRIMARY_RELATIONSHIP_MANAGER_I VARCHAR2(255),
    RELATIONSHIP_SEGMENT_CODE VARCHAR2(255) NOT NULL,
    INNOVATION_FOCUS_FLAG NUMBER(1) NOT NULL,
    ANNUAL_REVENUE_AMOUNT NUMBER(18,2),
    ANNUAL_EBITDA_MARGIN_PERCENT NUMBER(5,2),
    CREDIT_EXPOSURE_EAD_AMOUNT NUMBER(20,2),
    RISK_RATING_INTERNAL_GRADE VARCHAR2(255),
    CLIENT_PROFITABILITY_ROLLING_1 NUMBER(18,2),
    WALLET_SHARE_ESTIMATE_PERCENT NUMBER(5,2),
    CROSS_SELL_OPPORTUNITY_SCORE NUMBER(18,0),
    CLIENT_TIER_CODE VARCHAR2(255),
    MARKETING_CONSENT_FLAG NUMBER(1) NOT NULL,
    GDPR_PROCESSING_LEGAL_BASIS VARCHAR2(255),
    PRIMARY_CONTACT_EMAIL VARCHAR2(320),
    PRIMARY_CONTACT_PHONE VARCHAR2(255),
    HEAD_OFFICE_CITY VARCHAR2(255),
    HEAD_OFFICE_COUNTRY VARCHAR2(255),
    DIGITAL_ENGAGEMENT_SCORE NUMBER(18,0),
    INNOVATION_PROGRAM_PARTICIPATI NUMBER(1) NOT NULL,
    LAST_INTERACTION_TIMESTAMP TIMESTAMP,
    INTERACTION_FREQUENCY_90D NUMBER(18,0),
    PRIMARY_BANKING_RELATIONSHIP_F NUMBER(1),
    ESG_RISK_SCORE NUMBER(5,2),
    FX_REPORTING_CURRENCY_CODE VARCHAR2(255) NOT NULL,
    ACTIVE_PRODUCT_CATEGORIES CLOB,
    DATA_SENSITIVITY_CLASSIFICATIO VARCHAR2(255) NOT NULL,
    CLIENT_CONSENT_METADATA CLOB,
    DATA_LAST_REFRESHED_TIMESTAMP TIMESTAMP NOT NULL,
    DATA_SOURCE_SYSTEM_CODE VARCHAR2(255) NOT NULL,
    RECORD_ACTIVE_FLAG NUMBER(1) NOT NULL,
    SYS_CR_DT TIMESTAMP,
    SYS_UPD_DT TIMESTAMP
    ,CONSTRAINT PK_FINANCE360_COMPANY_I PRIMARY KEY (ID)
);


