-- ============================================
-- Platform: ORACLE
-- Schema/Source: ECD_ORCL
-- Generated: 2026-03-18T11:59:44.553940
-- Datasets: 1
-- ============================================

-- Dataset: GDS26230
-- Schema: ECD_ORCL

-- Master table for Finance360 Company Insights, storing financial, relationship, and innovation-relate
CREATE TABLE ECD_ORCL.F360_CMPNY_INSGHT_MSTR (
    CMPNY_INSGHT_ID VARCHAR2(255) NOT NULL,
    CORE_CUST_ID VARCHAR2(255) NOT NULL,
    EXT_CMPNY_REF VARCHAR2(255),
    LEGL_ENT_ID VARCHAR2(255),
    CMPNY_LEGL_NM VARCHAR2(255) NOT NULL,
    CMPNY_TRD_NM VARCHAR2(255),
    INDS_SECTR_CD VARCHAR2(255) NOT NULL,
    INDS_SECTR_DESC VARCHAR2(255) NOT NULL,
    GLBL_ULT_PRNT_ID VARCHAR2(255),
    INCORP_CNTRY_CD VARCHAR2(255) NOT NULL,
    PRIM_OPER_CNTRY_CD VARCHAR2(255),
    CMPNY_STAT_CD VARCHAR2(255) NOT NULL,
    ONBOARD_DT DATE,
    LAST_RLTNSHP_REVW_DT DATE,
    NEXT_REVW_DUE_DT DATE,
    PRIM_RLNSHP_MGR_ID VARCHAR2(255),
    RLTNSHP_SGMT_CD VARCHAR2(255) NOT NULL,
    INNOV_FOCUS_FLG NUMBER(1) NOT NULL,
    ANN_REV_AMT NUMBER(18,4),
    ANN_EBITDA_MARG_PCT NUMBER(18,4),
    CRDT_EXP_EAD_AMT NUMBER(18,4),
    RISK_RTNG_INT_GRD VARCHAR2(255),
    CLNT_PROFT_R12M_AMT NUMBER(18,4),
    WLLT_SHARE_EST_PCT NUMBER(18,4),
    CRS_SELL_OPPTY_SCR NUMBER(18,0),
    CLNT_TIER_CD VARCHAR2(255),
    MRKT_CONSENT_FLG NUMBER(1) NOT NULL,
    GDPR_PROC_LEGAL_BASIS VARCHAR2(255),
    PRIM_CNTCT_EMAIL VARCHAR2(255),
    PRIM_CNTCT_PHONE VARCHAR2(255),
    HD_OFFICE_CITY VARCHAR2(255),
    HD_OFFICE_CNTRY_CD VARCHAR2(255),
    DIG_ENGMT_SCR NUMBER(18,0),
    INNOV_PROG_PART_FLG NUMBER(1) NOT NULL,
    LAST_INTRCTN_TS TIMESTAMP,
    INTRCTN_FREQ_90D NUMBER(18,0),
    PRIM_BANK_RLTNSHP_FLG NUMBER(1),
    ESG_RISK_SCR NUMBER(18,4),
    FX_REP_CCY_CD VARCHAR2(255) NOT NULL,
    ACTV_PROD_CATS_JSON CLOB,
    DATA_SENS_CLASS_CD VARCHAR2(255) NOT NULL,
    CLNT_CONSENT_META_JSON CLOB,
    DATA_LAST_REFRSH_TS TIMESTAMP NOT NULL,
    DATA_SRC_SYSTM_CD VARCHAR2(255) NOT NULL,
    RECORD_ACTV_FLG NUMBER(1) NOT NULL,
    SYS_CR_DT DATE NOT NULL,
    SYS_UPD_DT DATE NOT NULL
    ,CONSTRAINT PK_F360_CMPNY_INSGHT_MS PRIMARY KEY (CMPNY_INSGHT_ID)
);


