-- ============================================
-- Platform: ORACLE
-- Schema/Source: GOVPILOT
-- Generated: 2026-03-18T12:18:16.774739
-- Datasets: 1
-- ============================================

-- Dataset: GDS19695
-- Schema: GOVPILOT

-- This risk management dataset supports leasing operations. Key applications include data analysis, re
CREATE TABLE GOVPILOT.RISKWATCH_FINANCE_DATASET (
    ID NUMBER(18,0) NOT NULL,
    CONTRACT_ID VARCHAR2(255) NOT NULL,
    LESSEE_PARTY_ID VARCHAR2(255) NOT NULL,
    LESSEE_NAME VARCHAR2(255) NOT NULL,
    LESSEE_SEGMENT VARCHAR2(255) NOT NULL,
    LESSEE_COUNTRY_CODE VARCHAR2(255) NOT NULL,
    ASSET_ID VARCHAR2(255) NOT NULL,
    ASSET_TYPE VARCHAR2(255) NOT NULL,
    ASSET_INDUSTRY_CODE VARCHAR2(255),
    CONTRACT_CURRENCY VARCHAR2(255) NOT NULL,
    LEASE_START_DATE DATE NOT NULL,
    LEASE_END_DATE DATE NOT NULL,
    BOOKING_DATE DATE NOT NULL,
    LAST_UPDATE_TIMESTAMP TIMESTAMP NOT NULL,
    ORIGINAL_LEASE_AMOUNT NUMBER(15,2) NOT NULL,
    CURRENT_OUTSTANDING_AMOUNT NUMBER(15,2) NOT NULL,
    UNDRAWN_COMMITMENT_AMOUNT NUMBER(15,2),
    INTEREST_RATE_TYPE VARCHAR2(255) NOT NULL,
    INTEREST_RATE_VALUE NUMBER(7,4) NOT NULL,
    INTEREST_RATE_INDEX VARCHAR2(255),
    PAYMENT_FREQUENCY VARCHAR2(255) NOT NULL,
    DAYS_PAST_DUE NUMBER(18,0) NOT NULL,
    NON_PERFORMING_FLAG NUMBER(1) NOT NULL,
    DEFAULT_FLAG NUMBER(1) NOT NULL,
    DEFAULT_DATE DATE,
    FORBEARANCE_FLAG NUMBER(1) NOT NULL,
    RESTRUCTURED_FLAG NUMBER(1) NOT NULL,
    COLLATERAL_VALUATION_AMOUNT NUMBER(15,2),
    COLLATERAL_VALUATION_DATE DATE,
    LTV_RATIO_CURRENT NUMBER(7,4),
    INTERNAL_RATING_GRADE VARCHAR2(255),
    PROBABILITY_OF_DEFAULT_12M NUMBER(6,5),
    LOSS_GIVEN_DEFAULT NUMBER(5,4),
    EXPOSURE_AT_DEFAULT NUMBER(15,2),
    STAGE_CLASSIFICATION_IFRS9 VARCHAR2(255),
    EXPECTED_CREDIT_LOSS_LIFETIME NUMBER(15,2),
    MACROECONOMIC_SCENARIO_SET VARCHAR2(255),
    RISK_REPORTING_REGION VARCHAR2(255) NOT NULL,
    PRODUCT_CODE VARCHAR2(255) NOT NULL,
    PRODUCT_CATEGORY VARCHAR2(255) NOT NULL,
    ORIGINATION_CHANNEL VARCHAR2(255),
    COVENANT_BREACH_FLAG NUMBER(1) NOT NULL,
    RISK_FLAGS CLOB,
    GDPR_PERSONAL_DATA_FLAG NUMBER(1) NOT NULL,
    STREAM_EVENT_ID RAW(16) NOT NULL,
    DATA_SOURCE_SYSTEM VARCHAR2(255) NOT NULL,
    DATA_QUALITY_SCORE NUMBER(4,2),
    CONTRACT_STATUS VARCHAR2(255) NOT NULL,
    NEXT_PAYMENT_DUE_DATE DATE,
    NEXT_PAYMENT_AMOUNT NUMBER(15,2),
    LEASE_RESIDUAL_VALUE_GUARANTEE NUMBER(15,2),
    COVENANT_DETAILS CLOB,
    SYS_CR_DT TIMESTAMP,
    SYS_UPD_DT TIMESTAMP
    ,CONSTRAINT PK_RISKWATCH_FINANCE_DA PRIMARY KEY (ID)
);


