-- ============================================
-- Platform: ORACLE
-- Schema/Source: IRONCLAD_DIGITAL
-- Generated: 2026-03-18T12:18:16.768740
-- Datasets: 5
-- ============================================

-- Dataset: GDS51041
-- Schema: IRONCLAD_DIGITAL

-- This it dataset supports leasing operations. Key applications include data analysis, reporting, busi
CREATE TABLE IRONCLAD_DIGITAL.DIGITAL_FINANCE_AUTHORIZATION_ (
    ID NUMBER(18,0) NOT NULL,
    AUTHORIZATION_ID RAW(16) NOT NULL,
    MASREPH_CUSTOMER_PSEUDO_ID VARCHAR2(255) NOT NULL,
    LEASING_CONTRACT_ID VARCHAR2(255),
    TRANSACTION_AMOUNT NUMBER(15,2) NOT NULL,
    TRANSACTION_CURRENCY VARCHAR2(255) NOT NULL,
    AUTHORIZATION_TIMESTAMP TIMESTAMP NOT NULL,
    AUTHORIZATION_STATUS VARCHAR2(255) NOT NULL,
    CHANNEL_TYPE VARCHAR2(255),
    DEVICE_FINGERPRINT VARCHAR2(255),
    STRONG_CUSTOMER_AUTH_APPLIED NUMBER(1) NOT NULL,
    CONSENT_SCOPE_LIST CLOB,
    SYS_CR_DT TIMESTAMP,
    SYS_UPD_DT TIMESTAMP
    ,CONSTRAINT PK_DIGITAL_FINANCE_AUTH PRIMARY KEY (ID)
);


-- Dataset: GDS29236
-- Schema: IRONCLAD_DIGITAL

-- This it dataset supports commercial finance operations. Key applications include data analysis, repo
CREATE TABLE IRONCLAD_DIGITAL.DIGITAL_FINANCE_AUTHORIZATION_ (
    ID NUMBER(18,0) NOT NULL,
    TRANSACTION_ID RAW(16) NOT NULL,
    AUTHORIZATION_ID VARCHAR2(255) NOT NULL,
    MASREPH_CUSTOMER_ID VARCHAR2(255) NOT NULL,
    CORPORATE_CLIENT_ID VARCHAR2(255),
    CHANNEL_TYPE VARCHAR2(255) NOT NULL,
    API_CLIENT_ID VARCHAR2(255),
    API_KEY_ID VARCHAR2(255),
    DEVICE_ID VARCHAR2(255),
    SESSION_ID VARCHAR2(255),
    USER_AGENT VARCHAR2(255),
    IP_ADDRESS VARCHAR2(255),
    AUTH_TIMESTAMP TIMESTAMP NOT NULL,
    TRANSACTION_AMOUNT NUMBER(18,2) NOT NULL,
    TRANSACTION_CURRENCY VARCHAR2(255) NOT NULL,
    MERCHANT_CATEGORY_CODE VARCHAR2(255),
    AUTHORIZATION_STATUS VARCHAR2(255) NOT NULL,
    AUTHORIZATION_RESULT_CODE VARCHAR2(255),
    RISK_SCORE NUMBER(5,2),
    RISK_FLAGGED NUMBER(1) NOT NULL,
    COUNTRY_CODE VARCHAR2(255),
    IBAN VARCHAR2(34),
    BIC_SWIFT VARCHAR2(255),
    COUNTERPARTY_NAME VARCHAR2(255),
    LOAN_ACCOUNT_ID VARCHAR2(255),
    FACILITY_ID VARCHAR2(255),
    PRODUCT_TYPE VARCHAR2(255),
    REPAYMENT_TERM_MONTHS NUMBER(18,0),
    INTEREST_RATE NUMBER(7,4),
    CREDIT_LIMIT_AMOUNT NUMBER(18,2),
    AVAILABLE_CREDIT_AMOUNT NUMBER(18,2),
    AUTH_METHOD VARCHAR2(255),
    MULTI_FACTOR_USED NUMBER(1) NOT NULL,
    CONSENT_CAPTURED_FLAG NUMBER(1) NOT NULL,
    CONSENT_TIMESTAMP TIMESTAMP,
    FAILURE_REASON VARCHAR2(255),
    REVERSAL_FLAG NUMBER(1) NOT NULL,
    CREATED_TIMESTAMP TIMESTAMP NOT NULL,
    LAST_UPDATED_TIMESTAMP TIMESTAMP NOT NULL,
    DATA_SOURCE_SYSTEM VARCHAR2(255) NOT NULL,
    GDPR_COMPLIANCE_FLAG NUMBER(1) NOT NULL,
    SYS_CR_DT TIMESTAMP,
    SYS_UPD_DT TIMESTAMP
    ,CONSTRAINT PK_DIGITAL_FINANCE_AUTH PRIMARY KEY (ID)
);


-- Dataset: GDS78390
-- Schema: IRONCLAD_DIGITAL

-- This it dataset supports leasing operations. Key applications include data analysis, reporting, busi
CREATE TABLE IRONCLAD_DIGITAL.DIGITAL_FINANCE_AUTHORIZATION_ (
    ID NUMBER(18,0) NOT NULL,
    AUTHORIZATION_ID RAW(16) NOT NULL,
    TRANSACTION_ID VARCHAR2(255) NOT NULL,
    LEASE_CONTRACT_ID VARCHAR2(255),
    CUSTOMER_ID VARCHAR2(255) NOT NULL,
    MASREPH_PARTY_ID VARCHAR2(255),
    CHANNEL_ID VARCHAR2(255) NOT NULL,
    API_CLIENT_ID VARCHAR2(255),
    DEVICE_ID VARCHAR2(255),
    SESSION_ID VARCHAR2(255),
    AUTHORIZATION_TIMESTAMP TIMESTAMP NOT NULL,
    TRANSACTION_AMOUNT NUMBER(15,2) NOT NULL,
    TRANSACTION_CURRENCY_CODE VARCHAR2(255) NOT NULL,
    MERCHANT_CATEGORY_CODE VARCHAR2(255),
    MERCHANT_NAME VARCHAR2(255),
    AUTHORIZATION_STATUS VARCHAR2(255) NOT NULL,
    AUTHORIZATION_RESULT_CODE VARCHAR2(255),
    DECLINE_REASON_CODE VARCHAR2(255),
    LEASE_ASSET_TYPE VARCHAR2(255),
    LEASE_ASSET_DESCRIPTION VARCHAR2(255),
    COUNTRY_CODE VARCHAR2(255) NOT NULL,
    CUSTOMER_SEGMENT VARCHAR2(255),
    CUSTOMER_AGE NUMBER(18,0),
    CUSTOMER_RESIDENCY_STATUS VARCHAR2(255),
    KYC_VERIFICATION_LEVEL VARCHAR2(255),
    RISK_SCORE NUMBER(5,2),
    FRAUD_SCREENING_RESULT VARCHAR2(255),
    FRAUD_RULE_TRIGGERED_LIST CLOB,
    AUTHENTICATION_METHOD VARCHAR2(255),
    AUTHENTICATION_RESULT VARCHAR2(255),
    IP_ADDRESS VARCHAR2(255),
    GEO_LOCATION CLOB,
    USER_AGENT VARCHAR2(255),
    RECURRING_PAYMENT_FLAG NUMBER(1) NOT NULL,
    RECURRING_PAYMENT_SEQUENCE_NUM NUMBER(18,0),
    ORIGINAL_AUTHORIZATION_ID RAW(16),
    PARTIAL_CAPTURE_ALLOWED_FLAG NUMBER(1) NOT NULL,
    CAPTURE_STATUS VARCHAR2(255),
    REVERSAL_FLAG NUMBER(1) NOT NULL,
    CHARGEBACK_FLAG NUMBER(1) NOT NULL,
    CHARGEBACK_REASON_CODE VARCHAR2(255),
    PROCESSING_TIMESTAMP TIMESTAMP NOT NULL,
    SETTLEMENT_DATE DATE,
    RESPONSE_TIME_MS NUMBER(18,0) NOT NULL,
    API_VERSION VARCHAR2(255) NOT NULL,
    CONSENT_REFERENCE_ID VARCHAR2(255),
    DATA_SHARING_CONSENT_FLAG NUMBER(1) NOT NULL,
    RECORD_CREATE_TIMESTAMP TIMESTAMP NOT NULL,
    RECORD_UPDATE_TIMESTAMP TIMESTAMP,
    SYS_CR_DT TIMESTAMP,
    SYS_UPD_DT TIMESTAMP
    ,CONSTRAINT PK_DIGITAL_FINANCE_AUTH PRIMARY KEY (ID)
);


-- Dataset: GDS82266
-- Schema: IRONCLAD_DIGITAL

-- This it dataset supports consumer finance operations. Key applications include data analysis, report
CREATE TABLE IRONCLAD_DIGITAL.DIGITAL_FINANCE_AUTHORIZATION_ (
    ID NUMBER(18,0) NOT NULL,
    AUTHORIZATION_ID RAW(16) NOT NULL,
    TRANSACTION_ID VARCHAR2(255) NOT NULL,
    CUSTOMER_INTERNAL_ID VARCHAR2(255) NOT NULL,
    PAN_TOKEN VARCHAR2(255) NOT NULL,
    AUTHORIZATION_TIMESTAMP TIMESTAMP NOT NULL,
    AUTHORIZATION_STATUS VARCHAR2(255) NOT NULL,
    AUTHORIZATION_RESPONSE_CODE VARCHAR2(255) NOT NULL,
    AUTHORIZATION_RESPONSE_MESSAGE VARCHAR2(255),
    TRANSACTION_AMOUNT NUMBER(15,2) NOT NULL,
    BILLING_CURRENCY_CODE VARCHAR2(255) NOT NULL,
    TRANSACTION_CURRENCY_CODE VARCHAR2(255) NOT NULL,
    EXCHANGE_RATE_APPLIED NUMBER(12,6),
    MERCHANT_ID VARCHAR2(255),
    MERCHANT_CATEGORY_CODE VARCHAR2(255),
    MERCHANT_COUNTRY_CODE VARCHAR2(255),
    CHANNEL_TYPE VARCHAR2(255) NOT NULL,
    DEVICE_ID VARCHAR2(255),
    IP_ADDRESS VARCHAR2(255),
    USER_AGENT_STRING VARCHAR2(255),
    CUSTOMER_AGE NUMBER(18,0),
    CUSTOMER_RESIDENCY_COUNTRY VARCHAR2(255),
    CUSTOMER_SEGMENT VARCHAR2(255),
    ACCOUNT_IBAN VARCHAR2(34),
    CARD_PRODUCT_TYPE VARCHAR2(255),
    RISK_SCORE NUMBER(5,2),
    RISK_DECISION_CODE VARCHAR2(255),
    STRONG_CUSTOMER_AUTH_APPLIED NUMBER(1) NOT NULL,
    SCA_METHOD VARCHAR2(320),
    CONSENT_ID VARCHAR2(255),
    GDPR_PSEUDONYMIZED NUMBER(1) NOT NULL,
    API_CLIENT_ID VARCHAR2(255),
    LATENCY_MS NUMBER(18,0),
    IS_RECURRING_TRANSACTION NUMBER(1) NOT NULL,
    ORIGINAL_AUTH_ID RAW(16),
    TRANSACTION_LIFE_CYCLE_STAGE VARCHAR2(255) NOT NULL,
    GEO_LOCATION CLOB,
    FRAUD_FLAGS CLOB,
    CUSTOMER_TENURE_DAYS NUMBER(18,0),
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP,
    SYS_CR_DT TIMESTAMP,
    SYS_UPD_DT TIMESTAMP
    ,CONSTRAINT PK_DIGITAL_FINANCE_AUTH PRIMARY KEY (ID)
);


-- Dataset: GDS96795
-- Schema: IRONCLAD_DIGITAL

-- This it dataset supports mobility solutions operations. Key applications include data analysis, repo
CREATE TABLE IRONCLAD_DIGITAL.DIGITAL_FINANCE_AUTHORIZATION_ (
    ID NUMBER(18,0) NOT NULL,
    AUTHORIZATION_ID RAW(16) NOT NULL,
    TRANSACTION_ID VARCHAR2(255) NOT NULL,
    CUSTOMER_INTERNAL_ID VARCHAR2(255) NOT NULL,
    MASREPH_USER_ID VARCHAR2(255),
    CUSTOMER_ONBOARD_DATE DATE,
    DEVICE_FINGERPRINT_ID VARCHAR2(255),
    API_CLIENT_ID VARCHAR2(255) NOT NULL,
    SESSION_ID VARCHAR2(255),
    AUTHORIZATION_TIMESTAMP TIMESTAMP NOT NULL,
    TRANSACTION_CURRENCY_CODE VARCHAR2(255) NOT NULL,
    TRANSACTION_AMOUNT NUMBER(18,2) NOT NULL,
    AUTHORIZATION_STATUS VARCHAR2(255) NOT NULL,
    AUTHORIZATION_CHANNEL VARCHAR2(255) NOT NULL,
    PAYMENT_METHOD_TYPE VARCHAR2(255) NOT NULL,
    CARD_TOKEN_ID VARCHAR2(255),
    IBAN_MASKED VARCHAR2(34),
    ISSUER_COUNTRY_CODE VARCHAR2(255),
    MERCHANT_ID VARCHAR2(255) NOT NULL,
    MERCHANT_CATEGORY_CODE VARCHAR2(255),
    MOBILITY_SERVICE_TYPE VARCHAR2(255) NOT NULL,
    ROUTE_START_LOCATION VARCHAR2(255),
    ROUTE_END_LOCATION VARCHAR2(255),
    VEHICLE_TYPE VARCHAR2(255),
    LOAN_APPLICATION_ID VARCHAR2(255),
    LOAN_OFFER_AMOUNT NUMBER(18,2),
    LOAN_TENOR_MONTHS NUMBER(18,0),
    RISK_SCORE NUMBER(5,2),
    FRAUD_CHECK_STATUS VARCHAR2(255),
    GDPR_CONSENT_FLAG NUMBER(1) NOT NULL,
    STRONG_CUSTOMER_AUTH_METHOD VARCHAR2(255),
    RETRY_ATTEMPT_COUNT NUMBER(18,0) NOT NULL,
    RESPONSE_LATENCY_MS NUMBER(18,0),
    DOWNSTREAM_PROCESSOR_NAME VARCHAR2(255),
    ERROR_CODE VARCHAR2(255),
    ERROR_MESSAGE VARCHAR2(255),
    API_VERSION VARCHAR2(255) NOT NULL,
    STREAMING_INGEST_TIMESTAMP TIMESTAMP NOT NULL,
    IS_TEST_SESSION NUMBER(1) NOT NULL,
    RAW_AUTHORIZATION_PAYLOAD VARCHAR2(255),
    TAGS_ARRAY CLOB,
    DATA_LINEAGE_OBJECT CLOB NOT NULL,
    SYS_CR_DT TIMESTAMP,
    SYS_UPD_DT TIMESTAMP
    ,CONSTRAINT PK_DIGITAL_FINANCE_AUTH PRIMARY KEY (ID)
);


