-- ============================================
-- Platform: ORACLE
-- Schema/Source: NAMSYS
-- Generated: 2026-03-18T12:18:16.778091
-- Datasets: 1
-- ============================================

-- Dataset: GDS44325
-- Schema: NAMSYS

-- This product dataset supports commercial finance operations. Key applications include product perfor
CREATE TABLE NAMSYS.CASHFLOW_INSIGHTS_DATASET (
    ID NUMBER(18,0) NOT NULL,
    CASHFLOW_RECORD_ID RAW(16) NOT NULL,
    MASREPH_CUSTOMER_ID VARCHAR2(255) NOT NULL,
    PRODUCT_ID VARCHAR2(255) NOT NULL,
    PRODUCT_NAME VARCHAR2(255) NOT NULL,
    ACCOUNT_IBAN VARCHAR2(34) NOT NULL,
    COUNTERPARTY_COUNTRY_CODE VARCHAR2(255),
    TRANSACTION_TIMESTAMP TIMESTAMP NOT NULL,
    VALUE_DATE DATE NOT NULL,
    CASHFLOW_TYPE VARCHAR2(255) NOT NULL,
    CASHFLOW_DIRECTION VARCHAR2(255) NOT NULL,
    TRANSACTION_CURRENCY VARCHAR2(255) NOT NULL,
    TRANSACTION_AMOUNT NUMBER(18,2) NOT NULL,
    AMOUNT_IN_BOOK_CURRENCY NUMBER(18,2) NOT NULL,
    BOOK_CURRENCY_CODE VARCHAR2(255) NOT NULL,
    FX_RATE_APPLIED NUMBER(12,6),
    INTEREST_RATE_EFFECTIVE NUMBER(7,4),
    PRODUCT_SEGMENT VARCHAR2(255) NOT NULL,
    CUSTOMER_INDUSTRY_CODE VARCHAR2(255),
    CUSTOMER_SIZE_BAND VARCHAR2(255),
    CASHFLOW_STATUS VARCHAR2(255) NOT NULL,
    IS_IN_DEFAULT_EXPOSURE NUMBER(1) NOT NULL,
    DAYS_PAST_DUE NUMBER(18,0),
    ORIGINATION_DATE DATE,
    MATURITY_DATE DATE,
    REMAINING_PRINCIPAL_BALANCE NUMBER(18,2),
    FEE_TYPE_CODE VARCHAR2(255),
    CHANNEL_CODE VARCHAR2(255),
    PORTFOLIO_ID VARCHAR2(255) NOT NULL,
    RISK_WEIGHT_PERCENT NUMBER(5,2),
    INTERNAL_RATING_GRADE VARCHAR2(255),
    CUSTOMER_CONSENT_MARKETING NUMBER(1) NOT NULL,
    ANONYMIZED_CUSTOMER_KEY VARCHAR2(255),
    DATA_CAPTURE_TIMESTAMP TIMESTAMP NOT NULL,
    SYS_CR_DT TIMESTAMP,
    SYS_UPD_DT TIMESTAMP
    ,CONSTRAINT PK_CASHFLOW_INSIGHTS_DA PRIMARY KEY (ID)
);


