-- ============================================
-- Platform: ORACLE
-- Schema/Source: OMNICONNECT_TRADE
-- Generated: 2026-03-18T12:18:16.770740
-- Datasets: 4
-- ============================================

-- Dataset: GDS10611
-- Schema: OMNICONNECT_TRADE

-- This collateral dataset supports leasing operations. Key applications include asset valuation, risk 
CREATE TABLE OMNICONNECT_TRADE.COLLATERAL_FINANCE_DATA_SET (
    ID NUMBER(18,0) NOT NULL,
    COLLATERAL_ID RAW(16) NOT NULL,
    COLLATERAL_EXTERNAL_REF VARCHAR2(255),
    LESSOR_LEGAL_ENTITY_ID VARCHAR2(255) NOT NULL,
    LESSEE_CUSTOMER_ID VARCHAR2(255) NOT NULL,
    LESSEE_SEGMENT_CODE VARCHAR2(255),
    ASSET_COLLATERAL_TYPE_CODE VARCHAR2(255) NOT NULL,
    ASSET_CATEGORY VARCHAR2(255) NOT NULL,
    ASSET_DESCRIPTION VARCHAR2(255),
    ASSET_MANUFACTURER_NAME VARCHAR2(255),
    ASSET_MODEL_NAME VARCHAR2(255),
    ASSET_SERIAL_NUMBER VARCHAR2(255),
    ASSET_COUNTRY_OF_LOCATION VARCHAR2(255) NOT NULL,
    ASSET_POSTAL_CODE VARCHAR2(255),
    ASSET_PURCHASE_DATE DATE,
    ASSET_PURCHASE_PRICE_AMOUNT NUMBER(18,2),
    COLLATERAL_VALUATION_CURRENCY_ VARCHAR2(255) NOT NULL,
    LATEST_VALUATION_AMOUNT NUMBER(18,2),
    LATEST_VALUATION_DATE DATE,
    VALUATION_METHOD_CODE VARCHAR2(255),
    VALUATION_PROVIDER_NAME VARCHAR2(255),
    HAIRCUT_PERCENTAGE NUMBER(5,2),
    REGULATORY_ELIGIBILITY_FLAG NUMBER(1) NOT NULL,
    COLLATERAL_STATUS_CODE VARCHAR2(255) NOT NULL,
    LIEN_RANK_CODE VARCHAR2(255),
    LOAN_CONTRACT_ID VARCHAR2(255) NOT NULL,
    LOAN_ORIGINAL_PRINCIPAL_AMOUNT NUMBER(18,2) NOT NULL,
    LOAN_OUTSTANDING_PRINCIPAL_AMO NUMBER(18,2) NOT NULL,
    LOAN_TO_VALUE_RATIO_PERCENTAGE NUMBER(6,2),
    RECOVERY_RATE_ESTIMATE_PERCENT NUMBER(5,2),
    REPOSSESSION_FLAG NUMBER(1) NOT NULL,
    REPOSSESSION_DATE DATE,
    IMPAIRMENT_INDICATOR_FLAG NUMBER(1) NOT NULL,
    WRITE_OFF_DATE DATE,
    COLLATERAL_INSURANCE_POLICY_NU VARCHAR2(255),
    COLLATERAL_INSURED_VALUE_AMOUN NUMBER(18,2),
    COLLATERAL_INSURANCE_EXPIRY_DA DATE,
    RISK_WEIGHT_PERCENTAGE NUMBER(5,2),
    CREATED_TIMESTAMP TIMESTAMP NOT NULL,
    LAST_UPDATED_TIMESTAMP TIMESTAMP NOT NULL,
    DATA_SOURCE_SYSTEM_CODE VARCHAR2(255) NOT NULL,
    CONSENT_TO_USE_DATA_FLAG NUMBER(1) NOT NULL,
    ASSET_USAGE_TYPE_CODES CLOB,
    GEO_LOCATION_COORDINATES CLOB,
    SYS_CR_DT TIMESTAMP,
    SYS_UPD_DT TIMESTAMP
    ,CONSTRAINT PK_COLLATERAL_FINANCE_D PRIMARY KEY (ID)
);


-- Dataset: GDS30435
-- Schema: OMNICONNECT_TRADE

-- This product dataset supports leasing operations. Key applications include product performance analy
CREATE TABLE OMNICONNECT_TRADE.FINANCE_TRANSACTION_INSIGHTS (
    ID NUMBER(18,0) NOT NULL,
    TRANSACTION_ID RAW(16) NOT NULL,
    LEASE_CONTRACT_ID VARCHAR2(255) NOT NULL,
    MASREPH_PRODUCT_CODE VARCHAR2(255) NOT NULL,
    PRODUCT_NAME VARCHAR2(255) NOT NULL,
    LESSEE_CUSTOMER_ID VARCHAR2(255) NOT NULL,
    LESSEE_SEGMENT VARCHAR2(255),
    ASSET_TYPE VARCHAR2(255) NOT NULL,
    ASSET_DESCRIPTION VARCHAR2(255),
    TRANSACTION_TYPE VARCHAR2(255) NOT NULL,
    TRANSACTION_TIMESTAMP TIMESTAMP NOT NULL,
    TRANSACTION_VALUE_DATE DATE NOT NULL,
    TRANSACTION_CURRENCY VARCHAR2(255) NOT NULL,
    TRANSACTION_AMOUNT NUMBER(15,2) NOT NULL,
    PRINCIPAL_COMPONENT_AMOUNT NUMBER(15,2),
    INTEREST_COMPONENT_AMOUNT NUMBER(15,2),
    FEE_COMPONENT_AMOUNT NUMBER(15,2),
    OUTSTANDING_PRINCIPAL_BALANCE NUMBER(17,2) NOT NULL,
    DAYS_PAST_DUE NUMBER(18,0),
    PAYMENT_STATUS VARCHAR2(255) NOT NULL,
    CONTRACT_START_DATE DATE NOT NULL,
    CONTRACT_END_DATE DATE,
    CONTRACTUAL_TENOR_MONTHS NUMBER(18,0) NOT NULL,
    INTEREST_RATE_FIXED_INDICATOR NUMBER(1) NOT NULL,
    NOMINAL_INTEREST_RATE NUMBER(7,4),
    EFFECTIVE_YIELD_RATE NUMBER(7,4),
    PORTFOLIO_ID VARCHAR2(255) NOT NULL,
    BOOKING_BRANCH_COUNTRY_CODE VARCHAR2(255) NOT NULL,
    COUNTERPARTY_IBAN_HASH VARCHAR2(255),
    CROSS_SELL_ELIGIBILITY_FLAG NUMBER(1),
    PRODUCT_PERFORMANCE_SEGMENT VARCHAR2(255),
    EXPECTED_LOSS_AMOUNT NUMBER(15,2),
    INTERNAL_RISK_GRADE VARCHAR2(255),
    MARKET_COMPETITOR_IDS CLOB,
    PRODUCT_PERFORMANCE_METRICS CLOB,
    LAST_UPDATED_TIMESTAMP TIMESTAMP NOT NULL,
    SYS_CR_DT TIMESTAMP,
    SYS_UPD_DT TIMESTAMP
    ,CONSTRAINT PK_FINANCE_TRANSACTION_ PRIMARY KEY (ID)
);


-- Dataset: GDS32513
-- Schema: OMNICONNECT_TRADE

-- This product dataset supports finance office operations. Key applications include product performanc
CREATE TABLE OMNICONNECT_TRADE.TRADE_FINANCE_DATA_SET (
    ID NUMBER(18,0) NOT NULL,
    TRADE_FINANCE_TRANSACTION_ID VARCHAR2(255) NOT NULL,
    TRADE_CONTRACT_REFERENCE VARCHAR2(255) NOT NULL,
    CUSTOMER_INTERNAL_ID VARCHAR2(255) NOT NULL,
    COUNTERPARTY_COUNTRY_CODE VARCHAR2(255) NOT NULL,
    ISSUING_BRANCH_CODE VARCHAR2(255) NOT NULL,
    PRODUCT_TYPE_CODE VARCHAR2(255) NOT NULL,
    PRODUCT_SUBTYPE_DESCRIPTION VARCHAR2(255),
    TRADE_BOOKING_DATE DATE NOT NULL,
    TRADE_MATURITY_DATE DATE,
    LAST_STATUS_UPDATE_TIMESTAMP TIMESTAMP NOT NULL,
    TRANSACTION_STATUS_CODE VARCHAR2(255) NOT NULL,
    TRADE_CURRENCY_CODE VARCHAR2(255) NOT NULL,
    TRADE_NOMINAL_AMOUNT NUMBER(18,2) NOT NULL,
    TRADE_OUTSTANDING_AMOUNT NUMBER(18,2) NOT NULL,
    PAYMENT_TERM_DAYS NUMBER(18,0),
    PAYMENT_METHOD_CODE VARCHAR2(255) NOT NULL,
    CLIENT_SEGMENT_CODE VARCHAR2(255) NOT NULL,
    INDUSTRY_SECTOR_CODE VARCHAR2(255),
    TRADE_PURPOSE_DESCRIPTION VARCHAR2(255),
    COUNTERPARTY_RISK_RATING VARCHAR2(255),
    PRICING_MARGIN_BPS NUMBER(7,2),
    FEE_INCOME_AMOUNT NUMBER(18,2) NOT NULL,
    INTEREST_INCOME_AMOUNT NUMBER(18,2),
    BOOKING_CURRENCY_CODE VARCHAR2(255) NOT NULL,
    FX_SPOT_RATE_AT_BOOKING NUMBER(16,8),
    EUROPEAN_ECONOMIC_AREA_FLAG NUMBER(1) NOT NULL,
    DOCUMENTARY_TRADE_FLAG NUMBER(1) NOT NULL,
    SUPPLY_CHAIN_FINANCE_PROGRAM_I VARCHAR2(255),
    PORTFOLIO_BUCKET_CODE VARCHAR2(255),
    CROSS_SELL_INDICATOR NUMBER(1) NOT NULL,
    ORIGINATING_CHANNEL_CODE VARCHAR2(255) NOT NULL,
    SANCTIONS_SCREENING_STATUS VARCHAR2(255) NOT NULL,
    TRANSACTION_PISEUDONYMIZED_KEY VARCHAR2(255),
    EXPECTED_LOSS_RATE_PCT NUMBER(6,4),
    SYS_CR_DT TIMESTAMP,
    SYS_UPD_DT TIMESTAMP
    ,CONSTRAINT PK_TRADE_FINANCE_DATA_S PRIMARY KEY (ID)
);


-- Dataset: GDS37121
-- Schema: OMNICONNECT_TRADE

-- This collateral dataset supports commercial finance operations. Key applications include asset valua
CREATE TABLE OMNICONNECT_TRADE.COLLATERAL_FINANCE_DATA_SET (
    ID NUMBER(18,0) NOT NULL,
    COLLATERAL_ID RAW(16) NOT NULL,
    LOAN_ID VARCHAR2(255) NOT NULL,
    CUSTOMER_ID VARCHAR2(255) NOT NULL,
    LEGAL_ENTITY_NAME VARCHAR2(255) NOT NULL,
    COLLATERAL_REFERENCE VARCHAR2(255) NOT NULL,
    COLLATERAL_TYPE_CODE VARCHAR2(255) NOT NULL,
    COLLATERAL_SUB_TYPE VARCHAR2(255),
    COLLATERAL_STATUS VARCHAR2(255) NOT NULL,
    JURISDICTION_COUNTRY_CODE VARCHAR2(255) NOT NULL,
    LOCATION_ADDRESS_SUMMARY VARCHAR2(255),
    VALUATION_CURRENCY_CODE VARCHAR2(255) NOT NULL,
    LATEST_VALUATION_AMOUNT NUMBER(18,2) NOT NULL,
    VALUATION_EFFECTIVE_DATE DATE NOT NULL,
    VALUATION_METHOD_CODE VARCHAR2(255) NOT NULL,
    VALUATION_FIRM_NAME VARCHAR2(255),
    REGULATORY_HAIRCUT_PERCENTAGE NUMBER(5,2),
    INTERNAL_HAIRCUT_PERCENTAGE NUMBER(5,2) NOT NULL,
    ELIGIBLE_COLLATERAL_FLAG NUMBER(1) NOT NULL,
    ENFORCEABILITY_ASSESSMENT VARCHAR2(255),
    LOAN_OUTSTANDING_AMOUNT NUMBER(18,2) NOT NULL,
    CURRENT_LTV_PERCENTAGE NUMBER(6,2) NOT NULL,
    MAX_PERMITTED_LTV_PERCENTAGE NUMBER(6,2) NOT NULL,
    PLEDGE_RANK NUMBER(18,0) NOT NULL,
    SECURED_EXPOSURE_AMOUNT NUMBER(18,2),
    COLLATERAL_OWNERSHIP_TYPE VARCHAR2(255) NOT NULL,
    PERFECTION_STATUS VARCHAR2(255) NOT NULL,
    PERFECTION_DATE DATE,
    REVALUATION_FREQUENCY_MONTHS NUMBER(18,0) NOT NULL,
    NEXT_VALUATION_DUE_DATE DATE,
    ENVIRONMENTAL_RISK_FLAG NUMBER(1),
    INSURANCE_COVERAGE_AMOUNT NUMBER(18,2),
    INSURANCE_EXPIRY_DATE DATE,
    INTERNAL_COLLATERAL_RATING VARCHAR2(255),
    EXPECTED_RECOVERY_RATE_PERCENT NUMBER(5,2),
    COLLATERAL_REALIZATION_TIME_MO NUMBER(18,0),
    SECURITY_DOCUMENT_REFERENCE VARCHAR2(255),
    LAST_STATUS_UPDATE_TIMESTAMP TIMESTAMP NOT NULL,
    DATA_SENSITIVITY_CLASSIFICATIO VARCHAR2(255) NOT NULL,
    SOURCE_SYSTEM_NAME VARCHAR2(255) NOT NULL,
    SYS_CR_DT TIMESTAMP,
    SYS_UPD_DT TIMESTAMP
    ,CONSTRAINT PK_COLLATERAL_FINANCE_D PRIMARY KEY (ID)
);


