-- ============================================
-- Platform: ORACLE
-- Schema/Source: PERITAM
-- Generated: 2026-03-18T12:18:16.778091
-- Datasets: 1
-- ============================================

-- Dataset: GDS33952
-- Schema: PERITAM

-- This employee dataset supports human resource office operations. Key applications include data analy
CREATE TABLE PERITAM.NL_FINANCE_STAFFING_DATA (
    ID NUMBER(18,0) NOT NULL,
    EMPLOYEE_ID VARCHAR2(255) NOT NULL,
    MASREPH_PERSONNEL_NUMBER VARCHAR2(255) NOT NULL,
    FULL_NAME VARCHAR2(255) NOT NULL,
    BIRTH_DATE DATE NOT NULL,
    GENDER_CODE VARCHAR2(255),
    HIRE_DATE DATE NOT NULL,
    TERMINATION_DATE DATE,
    EMPLOYMENT_STATUS VARCHAR2(255) NOT NULL,
    CONTRACT_TYPE VARCHAR2(255) NOT NULL,
    POSITION_TITLE VARCHAR2(255) NOT NULL,
    DEPARTMENT_CODE VARCHAR2(255) NOT NULL,
    DEPARTMENT_NAME VARCHAR2(255) NOT NULL,
    BASE_SALARY_EUR NUMBER(15,2) NOT NULL,
    FTE_PERCENTAGE NUMBER(5,2) NOT NULL,
    WORK_LOCATION_CITY VARCHAR2(255),
    WORK_COUNTRY_CODE VARCHAR2(255) NOT NULL,
    COST_CENTER_CODE VARCHAR2(255) NOT NULL,
    UNION_MEMBERSHIP_FLAG NUMBER(1),
    PERFORMANCE_RATING_SCORE NUMBER(3,1),
    RECORD_EFFECTIVE_TIMESTAMP TIMESTAMP NOT NULL,
    REMOTE_WORK_RATIO NUMBER(5,2),
    SYS_CR_DT TIMESTAMP,
    SYS_UPD_DT TIMESTAMP
    ,CONSTRAINT PK_NL_FINANCE_STAFFING_ PRIMARY KEY (ID)
);


