-- ============================================
-- Platform: ORACLE
-- Schema/Source: REALESTATE_STORE
-- Generated: 2026-03-18T12:18:16.771739
-- Datasets: 5
-- ============================================

-- Dataset: GDS12287
-- Schema: REALESTATE_STORE

-- This client dataset supports consumer finance operations. Key applications include relationship mana
CREATE TABLE REALESTATE_STORE.FLORIUS_FINANCE_CUSTOMERS_DATA (
    ID NUMBER(18,0) NOT NULL,
    CUSTOMER_ID RAW(16) NOT NULL,
    CRM_PARTY_REFERENCE VARCHAR2(255) NOT NULL,
    CUSTOMER_LIFECYCLE_STATUS VARCHAR2(255) NOT NULL,
    PRIMARY_COUNTRY_OF_RESIDENCE VARCHAR2(255) NOT NULL,
    DATE_OF_BIRTH DATE,
    CUSTOMER_ONBOARDING_DATE DATE NOT NULL,
    PREFERRED_CONTACT_CHANNEL VARCHAR2(320),
    EMAIL_ADDRESS_HASH VARCHAR2(255),
    GDPR_MARKETING_CONSENT_FLAG NUMBER(1) NOT NULL,
    LAST_INTERACTION_TIMESTAMP TIMESTAMP,
    PRIMARY_PROPERTY_LOAN_BALANCE NUMBER(15,2),
    PRIMARY_PROPERTY_LOAN_LTV_RATI NUMBER(5,2),
    ANNUAL_GROSS_INCOME_EUR NUMBER(13,2),
    CUSTOMER_PROFITABILITY_ROLLING NUMBER(15,2),
    BEHAVIORAL_CREDIT_SCORE NUMBER(18,0),
    DAYS_PAST_DUE_MAX_LAST_12M NUMBER(18,0),
    CLIENT_SEGMENT_CODES CLOB,
    TOTAL_NUMBER_OF_ACTIVE_ACCOUNT NUMBER(18,0) NOT NULL,
    RELATIONSHIP_MANAGER_ID VARCHAR2(255),
    PRIMARY_PROPERTY_COUNTRY_CODE VARCHAR2(255),
    SYS_CR_DT TIMESTAMP,
    SYS_UPD_DT TIMESTAMP
    ,CONSTRAINT PK_FLORIUS_FINANCE_CUST PRIMARY KEY (ID)
);


-- Dataset: GDS35091
-- Schema: REALESTATE_STORE

-- This client dataset supports consumer finance operations. Key applications include relationship mana
CREATE TABLE REALESTATE_STORE.FINANCE_SUBSIDIARY_INSIGHTS (
    ID NUMBER(18,0) NOT NULL,
    SUBSIDIARY_ID VARCHAR2(255) NOT NULL,
    SUBSIDIARY_LEGAL_NAME VARCHAR2(255) NOT NULL,
    SUBSIDIARY_COUNTRY_CODE VARCHAR2(255) NOT NULL,
    CLIENT_ID VARCHAR2(255) NOT NULL,
    CLIENT_GLOBAL_PARTY_ID RAW(16),
    LOAN_ACCOUNT_ID VARCHAR2(255) NOT NULL,
    CRM_RELATIONSHIP_ID VARCHAR2(255),
    CLIENT_SEGMENT_CODE VARCHAR2(255),
    CLIENT_RESIDENCE_COUNTRY_CODE VARCHAR2(255),
    CLIENT_DATE_OF_BIRTH DATE,
    CLIENT_AGE_YEARS NUMBER(18,0),
    PRIMARY_RELATIONSHIP_MANAGER_I VARCHAR2(255),
    RELATIONSHIP_START_DATE DATE,
    RELATIONSHIP_STATUS VARCHAR2(255) NOT NULL,
    RELATIONSHIP_TENURE_MONTHS NUMBER(18,0),
    LOAN_ORIGINATION_DATE DATE NOT NULL,
    LOAN_MATURITY_DATE DATE,
    LOAN_ORIGINAL_PRINCIPAL_AMOUNT NUMBER(15,2) NOT NULL,
    LOAN_OUTSTANDING_PRINCIPAL_AMO NUMBER(15,2) NOT NULL,
    LOAN_CURRENCY_CODE VARCHAR2(255) NOT NULL,
    LOAN_INTEREST_RATE_ANNUAL NUMBER(5,3) NOT NULL,
    INTEREST_RATE_TYPE VARCHAR2(255) NOT NULL,
    LOAN_STATUS_CODE VARCHAR2(255) NOT NULL,
    DAYS_PAST_DUE NUMBER(18,0) NOT NULL,
    NON_PERFORMING_FLAG NUMBER(1) NOT NULL,
    EFFECTIVE_INTEREST_INCOME_YTD NUMBER(17,2),
    FEE_INCOME_YTD NUMBER(17,2),
    EXPECTED_CREDIT_LOSS_LIFETIME NUMBER(17,2),
    RISK_GRADE_CODE VARCHAR2(255),
    PROFITABILITY_CONTRIBUTION_YTD NUMBER(18,2),
    PROFITABILITY_CONTRIBUTION_LIF NUMBER(18,2),
    CROSS_SELL_PRODUCTS_COUNT NUMBER(18,0),
    PRIMARY_CONTACT_CHANNEL VARCHAR2(255),
    LAST_INTERACTION_TIMESTAMP TIMESTAMP,
    LAST_INTERACTION_TYPE VARCHAR2(255),
    COMPLAINTS_COUNT_LAST_12M NUMBER(18,0),
    CLIENT_NET_PROMOTER_SCORE NUMBER(18,0),
    MARKETING_OPT_IN_FLAG NUMBER(1) NOT NULL,
    GDPR_PROCESSING_CONSENT_FLAG NUMBER(1) NOT NULL,
    CONSENT_LAST_UPDATED_TIMESTAMP TIMESTAMP,
    CLIENT_EMAIL_HASH VARCHAR2(255),
    CLIENT_POSTAL_CODE_MASKED VARCHAR2(255),
    INCOME_BRACKET_CODE VARCHAR2(255),
    EMPLOYMENT_STATUS_CODE VARCHAR2(255),
    DIGITAL_ENGAGEMENT_SCORE NUMBER(5,2),
    PAYMENT_BEHAVIOR_SEGMENT VARCHAR2(255),
    SCHEDULED_MONTHLY_INSTALLMENT_ NUMBER(15,2),
    NEXT_SCHEDULED_PAYMENT_DATE DATE,
    SUBSIDIARY_COST_OF_FUNDS_RATE NUMBER(5,3),
    ASSOCIATED_CAMPAIGN_IDS CLOB,
    CLIENT_CONTACT_PREFERENCES CLOB,
    SYS_CR_DT TIMESTAMP,
    SYS_UPD_DT TIMESTAMP
    ,CONSTRAINT PK_FINANCE_SUBSIDIARY_I PRIMARY KEY (ID)
);


-- Dataset: GDS39302
-- Schema: REALESTATE_STORE

-- This client dataset supports consumer finance operations. Key applications include relationship mana
CREATE TABLE REALESTATE_STORE.MORTGAGE_FINANCE_INSIGHTS_ (
    ID NUMBER(18,0) NOT NULL,
    CLIENT_ID RAW(16) NOT NULL,
    MASREPH_CUSTOMER_NUMBER VARCHAR2(255) NOT NULL,
    MORTGAGE_ACCOUNT_ID VARCHAR2(255) NOT NULL,
    CLIENT_SEGMENT VARCHAR2(255),
    RESIDENCE_COUNTRY_CODE VARCHAR2(255) NOT NULL,
    CLIENT_BIRTH_DATE DATE,
    CLIENT_AGE_YEARS NUMBER(18,0),
    CLIENT_ONBOARDED_TIMESTAMP TIMESTAMP NOT NULL,
    PRIMARY_RELATIONSHIP_MANAGER_I VARCHAR2(255),
    RELATIONSHIP_TENURE_MONTHS NUMBER(18,0),
    TOTAL_MORTGAGE_EXPOSURE_EUR NUMBER(15,2) NOT NULL,
    CURRENT_MORTGAGE_BALANCE_EUR NUMBER(15,2) NOT NULL,
    AVERAGE_MORTGAGE_RATE_PCT NUMBER(5,3),
    MORTGAGE_PRODUCT_TYPE VARCHAR2(255),
    MORTGAGE_ORIGINATION_DATE DATE,
    MORTGAGE_MATURITY_DATE DATE,
    LTV_AT_ORIGINATION_PCT NUMBER(5,2),
    CURRENT_LTV_PCT NUMBER(5,2),
    CLIENT_PROFITABILITY_SCORE NUMBER(5,2),
    TWELVE_MONTHS_MORTGAGE_REVENUE NUMBER(15,2),
    EXPECTED_CLIENT_LIFETIME_VALUE NUMBER(17,2),
    CLIENT_RISK_RATING VARCHAR2(255),
    PROBABILITY_OF_DEFAULT_12M_PCT NUMBER(5,3),
    IS_CLIENT_IN_ARREARS NUMBER(1) NOT NULL,
    DAYS_PAST_DUE_MAX_12M NUMBER(18,0),
    LAST_MORTGAGE_PAYMENT_DATE DATE,
    PREFERRED_CONTACT_CHANNEL VARCHAR2(255),
    CONSENT_TO_MARKETING NUMBER(1) NOT NULL,
    GDPR_DATA_PROCESSING_CONSENT NUMBER(1) NOT NULL,
    LAST_RELATIONSHIP_CONTACT_TIME TIMESTAMP,
    CROSS_SELL_ELIGIBILITY_FLAGS CLOB,
    CLIENT_LANGUAGE_PREFERENCE VARCHAR2(255),
    CRM_SOURCE_SYSTEM_ID VARCHAR2(255) NOT NULL,
    DATA_RECORD_LAST_UPDATED_TIMES TIMESTAMP NOT NULL,
    CLIENT_EMPLOYMENT_STATUS VARCHAR2(255),
    HOUSEHOLD_NET_MONTHLY_INCOME_E NUMBER(12,2),
    SYS_CR_DT TIMESTAMP,
    SYS_UPD_DT TIMESTAMP
    ,CONSTRAINT PK_MORTGAGE_FINANCE_INS PRIMARY KEY (ID)
);


-- Dataset: GDS50320
-- Schema: REALESTATE_STORE

-- This client dataset supports consumer finance operations. Key applications include relationship mana
CREATE TABLE REALESTATE_STORE.FLORIUS_FINANCE_INSIGHTS (
    ID NUMBER(18,0) NOT NULL,
    CLIENT_INTERNAL_ID RAW(16) NOT NULL,
    CORE_BANKING_CUSTOMER_NUMBER VARCHAR2(255) NOT NULL,
    CLIENT_SEGMENT_CODE VARCHAR2(255) NOT NULL,
    CLIENT_RESIDENCY_COUNTRY VARCHAR2(255) NOT NULL,
    PRIMARY_RESIDENTIAL_PROPERTY_I VARCHAR2(255),
    RELATIONSHIP_START_DATE DATE NOT NULL,
    RELATIONSHIP_STATUS VARCHAR2(255) NOT NULL,
    PREFERRED_CONTACT_CHANNEL VARCHAR2(320),
    PRIMARY_EMAIL_ADDRESS VARCHAR2(320),
    MOBILE_PHONE_NUMBER VARCHAR2(255),
    GDPR_CONTACT_CONSENT_FLAG NUMBER(1) NOT NULL,
    GDPR_CONSENT_LAST_UPDATED_TS TIMESTAMP,
    TOTAL_OUTSTANDING_PROPERTY_BAL NUMBER(15,2) NOT NULL,
    WEIGHTED_AVERAGE_MORTGAGE_RATE NUMBER(5,3),
    CLIENT_PROPERTY_PORTFOLIO_COUN NUMBER(18,0) NOT NULL,
    CLIENT_ANNUAL_PROPERTY_FINANCE NUMBER(15,2),
    CLIENT_DIRECT_COST_ALLOCATED NUMBER(15,2),
    CLIENT_NET_CONTRIBUTION_MARGIN NUMBER(15,2),
    LAST_RELATIONSHIP_MANAGER_INTE TIMESTAMP,
    NEXT_SCHEDULED_CONTACT_DATE DATE,
    RELATIONSHIP_MANAGER_ID VARCHAR2(255),
    CLIENT_PROFITABILITY_SEGMENT VARCHAR2(255),
    CLIENT_RISK_GRADE VARCHAR2(255),
    PRIMARY_FUNDING_CURRENCY VARCHAR2(255) NOT NULL,
    CLIENT_LIFECYCLE_STAGE VARCHAR2(255),
    DIGITAL_ENGAGEMENT_SCORE NUMBER(18,0),
    RECENT_PRODUCT_OPPORTUNITY_FLA CLOB,
    CLIENT_PROFILE_LAST_UPDATED_TS TIMESTAMP NOT NULL,
    SYS_CR_DT TIMESTAMP,
    SYS_UPD_DT TIMESTAMP
    ,CONSTRAINT PK_FLORIUS_FINANCE_INSI PRIMARY KEY (ID)
);


-- Dataset: GDS59046
-- Schema: REALESTATE_STORE

-- This client dataset supports mobility solutions operations. Key applications include relationship ma
CREATE TABLE REALESTATE_STORE.MORTGAGE_FINANCE_INSIGHTS_ (
    ID NUMBER(18,0) NOT NULL,
    CLIENT_ID RAW(16) NOT NULL,
    MASREPH_PARTY_NUMBER VARCHAR2(255) NOT NULL,
    CLIENT_SEGMENT_CODE VARCHAR2(255) NOT NULL,
    CLIENT_SEGMENT_DESCRIPTION VARCHAR2(255),
    PRIMARY_RELATIONSHIP_MANAGER_I VARCHAR2(255),
    PRIMARY_RELATIONSHIP_MANAGER_N VARCHAR2(255),
    CLIENT_RESIDENCY_COUNTRY_CODE VARCHAR2(255) NOT NULL,
    CLIENT_PRIMARY_CITY VARCHAR2(255),
    CLIENT_BIRTH_DATE DATE,
    CLIENT_TYPE VARCHAR2(255) NOT NULL,
    MORTGAGE_ACCOUNT_ID VARCHAR2(255),
    MORTGAGE_ORIGINATION_DATE DATE,
    MORTGAGE_ORIGINAL_PRINCIPAL_AM NUMBER(15,2),
    MORTGAGE_OUTSTANDING_PRINCIPAL NUMBER(15,2),
    MORTGAGE_INTEREST_RATE NUMBER(5,3),
    MORTGAGE_RATE_TYPE VARCHAR2(255),
    MORTGAGE_MATURITY_DATE DATE,
    MORTGAGE_PAYMENT_FREQUENCY VARCHAR2(255),
    MORTGAGE_CURRENT_STATUS VARCHAR2(255),
    DAYS_PAST_DUE_MORTGAGE NUMBER(18,0),
    AUTO_LOAN_COUNT NUMBER(18,0) NOT NULL,
    ACTIVE_MOBILITY_CONTRACTS_COUN NUMBER(18,0) NOT NULL,
    TOTAL_MOBILITY_FINANCE_EXPOSUR NUMBER(15,2) NOT NULL,
    CLIENT_TOTAL_REVENUE_YTD NUMBER(15,2) NOT NULL,
    CLIENT_PROFITABILITY_SCORE NUMBER(6,3),
    CROSS_SELL_OPPORTUNITY_INDEX NUMBER(5,3),
    CLIENT_RISK_RATING VARCHAR2(255),
    PEP_FLAG NUMBER(1) NOT NULL,
    GDPR_MARKETING_CONSENT_FLAG NUMBER(1) NOT NULL,
    GDPR_CONSENT_LAST_UPDATED_TS TIMESTAMP,
    PRIMARY_CONTACT_EMAIL_HASH VARCHAR2(255),
    PREFERRED_CONTACT_CHANNEL VARCHAR2(320),
    LAST_CONTACT_TIMESTAMP TIMESTAMP,
    LAST_CONTACT_CHANNEL VARCHAR2(320),
    RELATIONSHIP_START_DATE DATE NOT NULL,
    RELATIONSHIP_STATUS VARCHAR2(255) NOT NULL,
    CHURN_RISK_SCORE NUMBER(5,3),
    MOBILITY_USAGE_INTENSITY_INDEX NUMBER(6,3),
    HOUSEHOLD_INCOME_BRACKET VARCHAR2(255),
    PROPERTY_PRIMARY_USE_TYPE VARCHAR2(255),
    PROPERTY_LOCATION_URBAN_FLAG NUMBER(1),
    LOAN_TO_VALUE_CURRENT_RATIO NUMBER(6,3),
    CLIENT_SATISFACTION_SCORE NUMBER(4,2),
    NEXT_BEST_ACTION_CODE VARCHAR2(255),
    RECORD_LAST_UPDATED_TS TIMESTAMP NOT NULL,
    SYS_CR_DT TIMESTAMP,
    SYS_UPD_DT TIMESTAMP
    ,CONSTRAINT PK_MORTGAGE_FINANCE_INS PRIMARY KEY (ID)
);


