-- ============================================
-- Platform: ORACLE
-- Schema/Source: SAP_FINANCE
-- Generated: 2026-03-18T12:18:16.777089
-- Datasets: 1
-- ============================================

-- Dataset: GDS29215
-- Schema: SAP_FINANCE

-- This finance dataset supports finance office operations. Key applications include data analysis, rep
CREATE TABLE SAP_FINANCE.FINANCE_LEDGER_INSIGHTS (
    ID NUMBER(18,0) NOT NULL,
    LEDGER_ENTRY_ID RAW(16) NOT NULL,
    MASREPH_ENTITY_ID VARCHAR2(255) NOT NULL,
    SOURCE_SYSTEM_CODE VARCHAR2(255) NOT NULL,
    ACCOUNT_NUMBER_MASKED VARCHAR2(255),
    GL_ACCOUNT_CODE VARCHAR2(255) NOT NULL,
    GL_ACCOUNT_NAME VARCHAR2(255) NOT NULL,
    COST_CENTER_CODE VARCHAR2(255),
    COST_CENTER_NAME VARCHAR2(255),
    PROFIT_CENTER_CODE VARCHAR2(255),
    INSTRUMENT_ID VARCHAR2(255),
    CURRENCY_CODE VARCHAR2(255) NOT NULL,
    TRANSACTION_DATE DATE NOT NULL,
    POSTING_TIMESTAMP TIMESTAMP NOT NULL,
    VALUE_DATE DATE,
    FISCAL_YEAR NUMBER(18,0) NOT NULL,
    FISCAL_PERIOD NUMBER(18,0) NOT NULL,
    REPORTING_QUARTER VARCHAR2(255) NOT NULL,
    BOOKING_COUNTRY_CODE VARCHAR2(255) NOT NULL,
    BOOKING_LEGAL_ENTITY VARCHAR2(255) NOT NULL,
    AMOUNT_LOCAL_CURRENCY NUMBER(18,2) NOT NULL,
    AMOUNT_REPORTING_CURRENCY NUMBER(18,2) NOT NULL,
    EXCHANGE_RATE NUMBER(12,6),
    DEBIT_CREDIT_INDICATOR VARCHAR2(255) NOT NULL,
    BALANCE_AFTER_TXN NUMBER(20,2),
    IS_REVERSAL_ENTRY NUMBER(1) NOT NULL,
    ORIGINAL_ENTRY_ID RAW(16),
    POSTING_STATUS VARCHAR2(255) NOT NULL,
    APPROVAL_STATUS VARCHAR2(255) NOT NULL,
    APPROVAL_TIMESTAMP TIMESTAMP,
    BUDGET_LINE_ID VARCHAR2(255),
    BUDGET_VERSION_NUMBER NUMBER(18,0),
    BUDGET_AMOUNT_REPORTING_CURREN NUMBER(18,2),
    FORECAST_AMOUNT_REPORTING_CURR NUMBER(18,2),
    ACTUAL_TO_BUDGET_VARIANCE NUMBER(18,2),
    VARIANCE_PERCENTAGE NUMBER(7,2),
    PRODUCT_SEGMENT_CODE VARCHAR2(255),
    CUSTOMER_SEGMENT_CODE VARCHAR2(255),
    FINANCIAL_INSTRUMENT_TYPE VARCHAR2(255),
    MATURITY_DATE DATE,
    INTEREST_RATE NUMBER(7,4),
    IS_HEDGED_ITEM NUMBER(1) NOT NULL,
    LIQUIDITY_BUCKET VARCHAR2(255),
    RISK_RATING_INTERNAL VARCHAR2(255),
    ACCOUNTING_STANDARD_CODE VARCHAR2(255) NOT NULL,
    GDP_COMPLIANCE_FLAG NUMBER(1) NOT NULL,
    DATA_QUALITY_SCORE NUMBER(5,2) NOT NULL,
    RECORD_CREATED_TIMESTAMP TIMESTAMP NOT NULL,
    RECORD_UPDATED_TIMESTAMP TIMESTAMP,
    SYS_CR_DT TIMESTAMP,
    SYS_UPD_DT TIMESTAMP
    ,CONSTRAINT PK_FINANCE_LEDGER_INSIG PRIMARY KEY (ID)
);


