-- ============================================
-- Platform: ORACLE
-- Schema/Source: SOLAR
-- Generated: 2026-03-18T12:18:16.780454
-- Datasets: 1
-- ============================================

-- Dataset: GDS85219
-- Schema: SOLAR

-- This collateral dataset supports commercial finance operations. Key applications include asset valua
CREATE TABLE SOLAR.COMMERCIAL_FINANCE_RECORDS (
    ID NUMBER(18,0) NOT NULL,
    RECORD_ID RAW(16) NOT NULL,
    MASREPH_CUSTOMER_ID VARCHAR2(255) NOT NULL,
    FACILITY_ID VARCHAR2(255) NOT NULL,
    COLLATERAL_ID VARCHAR2(255) NOT NULL,
    COLLATERAL_TYPE_CODE VARCHAR2(255) NOT NULL,
    COLLATERAL_DESCRIPTION VARCHAR2(255),
    INDUSTRY_SECTOR_CODE VARCHAR2(255),
    COUNTRY_OF_RISK VARCHAR2(255) NOT NULL,
    BOOKING_BRANCH_CODE VARCHAR2(255),
    FACILITY_TYPE VARCHAR2(255) NOT NULL,
    FACILITY_CURRENCY VARCHAR2(255) NOT NULL,
    ORIGINAL_FACILITY_AMOUNT NUMBER(18,2) NOT NULL,
    CURRENT_OUTSTANDING_AMOUNT NUMBER(18,2) NOT NULL,
    COLLATERAL_VALUATION_AMOUNT NUMBER(18,2) NOT NULL,
    VALUATION_CURRENCY VARCHAR2(255) NOT NULL,
    VALUATION_EFFECTIVE_DATE DATE NOT NULL,
    VALUATION_METHOD_CODE VARCHAR2(255),
    LOAN_TO_VALUE_RATIO NUMBER(7,4),
    INTERNAL_RATING_GRADE VARCHAR2(255),
    PROBABILITY_OF_DEFAULT_PCT NUMBER(6,4),
    LOSS_GIVEN_DEFAULT_PCT NUMBER(6,2),
    COLLATERAL_HAIRCUT_PCT NUMBER(5,2),
    COLLATERAL_RANK VARCHAR2(255),
    SECURITY_PERFECTION_STATUS VARCHAR2(255),
    LEGAL_ENFORCEABILITY_FLAG NUMBER(1),
    COLLATERAL_OWNER_NAME VARCHAR2(255),
    COLLATERAL_OWNER_IDENTIFIER VARCHAR2(255),
    COLLATERAL_LOCATION_ADDRESS VARCHAR2(255),
    COLLATERAL_LOCATION_COUNTRY VARCHAR2(255),
    EXPOSURE_CLASSIFICATION_CODE VARCHAR2(255),
    IMPAIRMENT_STATUS_CODE VARCHAR2(255),
    DAYS_PAST_DUE NUMBER(18,0),
    RESTRUCTURING_FLAG NUMBER(1),
    RECOVERY_ESTIMATE_AMOUNT NUMBER(18,2),
    RECOVERY_SCENARIO_CODE VARCHAR2(255),
    NEXT_REVIEW_DATE DATE,
    CREATED_TIMESTAMP TIMESTAMP NOT NULL,
    LAST_UPDATED_TIMESTAMP TIMESTAMP NOT NULL,
    SOURCE_SYSTEM_CODE VARCHAR2(255) NOT NULL,
    DATA_QUALITY_SCORE NUMBER(5,2),
    RECORD_ACTIVE_FLAG NUMBER(1) NOT NULL,
    SYS_CR_DT TIMESTAMP,
    SYS_UPD_DT TIMESTAMP
    ,CONSTRAINT PK_COMMERCIAL_FINANCE_R PRIMARY KEY (ID)
);


