-- ============================================
-- Platform: ORACLE
-- Schema/Source: TWIKEY
-- Generated: 2026-03-18T12:18:16.779439
-- Datasets: 1
-- ============================================

-- Dataset: GDS60352
-- Schema: TWIKEY

-- This product dataset supports commercial finance operations. Key applications include product perfor
CREATE TABLE TWIKEY.SEPA_MANDATE_VERIFICATION_DATA (
    ID NUMBER(18,0) NOT NULL,
    MANDATE_ID RAW(16) NOT NULL,
    MANDATE_REFERENCE VARCHAR2(255) NOT NULL,
    CREDITOR_IDENTIFIER VARCHAR2(255) NOT NULL,
    DEBTOR_IBAN VARCHAR2(34) NOT NULL,
    DEBTOR_BIC VARCHAR2(255),
    DEBTOR_NAME VARCHAR2(255) NOT NULL,
    DEBTOR_COUNTRY_CODE VARCHAR2(255) NOT NULL,
    PRODUCT_CODE VARCHAR2(255) NOT NULL,
    PRODUCT_NAME VARCHAR2(255) NOT NULL,
    MANDATE_SIGNATURE_DATE DATE NOT NULL,
    MANDATE_EFFECTIVE_DATE DATE NOT NULL,
    MANDATE_CANCELLATION_DATE DATE,
    MANDATE_STATUS VARCHAR2(255) NOT NULL,
    MANDATE_STATUS_REASON VARCHAR2(255),
    SEPA_SCHEME_TYPE VARCHAR2(255) NOT NULL,
    FIRST_COLLECTION_DATE DATE,
    LAST_COLLECTION_DATE DATE,
    COLLECTION_FREQUENCY VARCHAR2(255) NOT NULL,
    MAX_COLLECTION_AMOUNT NUMBER(15,2),
    CURRENCY_CODE VARCHAR2(255) NOT NULL,
    MANDATE_CHANNEL VARCHAR2(255) NOT NULL,
    VERIFICATION_STATUS VARCHAR2(255) NOT NULL,
    VERIFICATION_METHOD VARCHAR2(255),
    VERIFICATION_TIMESTAMP TIMESTAMP,
    VERIFICATION_AGENT_ID VARCHAR2(255),
    RISK_SCORE NUMBER(5,2),
    RISK_CATEGORY VARCHAR2(255),
    PORTFOLIO_SEGMENT VARCHAR2(255) NOT NULL,
    MASREPH_CUSTOMER_ID VARCHAR2(255) NOT NULL,
    CUSTOMER_TENURE_MONTHS NUMBER(18,0),
    CROSS_SELL_ELIGIBILITY_FLAG NUMBER(1) NOT NULL,
    EXPECTED_ANNUAL_REVENUE NUMBER(15,2),
    REALIZED_ANNUAL_REVENUE NUMBER(15,2),
    REVENUE_FORECAST_ACCURACY_PCT NUMBER(5,2),
    CHURN_RISK_FLAG NUMBER(1) NOT NULL,
    MANDATE_UTILIZATION_RATIO NUMBER(6,4),
    CHARGEBACK_INCIDENT_COUNT NUMBER(18,0) NOT NULL,
    LAST_CHARGEBACK_DATE DATE,
    GDPR_CONSENT_FLAG NUMBER(1) NOT NULL,
    DATA_LINEAGE_REFERENCE CLOB,
    RECORD_CREATION_TIMESTAMP TIMESTAMP NOT NULL,
    RECORD_LAST_UPDATE_TIMESTAMP TIMESTAMP NOT NULL,
    SOURCE_SYSTEM_NAME VARCHAR2(255) NOT NULL,
    SYS_CR_DT TIMESTAMP,
    SYS_UPD_DT TIMESTAMP
    ,CONSTRAINT PK_SEPA_MANDATE_VERIFIC PRIMARY KEY (ID)
);


