-- ============================================
-- Platform: DATABRICKS
-- Schema/Source: salesforce_customer_insights
-- Generated: 2026-03-18T12:18:16.830944
-- Datasets: 8
-- ============================================

-- Dataset: GDS10037
CREATE SCHEMA IF NOT EXISTS salesforce_customer_insights;

-- This client dataset supports commercial finance operations. Key applications include relationship ma
CREATE TABLE IF NOT EXISTS salesforce_customer_insights.propensity_cube_leads_dataset_ (
    id INT NOT NULL,
    lead_id STRING NOT NULL,
    client_master_id STRING,
    crm_account_id STRING,
    company_legal_name STRING NOT NULL,
    industry_sector_code STRING NOT NULL,
    industry_sector_name STRING NOT NULL,
    country_of_incorporation_code STRING NOT NULL,
    domicile_country_name STRING NOT NULL,
    relationship_manager_id STRING,
    relationship_manager_name STRING,
    lead_created_timestamp TIMESTAMP NOT NULL,
    lead_last_updated_timestamp TIMESTAMP NOT NULL,
    lead_status_code STRING NOT NULL,
    lead_status_description STRING NOT NULL,
    lead_source_code STRING,
    lead_source_description STRING,
    propensity_score DECIMAL(5,4) NOT NULL,
    propensity_score_band STRING NOT NULL,
    probability_to_convert_pct DECIMAL(5,2) NOT NULL,
    expected_annual_revenue_amount DECIMAL(15,2),
    expected_annual_revenue_currency_code STRING,
    expected_product_margin_bps INT,
    primary_product_interest_code STRING,
    primary_product_interest_description STRING,
    is_existing_client_flag BOOLEAN NOT NULL,
    gdpr_marketing_consent_flag BOOLEAN NOT NULL,
    last_contact_date DATE,
    next_planned_contact_date DATE,
    primary_contact_full_name STRING,
    contact_email_address STRING,
    contact_phone_number STRING,
    client_profitability_segment_code STRING,
    client_profitability_segment_description STRING,
    lead_priority_rank INT,
    data_source_system_code STRING NOT NULL,
    record_effective_date DATE NOT NULL,
    _loaded_at TIMESTAMP,
    _source_file STRING
    ,CONSTRAINT PK_propensity_cube_lead PRIMARY KEY (id)
);


-- Dataset: GDS15860
CREATE SCHEMA IF NOT EXISTS salesforce_customer_insights;

-- This client dataset supports leasing operations. Key applications include relationship management, c
CREATE TABLE IF NOT EXISTS salesforce_customer_insights.customer_interaction_dataset (
    id INT NOT NULL,
    interaction_id STRING NOT NULL,
    customer_id STRING NOT NULL,
    leasing_account_id STRING,
    interaction_channel STRING NOT NULL,
    interaction_type STRING NOT NULL,
    interaction_subtype STRING,
    interaction_direction STRING NOT NULL,
    interaction_start_timestamp TIMESTAMP NOT NULL,
    interaction_end_timestamp TIMESTAMP,
    interaction_duration_seconds INT,
    interaction_subject STRING,
    interaction_summary STRING,
    interaction_detail_redacted STRING,
    agent_id STRING,
    agent_role STRING,
    relationship_manager_id STRING,
    product_segment STRING,
    lease_contract_number STRING,
    customer_segment STRING,
    customer_residency_country_code STRING,
    customer_industry_code STRING,
    customer_profitability_score DECIMAL(7,4),
    interaction_outcome_code STRING,
    follow_up_required_flag BOOLEAN NOT NULL,
    follow_up_due_date DATE,
    follow_up_owner_id STRING,
    complaint_indicator BOOLEAN NOT NULL,
    complaint_severity_code STRING,
    sales_opportunity_flag BOOLEAN NOT NULL,
    sales_opportunity_value DECIMAL(15,2),
    cross_sell_product_code STRING,
    interaction_sentiment_score DECIMAL(5,2),
    interaction_language_code STRING,
    customer_contact_point STRING,
    customer_consent_marketing_flag BOOLEAN NOT NULL,
    customer_consent_last_updated_date DATE,
    data_retention_expiry_date DATE,
    gdpr_legal_basis_code STRING,
    recording_reference_id STRING,
    email_message_id STRING,
    chat_session_id STRING,
    call_recording_quality_score DECIMAL(4,2),
    data_source_system_code STRING NOT NULL,
    _loaded_at TIMESTAMP,
    _source_file STRING
    ,CONSTRAINT PK_customer_interaction PRIMARY KEY (id)
);


-- Dataset: GDS25677
CREATE SCHEMA IF NOT EXISTS salesforce_customer_insights;

-- This client dataset supports commercial finance operations. Key applications include relationship ma
CREATE TABLE IF NOT EXISTS salesforce_customer_insights.revmax_finance_dataset (
    id INT NOT NULL,
    client_id STRING NOT NULL,
    masreph_party_id STRING NOT NULL,
    global_client_lei STRING,
    client_legal_name STRING NOT NULL,
    client_segment_code STRING NOT NULL,
    client_segment_description STRING NOT NULL,
    industry_naics_code STRING,
    industry_description STRING,
    country_of_risk_code STRING NOT NULL,
    relationship_manager_id STRING NOT NULL,
    relationship_manager_name STRING NOT NULL,
    client_onboarding_date DATE NOT NULL,
    relationship_start_date DATE,
    relationship_status STRING NOT NULL,
    relationship_status_effective_date DATE NOT NULL,
    primary_contact_email STRING,
    primary_contact_phone STRING,
    contact_preference_channels ARRAY<STRING>,
    consent_to_marketing_flag BOOLEAN NOT NULL,
    gdpr_processing_basis STRING,
    last_contact_timestamp TIMESTAMP,
    last_contact_channel STRING,
    total_committed_exposure_eur DECIMAL(18,2),
    total_outstanding_balance_eur DECIMAL(18,2),
    annual_client_revenue_eur DECIMAL(18,2),
    annual_bank_revenue_eur DECIMAL(18,2),
    cross_sell_score DECIMAL(5,2),
    profitability_tier STRING,
    client_lifetime_value_eur DECIMAL(18,2),
    wallet_share_percentage DECIMAL(5,2),
    churn_risk_score DECIMAL(5,2),
    credit_rating_internal STRING,
    credit_rating_external STRING,
    next_review_date DATE,
    pipeline_deal_count_active INT,
    pipeline_deal_total_expected_revenue_eur DECIMAL(18,2),
    last_product_purchased STRING,
    preferred_contact_language STRING,
    kyc_review_status STRING,
    data_source_system STRING NOT NULL,
    record_last_updated_timestamp TIMESTAMP NOT NULL,
    _loaded_at TIMESTAMP,
    _source_file STRING
    ,CONSTRAINT PK_revmax_finance_datas PRIMARY KEY (id)
);


-- Dataset: GDS39731
CREATE SCHEMA IF NOT EXISTS salesforce_customer_insights;

-- This client dataset supports leasing operations. Key applications include relationship management, c
CREATE TABLE IF NOT EXISTS salesforce_customer_insights.finance_review_tracker (
    id INT NOT NULL,
    finance_review_id STRING NOT NULL,
    client_id STRING NOT NULL,
    client_legal_name STRING NOT NULL,
    client_segment STRING,
    relationship_manager_id STRING,
    relationship_manager_name STRING,
    review_period_start_date DATE NOT NULL,
    review_period_end_date DATE NOT NULL,
    latest_review_timestamp TIMESTAMP NOT NULL,
    review_status STRING NOT NULL,
    primary_leasing_product STRING,
    active_lease_contract_count INT NOT NULL,
    total_leased_asset_value DECIMAL(18,2),
    outstanding_lease_balance DECIMAL(18,2),
    average_lease_term_months INT,
    client_industry_code STRING,
    client_country_of_risk STRING,
    client_profitability_score DECIMAL(5,2),
    net_interest_income_amount DECIMAL(18,2),
    fee_and_commission_income_amount DECIMAL(18,2),
    direct_servicing_cost_amount DECIMAL(18,2),
    expected_credit_loss_amount DECIMAL(18,2),
    risk_adjusted_return_on_capital DECIMAL(6,3),
    client_lifetime_value_estimate DECIMAL(20,2),
    client_onboarding_date DATE,
    last_contact_timestamp TIMESTAMP,
    next_scheduled_review_date DATE,
    client_risk_rating STRING,
    probability_of_default_1y DECIMAL(6,4),
    days_past_due_max INT,
    is_watchlist_client BOOLEAN NOT NULL,
    watchlist_since_date DATE,
    client_contact_channel_preference STRING,
    primary_contact_email_masked STRING,
    primary_contact_phone_masked STRING,
    relationship_tenure_years DECIMAL(5,2),
    cross_sell_opportunity_score DECIMAL(5,2),
    churn_risk_score DECIMAL(5,2),
    service_issue_count INT NOT NULL,
    average_response_time_hours DECIMAL(7,2),
    client_satisfaction_index DECIMAL(4,1),
    archival_flag BOOLEAN NOT NULL,
    archival_timestamp TIMESTAMP,
    data_privacy_level STRING NOT NULL,
    associated_product_codes ARRAY<STRING>,
    annual_turnover_reported DECIMAL(20,2),
    ebitda_margin_percentage DECIMAL(6,3),
    created_timestamp TIMESTAMP NOT NULL,
    last_modified_timestamp TIMESTAMP NOT NULL,
    _loaded_at TIMESTAMP,
    _source_file STRING
    ,CONSTRAINT PK_finance_review_track PRIMARY KEY (id)
);


-- Dataset: GDS49817
CREATE SCHEMA IF NOT EXISTS salesforce_customer_insights;

-- This client dataset supports leasing operations. Key applications include relationship management, c
CREATE TABLE IF NOT EXISTS salesforce_customer_insights.interacttask_finance_data (
    id INT NOT NULL,
    dataset_record_id STRING NOT NULL,
    client_id STRING NOT NULL,
    client_legal_name STRING NOT NULL,
    client_segment_code STRING NOT NULL,
    client_segment_description STRING,
    industry_naics_code STRING,
    industry_description STRING,
    country_of_incorporation STRING NOT NULL,
    primary_contact_id STRING,
    primary_contact_email STRING,
    relationship_manager_id STRING NOT NULL,
    relationship_manager_name STRING NOT NULL,
    client_onboarding_date DATE NOT NULL,
    client_termination_date DATE,
    client_status STRING NOT NULL,
    kyc_review_status STRING NOT NULL,
    kyc_last_review_date DATE,
    risk_rating_internal STRING,
    risk_rating_external_agency STRING,
    total_outstanding_leased_amount DECIMAL(18,2) NOT NULL,
    total_lease_limit_amount DECIMAL(18,2) NOT NULL,
    lease_utilization_ratio DECIMAL(5,2) NOT NULL,
    avg_lease_tenor_months INT,
    import_finance_exposure_amount DECIMAL(18,2),
    export_finance_exposure_amount DECIMAL(18,2),
    cross_border_trade_volume_12m DECIMAL(18,2),
    client_profitability_score DECIMAL(6,2),
    net_interest_income_12m DECIMAL(18,2),
    fee_income_12m DECIMAL(18,2),
    credit_loss_provision_12m DECIMAL(18,2),
    relationship_tenure_months INT,
    last_interaction_timestamp TIMESTAMP,
    last_interaction_channel STRING,
    last_interaction_outcome STRING,
    interaction_frequency_90d INT,
    active_leasing_contract_count INT NOT NULL,
    watchlist_flag BOOLEAN NOT NULL,
    aml_monitoring_flag BOOLEAN NOT NULL,
    data_privacy_consent_flag BOOLEAN NOT NULL,
    gdpr_erasure_request_flag BOOLEAN NOT NULL,
    client_preferred_language STRING,
    client_group_id STRING,
    client_group_name STRING,
    strategic_import_export_focus STRING,
    next_scheduled_review_date DATE,
    revenue_growth_rate_12m DECIMAL(6,2),
    client_satisfaction_index DECIMAL(5,2),
    data_source_system_code STRING NOT NULL,
    record_last_updated_timestamp TIMESTAMP NOT NULL,
    _loaded_at TIMESTAMP,
    _source_file STRING
    ,CONSTRAINT PK_interacttask_finance PRIMARY KEY (id)
);


-- Dataset: GDS72838
CREATE SCHEMA IF NOT EXISTS salesforce_customer_insights;

-- This client dataset supports leasing operations. Key applications include relationship management, c
CREATE TABLE IF NOT EXISTS salesforce_customer_insights.revtrack_finance_data (
    id INT NOT NULL,
    client_id STRING NOT NULL,
    masreph_party_number STRING NOT NULL,
    client_global_lei STRING,
    client_segment_code STRING NOT NULL,
    client_segment_description STRING,
    primary_relationship_manager_id STRING NOT NULL,
    primary_relationship_manager_name STRING,
    client_relationship_tenure_months INT NOT NULL,
    client_onboarding_date DATE NOT NULL,
    client_status STRING NOT NULL,
    client_residency_country_iso STRING NOT NULL,
    client_industry_nace_code STRING,
    client_industry_description STRING,
    group_parent_client_id STRING,
    is_group_parent BOOLEAN NOT NULL,
    client_confidentiality_level STRING NOT NULL,
    preferred_communication_channel STRING,
    gdpr_marketing_consent_flag BOOLEAN NOT NULL,
    gdpr_consent_last_updated TIMESTAMP,
    client_primary_language_code STRING,
    last_relationship_review_date DATE,
    next_scheduled_review_date DATE,
    leasing_portfolio_outstanding_balance DECIMAL(18,2) NOT NULL,
    leasing_annualized_revenue DECIMAL(18,2) NOT NULL,
    leasing_net_interest_margin_pct DECIMAL(5,2),
    total_leasing_contract_count INT NOT NULL,
    active_leasing_contract_count INT NOT NULL,
    average_contract_tenor_months INT,
    client_profitability_score INT,
    client_profitability_band STRING,
    cross_sell_opportunity_score INT,
    primary_leasing_product_family STRING,
    client_risk_rating_internal STRING,
    payment_behaviour_indicator STRING,
    days_past_due_max_12m INT,
    last_contact_timestamp TIMESTAMP,
    last_contact_channel STRING,
    open_service_ticket_count INT NOT NULL,
    avg_service_resolution_time_hours DECIMAL(7,2),
    client_satisfaction_score INT,
    churn_risk_level STRING,
    strategic_account_flag BOOLEAN NOT NULL,
    relationship_plan_presence_flag BOOLEAN NOT NULL,
    relationship_plan_last_updated DATE,
    pipeline_opportunity_volume_12m DECIMAL(18,2),
    primary_banking_country_iso STRING,
    masked_contact_email STRING,
    preferred_contact_time_window STRING,
    data_record_created_timestamp TIMESTAMP NOT NULL,
    data_record_last_modified_timestamp TIMESTAMP NOT NULL,
    _loaded_at TIMESTAMP,
    _source_file STRING
    ,CONSTRAINT PK_revtrack_finance_dat PRIMARY KEY (id)
);


-- Dataset: GDS92948
CREATE SCHEMA IF NOT EXISTS salesforce_customer_insights;

-- This client dataset supports commercial finance operations. Key applications include relationship ma
CREATE TABLE IF NOT EXISTS salesforce_customer_insights.interacttask_finance_data (
    id INT NOT NULL,
    client_id STRING NOT NULL,
    client_legal_name STRING NOT NULL,
    client_industry_code STRING NOT NULL,
    client_industry_description STRING,
    client_segment STRING NOT NULL,
    client_group_id STRING,
    country_of_incorporation STRING NOT NULL,
    primary_relationship_manager_id STRING NOT NULL,
    primary_relationship_manager_name STRING NOT NULL,
    client_onboarding_date DATE NOT NULL,
    relationship_status STRING NOT NULL,
    relationship_status_effective_date DATE NOT NULL,
    last_interaction_timestamp TIMESTAMP,
    last_interaction_channel STRING,
    interaction_count_12m INT NOT NULL,
    open_opportunity_count INT NOT NULL,
    total_commitment_amount DECIMAL(18,2),
    outstanding_balance_amount DECIMAL(18,2),
    relationship_base_currency STRING NOT NULL,
    net_interest_income_12m DECIMAL(18,2),
    fee_income_12m DECIMAL(18,2),
    direct_costs_12m DECIMAL(18,2),
    client_profit_before_tax_12m DECIMAL(18,2),
    return_on_rwa_12m DECIMAL(7,4),
    cross_sell_score DECIMAL(5,2),
    wallet_share_estimate_pct DECIMAL(5,2),
    client_risk_rating STRING,
    risk_rating_effective_date DATE,
    kyc_review_next_due_date DATE,
    gdpr_consent_flag BOOLEAN NOT NULL,
    data_anonymized_flag BOOLEAN NOT NULL,
    archival_status STRING NOT NULL,
    archival_timestamp TIMESTAMP,
    primary_contact_email STRING,
    primary_contact_role STRING,
    advisory_mandate_active_flag BOOLEAN NOT NULL,
    active_advisory_mandate_count INT NOT NULL,
    last_advisory_mandate_close_date DATE,
    prospect_probability_score DECIMAL(5,4),
    relationship_tenure_years DECIMAL(6,2),
    strategic_importance_tier STRING,
    key_product_holdings ARRAY<STRING>,
    annual_revenue_client_reported DECIMAL(18,2),
    employee_count_client_reported INT,
    client_preferred_language STRING,
    client_profile_metadata MAP<STRING, STRING>,
    _loaded_at TIMESTAMP,
    _source_file STRING
    ,CONSTRAINT PK_interacttask_finance PRIMARY KEY (id)
);


-- Dataset: GDS99977
CREATE SCHEMA IF NOT EXISTS salesforce_customer_insights;

-- This client dataset supports leasing operations. Key applications include relationship management, c
CREATE TABLE IF NOT EXISTS salesforce_customer_insights.trade_finance_crm_data (
    id INT NOT NULL,
    client_id STRING NOT NULL,
    crm_account_id STRING NOT NULL,
    parent_group_id STRING,
    client_legal_name STRING NOT NULL,
    client_segment STRING NOT NULL,
    industry_nace_code STRING,
    tax_identification_number_hash STRING,
    client_residency_country STRING NOT NULL,
    gdpr_consent_flag BOOLEAN NOT NULL,
    primary_relationship_manager_id STRING NOT NULL,
    relationship_start_date DATE NOT NULL,
    relationship_status STRING NOT NULL,
    last_contact_timestamp TIMESTAMP,
    preferred_contact_channel STRING,
    primary_contact_email STRING,
    primary_contact_phone STRING,
    crm_lead_source STRING,
    client_rating_internal STRING,
    credit_rating_external STRING,
    annual_turnover_eur DECIMAL(18,2),
    trade_finance_revenue_ytd_eur DECIMAL(18,2),
    trade_finance_revenue_ttm_eur DECIMAL(18,2),
    client_profitability_score DECIMAL(5,2),
    leasing_outstanding_exposure_eur DECIMAL(18,2),
    trade_finance_product_mix ARRAY<STRING>,
    cross_sell_potential_score DECIMAL(4,2),
    client_risk_appetite_category STRING,
    kyc_review_status STRING NOT NULL,
    kyc_next_review_date DATE,
    sanctions_screening_flag BOOLEAN NOT NULL,
    onboarding_channel STRING,
    onboarding_completion_date DATE,
    primary_operating_currency STRING,
    average_tenor_leasing_months INT,
    number_of_active_leases INT NOT NULL,
    overdue_lease_payments_flag BOOLEAN NOT NULL,
    last_overdue_event_date DATE,
    client_lifecycle_stage STRING NOT NULL,
    strategic_account_flag BOOLEAN NOT NULL,
    account_plan_last_update TIMESTAMP,
    next_review_meeting_date DATE,
    esg_profile_rating STRING,
    primary_registered_address_country STRING,
    client_contact_preferences MAP<STRING, STRING>,
    client_notes_latest STRING,
    crm_record_created_timestamp TIMESTAMP NOT NULL,
    crm_record_last_modified_timestamp TIMESTAMP NOT NULL,
    data_source_system STRING NOT NULL,
    record_archived_flag BOOLEAN NOT NULL,
    _loaded_at TIMESTAMP,
    _source_file STRING
    ,CONSTRAINT PK_trade_finance_crm_da PRIMARY KEY (id)
);


